/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#ifndef _cimple_CMPL_Cross_h
#define _cimple_CMPL_Cross_h

#include <cimple/cimple.h>
#include "CMPL_Left.h"
#include "CMPL_Right.h"

#if (0x00632D00 > CIMPLE_VERSION)
# error "The version of genclass used to generate this file (0.99.45) is newer than the version of <cimple/cimple.h> found on the include path. Please place the matching version of <cimple/cimple.h> on the include path."
#endif

#if (0x00632D00 < CIMPLE_VERSION)
# error "The version of genclass used to generate this file (0.99.45) is older than the version of <cimple/cimple.h> found on the include path. Please regenerate the sources with the matching version of genclass."
#endif


CIMPLE_NAMESPACE_BEGIN

class CMPL_Cross : public Instance
{
public:
    // CMPL_Cross features:
    CMPL_Left* left;
    CMPL_Right* right;

    CIMPLE_CLASS(CMPL_Cross)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_CMPL_Cross_h */
