/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#ifndef _cimple_CMPL_Right_h
#define _cimple_CMPL_Right_h

#include <cimple/cimple.h>

CIMPLE_NAMESPACE_BEGIN

// CMPL_Right keys:
//     key

class CMPL_Right : public Instance
{
public:
    // CMPL_Right features:
    Property<uint32> key;

    CIMPLE_CLASS(CMPL_Right)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_CMPL_Right_h */
