/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "CMPL_Cross.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_F4E528F227ED1CBD8BD1773E04D0F0A0;

extern const Meta_Reference
_CMPL_Cross_left;

const Meta_Reference
_CMPL_Cross_left =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_KEY,
    "left",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    &CMPL_Left::static_meta_class,
    CIMPLE_OFF(CMPL_Cross,left)
};

extern const Meta_Reference
_CMPL_Cross_right;

const Meta_Reference
_CMPL_Cross_right =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_KEY,
    "right",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    &CMPL_Right::static_meta_class,
    CIMPLE_OFF(CMPL_Cross,right)
};

static Meta_Feature* _CMPL_Cross_MFA[] =
{
    (Meta_Feature*)&_CMPL_Cross_left,
    (Meta_Feature*)&_CMPL_Cross_right,
};

static const Meta_Feature_Local _locals[] =
{
    {1},
    {1},
};

const Meta_Class CMPL_Cross::static_meta_class =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_ASSOCIATION,
    "CMPL_Cross",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _CMPL_Cross_MFA,
    CIMPLE_ARRAY_SIZE(_CMPL_Cross_MFA),
    sizeof(CMPL_Cross),
    _locals,
    0, /* super_class */ 
    2, /* num_keys */
    0xDD2EC491, /* crc */
    &__meta_repository_F4E528F227ED1CBD8BD1773E04D0F0A0,
};

CIMPLE_NAMESPACE_END

CIMPLE_ID("$Header: /home/cvs/cimple/src/providers/Cross/CMPL_Cross.cpp,v 1.2 2007/03/07 20:25:24 mbrasher-public Exp $");
