/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.0.22
//
//==============================================================================

#ifndef _cimple_Right_h
#define _cimple_Right_h

#include <cimple/cimple.h>

CIMPLE_NAMESPACE_BEGIN

// Right keys:
//     key

/*[928]*/
class Right : public Instance
{
public:
    // Right features:
    Property<uint32> key;

    CIMPLE_CLASS(Right)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_Right_h */
