/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.5
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "CIMPLE_ExceptionLink.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_5C36F0E1DDB21B1D815B3034F5BB8D9D;

/*[1389]*/
extern const Meta_Reference
_CIMPLE_ExceptionLink_left;

/*[1400]*/
const Meta_Reference
_CIMPLE_ExceptionLink_left =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_KEY,
    "left",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    0, /* subscript */
    &CIMPLE_Exception::static_meta_class,
    CIMPLE_OFF(CIMPLE_ExceptionLink,left)
};

/*[1389]*/
extern const Meta_Reference
_CIMPLE_ExceptionLink_right;

/*[1400]*/
const Meta_Reference
_CIMPLE_ExceptionLink_right =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_KEY,
    "right",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    0, /* subscript */
    &CIMPLE_Exception::static_meta_class,
    CIMPLE_OFF(CIMPLE_ExceptionLink,right)
};

/*[1518]*/
static const Meta_Property
_CIMPLE_ExceptionLink_setException_Exception =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "Exception",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(CIMPLE_ExceptionLink_setException_method,Exception),
    0, /* value */
};

/*[1518]*/
static const Meta_Property
_CIMPLE_ExceptionLink_setException_getInstanceDefault =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "getInstanceDefault",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    BOOLEAN,
    0,
    CIMPLE_OFF(CIMPLE_ExceptionLink_setException_method,getInstanceDefault),
    0, /* value */
};

/*[1518]*/
static const Meta_Property
_CIMPLE_ExceptionLink_setException_associatorsDefault =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "associatorsDefault",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    BOOLEAN,
    0,
    CIMPLE_OFF(CIMPLE_ExceptionLink_setException_method,associatorsDefault),
    0, /* value */
};

/*[1671]*/
static const Meta_Property
_CIMPLE_ExceptionLink_setException_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(CIMPLE_ExceptionLink_setException_method,return_value),
    0, /* value */
};

/*[1647]*/
static Meta_Feature* _CIMPLE_ExceptionLink_setException_MFA[] =
{
    (Meta_Feature*)(void*)&_CIMPLE_ExceptionLink_setException_Exception,
    (Meta_Feature*)(void*)&_CIMPLE_ExceptionLink_setException_getInstanceDefault,
    (Meta_Feature*)(void*)&_CIMPLE_ExceptionLink_setException_associatorsDefault,
    (Meta_Feature*)(void*)&_CIMPLE_ExceptionLink_setException_return_value
};

/*[1849]*/
const Meta_Method
CIMPLE_ExceptionLink_setException_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "setException",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _CIMPLE_ExceptionLink_setException_MFA,
    CIMPLE_ARRAY_SIZE(_CIMPLE_ExceptionLink_setException_MFA),
    sizeof(CIMPLE_ExceptionLink_setException_method),
    UINT32,
};

/*[1671]*/
static const Meta_Property
_CIMPLE_ExceptionLink_testException_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(CIMPLE_ExceptionLink_testException_method,return_value),
    0, /* value */
};

/*[1647]*/
static Meta_Feature* _CIMPLE_ExceptionLink_testException_MFA[] =
{
    (Meta_Feature*)(void*)&_CIMPLE_ExceptionLink_testException_return_value
};

/*[1849]*/
const Meta_Method
CIMPLE_ExceptionLink_testException_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "testException",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _CIMPLE_ExceptionLink_testException_MFA,
    CIMPLE_ARRAY_SIZE(_CIMPLE_ExceptionLink_testException_MFA),
    sizeof(CIMPLE_ExceptionLink_testException_method),
    UINT32,
};

/*[2027]*/
static Meta_Feature* _CIMPLE_ExceptionLink_MFA[] =
{
    (Meta_Feature*)(void*)&_CIMPLE_ExceptionLink_left,
    (Meta_Feature*)(void*)&_CIMPLE_ExceptionLink_right,
    (Meta_Feature*)(void*)&CIMPLE_ExceptionLink_setException_method::static_meta_class,
    (Meta_Feature*)(void*)&CIMPLE_ExceptionLink_testException_method::static_meta_class,
};

/*[2074]*/
static const Meta_Feature_Local _locals[] =
{
    {1},
    {1},
    {1},
    {1},
};

/*[2094]*/
const Meta_Class CIMPLE_ExceptionLink::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_ASSOCIATION,
    "CIMPLE_ExceptionLink",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _CIMPLE_ExceptionLink_MFA,
    CIMPLE_ARRAY_SIZE(_CIMPLE_ExceptionLink_MFA),
    sizeof(CIMPLE_ExceptionLink),
    _locals,
    0, /* super_class */ 
    2, /* num_keys */
    &__meta_repository_5C36F0E1DDB21B1D815B3034F5BB8D9D,
};

CIMPLE_NAMESPACE_END

