// Copyright (c) 2005 DMTF.  All rights reserved.
// ==================================================================
//  CIM_J2eeSessionBean
// ==================================================================
   [Abstract, Version ( "2.8.0" ), Description (
       "The CIM_J2eeSessionBean class is a base class that represents "
       "specific types of deployed Session beans.")]
class CIM_J2eeSessionBean : CIM_J2eeEJB {
};
