TOP = ../../../..
include $(TOP)/mak/config.mak

BINARY = test_mutex
SOURCES = main.cpp
LIBRARIES = cimple

include $(TOP)/mak/rules.mak

tests:
	@ $(BIN_DIR)/test_mutex

genclass:

xxx:
	echo $(TARGET)
