
[Description("")]
class Upcall2Part : CIM_RegisteredProfile
{
};

[Association , Description("")]
class Upcall2 : CIM_ElementConformsToProfile
{
   // in root/adpt namespace
   [Override ("ConformantStandard")]
   Upcall2Part REF ConformantStandard; 

   //refers to root/ibmsd namespace object
   [Override ("ManagedElement")]
   CIM_ComputerSystem REF ManagedElement; 
};
