//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#include <cimple/cimple.h>
#include "repository.h"

CIMPLE_NAMESPACE_BEGIN

static const Meta_Class* _meta_classes[] =
{
    &Part::static_meta_class,
    &Glue::static_meta_class,
};

static const size_t _num_meta_classes = CIMPLE_ARRAY_SIZE(_meta_classes);

extern const Meta_Repository __meta_repository_B2486018BB8512E1BE392A1E79FC574D;

const Meta_Repository __meta_repository_B2486018BB8512E1BE392A1E79FC574D =
{
    _meta_classes,
    _num_meta_classes,
};

CIMPLE_NAMESPACE_END
