/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.0.3
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "BUG31_A.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_CE2FDEBA768A1A15997A464B13444CBC;

extern const Meta_Property
_BUG31_A_prop1;

const Meta_Property
_BUG31_A_prop1 =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "prop1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0, /* subscript */
    CIMPLE_OFF(BUG31_A,prop1),
    0, /* value */
};

static Meta_Feature* _BUG31_A_MFA[] =
{
    (Meta_Feature*)(void*)&_BUG31_A_prop1,
};

static const Meta_Feature_Local _locals[] =
{
    {1},
};

const Meta_Class BUG31_A::static_meta_class =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_CLASS,
    "BUG31_A",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _BUG31_A_MFA,
    CIMPLE_ARRAY_SIZE(_BUG31_A_MFA),
    sizeof(BUG31_A),
    _locals,
    0, /* super_class */ 
    0, /* num_keys */
    &__meta_repository_CE2FDEBA768A1A15997A464B13444CBC,
};

CIMPLE_NAMESPACE_END

