/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#ifndef _cimple_BUG31_B_h
#define _cimple_BUG31_B_h

#include <cimple/cimple.h>
#include "BUG31_A.h"

#if (0x00633800 > CIMPLE_VERSION)
# error "The version of genclass used to generate this file (0.99.56) is newer than the version of <cimple/cimple.h> found on the include path. Please place the matching version of <cimple/cimple.h> on the include path."
#endif

#if (0x00633800 < CIMPLE_VERSION)
# error "The version of genclass used to generate this file (0.99.56) is older than the version of <cimple/cimple.h> found on the include path. Please regenerate the sources with the matching version of genclass."
#endif


CIMPLE_NAMESPACE_BEGIN

class BUG31_B : public Instance
{
public:
    // BUG31_A features:
    Property<uint32> prop1;

    // BUG31_B features:
    Property<uint32> key; // KEY

    CIMPLE_CLASS(BUG31_B)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_BUG31_B_h */
