/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.23
//
//==============================================================================

#ifndef _cimple_CMPL_Base_h
#define _cimple_CMPL_Base_h

#include <cimple/cimple.h>

CIMPLE_NAMESPACE_BEGIN

// CMPL_Base keys:
//     Key

/*[1194]*/
class CMPL_Base : public Instance
{
public:
    // CMPL_Base features:
    Property<uint32> Key;
    Property<String> info;

    CIMPLE_CLASS(CMPL_Base)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_CMPL_Base_h */
