#pragma locale ("en_US")

instance of PG_ProviderModule
{
    Description = "MyIndicationProviderModule";
    Caption = "MyIndicationProviderModule";
    Name = "MyIndicationProviderModule";
    Vendor = "Pegasus";
    Version = "2.0.0";
    InterfaceType = "C++Default";
    InterfaceVersion = "2.2.0";
    Location = "MyIndicationProvider";
};

instance of PG_Provider
{
    ProviderModuleName = "MyIndicationProviderModule";
    Name = "MyIndicationProvider";
};

instance of PG_ProviderCapabilities
{
    ProviderModuleName = "MyIndicationProviderModule";
    ProviderName = "MyIndicationProvider";
    CapabilityID = "1";
    ClassName = "MyIndication";
    Namespaces = { "root/cimv2" };
    ProviderType = { 4 /* indication */, 5 /* method */ };
    SupportedProperties = NULL;
    SupportedMethods = { "DeliverIndications" };
};
