//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#ifndef _AAA2_h
#define _AAA2_h

#include <cimple/cimple.h>
#include "AAA.h"

CIMPLE_NAMESPACE_BEGIN

class AAA2 : public Instance
{
public:
    // AAA features:
    CCC* left;
    DDD* right;

    // AAA2 features:
    Property<uint32> aaa;

    CIMPLE_CLASS(AAA2)
};

class AAA2_fool_method : public Instance
{
public:
    CCC* c;
    Property<uint32> return_value;
    CIMPLE_METHOD(AAA2_fool_method)
};

CIMPLE_NAMESPACE_END

#endif /* _AAA2_h */
