//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "BBB.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

CIMPLE_HIDE
extern const Meta_Property _BBB_counter;

const Meta_Property _BBB_counter =
{
    CIMPLE_FLAG_PROPERTY,
    "counter",
    UINT32,
    0,
    CIMPLE_OFF(BBB,counter)
};

static Meta_Feature* _BBB_meta_features[] =
{
    (Meta_Feature*)&_BBB_counter,
};

const Meta_Class BBB::static_meta_class =
{
    CIMPLE_FLAG_CLASS,
    "BBB",
    _BBB_meta_features,
    CIMPLE_ARRAY_SIZE(_BBB_meta_features),
    sizeof(BBB),
    0,
    0,
    0x0F3721B9,
};

CIMPLE_NAMESPACE_END

