/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#ifndef _cimple_CCC_h
#define _cimple_CCC_h

#include <cimple/cimple.h>
#include "BBB.h"

#if (0x00633800 > CIMPLE_VERSION)
# error "The version of genclass used to generate this file (0.99.56) is newer than the version of <cimple/cimple.h> found on the include path. Please place the matching version of <cimple/cimple.h> on the include path."
#endif

#if (0x00633800 < CIMPLE_VERSION)
# error "The version of genclass used to generate this file (0.99.56) is older than the version of <cimple/cimple.h> found on the include path. Please regenerate the sources with the matching version of genclass."
#endif


CIMPLE_NAMESPACE_BEGIN

class CCC : public Instance
{
public:
    // BBB features:
    Property<uint32> counter;

    // CCC features:
    Property<String> key; // KEY
    Property<uint32> bbb; // KEY

    CIMPLE_CLASS(CCC)
};

class CCC_foo_method : public Instance
{
public:
    Property<String> arg1;
    Property<String> arg2;
    Property<uint32> return_value;
    CIMPLE_METHOD(CCC_foo_method)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_CCC_h */
