TOP = ../..
include $(TOP)/mak/config.mak

DIRS = utils \
       utils/tests/containers \
       adapter \
       clients \
       regmod  \
       cimlisten \
       regview \
       ciminvoke

include $(TOP)/mak/dir.mak
include check-pegasus.mak
