#!/bin/sh

if [ "$PEGASUS_ROOT" = "" ]; then
    echo "$0: Please define PEGASUS_ROOT"
    echo
    exit 1
fi

if [ ! -d "$PEGASUS_ROOT" ]; then
    echo "$0: No such directory: PEGASUS_ROOT=$PEGASUS_ROOT"
    echo
    exit 1
fi

if [ ! -d "$PEGASUS_ROOT/VXWORKS_XSCALE_GNU" ]; then
    echo "$0: No such directory: \$PEGASUS_ROOT/VXWORKS_XSCALE_GNU"
    echo
    exit 1
fi

./configure --host=arm-wrs-vxworks-gnu --prefix=$PEGASUS_ROOT/VXWORKS_XSCALE_GNU --with-pegasus-includes=$PEGASUS_ROOT/src --with-pegasus-libdir=$PEGASUS_ROOT/VXWORKS_XSCALE_GNU/lib
