//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.1.2
//
//==============================================================================

#ifndef _repository_h
#define _repository_h

#include <cimple/cimple.h>
#include "Class1.h"
#include "Assoc1.h"
#include "Class2.h"
#include "Class3.h"
#include "Class4.h"
#include "Class5.h"
#include "Assoc2.h"

CIMPLE_NAMESPACE_BEGIN

CIMPLE_NAMESPACE_END

#endif /* _repository_h */
