//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#include <cimple/cimple.h>
#include "repository.h"

CIMPLE_NAMESPACE_BEGIN

static const Meta_Class* _meta_classes[] =
{
    &House::static_meta_class,
    &Example::static_meta_class,
};

static const size_t _num_meta_classes = CIMPLE_ARRAY_SIZE(_meta_classes);

extern const Meta_Repository __meta_repository_069F1F3E4D89165BAE741B77034FF021;

const Meta_Repository __meta_repository_069F1F3E4D89165BAE741B77034FF021 =
{
    _meta_classes,
    _num_meta_classes,
};

CIMPLE_NAMESPACE_END
