//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.0.22
//
//==============================================================================

#include <cimple/cimple.h>
#include "repository.h"

CIMPLE_NAMESPACE_BEGIN

/*[2528]*/
static const Meta_Class* _meta_classes[] =
{
    &House::static_meta_class,
    &Example::static_meta_class,
};

static const size_t _num_meta_classes = CIMPLE_ARRAY_SIZE(_meta_classes);

extern const Meta_Repository __meta_repository_C7BF6C6FB00317A9BC783810AA2DB41F;

/*[2555]*/
const Meta_Repository __meta_repository_C7BF6C6FB00317A9BC783810AA2DB41F =
{
    _meta_classes,
    _num_meta_classes,
};

CIMPLE_NAMESPACE_END
