/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#ifndef _cimple_CIM_StorageSetting_h
#define _cimple_CIM_StorageSetting_h

#include <cimple/cimple.h>
#include "CIM_SettingData.h"

#if (0x00633300 > CIMPLE_VERSION)
# error "The version of genclass used to generate this file (0.99.51) is newer than the version of <cimple/cimple.h> found on the include path. Please place the matching version of <cimple/cimple.h> on the include path."
#endif

#if (0x00633300 < CIMPLE_VERSION)
# error "The version of genclass used to generate this file (0.99.51) is older than the version of <cimple/cimple.h> found on the include path. Please regenerate the sources with the matching version of genclass."
#endif


CIMPLE_NAMESPACE_BEGIN

class CIM_StorageSetting : public Instance
{
public:
    // CIM_ManagedElement features:
    Property<String> Caption;
    Property<String> Description;
    Property<String> ElementName;

    // CIM_SettingData features:
    Property<String> InstanceID; // KEY

    // CIM_StorageSetting features:
    Property<boolean> NoSinglePointOfFailure;
    Property<uint16> DataRedundancyMax;
    Property<uint16> DataRedundancyMin;
    Property<uint16> DataRedundancyGoal;
    Property<uint16> PackageRedundancyMax;
    Property<uint16> PackageRedundancyMin;
    Property<uint16> PackageRedundancyGoal;
    Property<uint8> DeltaReservationMax;
    Property<uint8> DeltaReservationMin;
    Property<uint8> DeltaReservationGoal;
    Property<uint16> ChangeableType;
    Property<uint16> ExtentStripeLength;
    Property<uint16> ExtentStripeLengthMin;
    Property<uint16> ExtentStripeLengthMax;
    Property<uint16> ParityLayout;
    Property<uint64> UserDataStripeDepth;
    Property<uint64> UserDataStripeDepthMin;
    Property<uint64> UserDataStripeDepthMax;

    CIMPLE_CLASS(CIM_StorageSetting)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_CIM_StorageSetting_h */
