//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#include <cimple/cimple.h>
#include "repository.h"

CIMPLE_NAMESPACE_BEGIN

static const Meta_Class* _meta_classes[] =
{
    &Hello::static_meta_class,
};

static const size_t _num_meta_classes = CIMPLE_ARRAY_SIZE(_meta_classes);

extern const Meta_Repository __meta_repository_1EF8761F95D6132EAF6BDA50670F490B;

const Meta_Repository __meta_repository_1EF8761F95D6132EAF6BDA50670F490B =
{
    _meta_classes,
    _num_meta_classes,
};

CIMPLE_NAMESPACE_END
