TOP = ../..
include $(TOP)/mak/config.mak

LIBRARY = cimpleutil

SOURCES = \
    util.cpp \
    crc.cpp \

LIBRARIES = -ldl -lpthread

FLAGS += -fno-rtti -fno-exceptions

include $(TOP)/mak/rules.mak

tests:

genclass:
