ROOT = $(PEGASUS_ROOT)
DIR = Pegasus/Client/tests/foo
include $(ROOT)/mak/config.mak
LIBRARIES = pegclient pegcommon

EXTRA_INCLUDES = $(SYS_INCLUDES)

PROGRAM = call_foo

SOURCES = main.cpp

include $(ROOT)/mak/program.mak

tests:

genclass:
