/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#ifndef _cimple_CIM_Collection_h
#define _cimple_CIM_Collection_h

#include <cimple/cimple.h>
#include "CIM_ManagedElement.h"

CIMPLE_NAMESPACE_BEGIN

class CIM_Collection : public Instance
{
public:
    // CIM_ManagedElement features:
    Property<String> Caption;
    Property<String> Description;
    Property<String> ElementName;

    // CIM_Collection features:

    CIMPLE_CLASS(CIM_Collection)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_CIM_Collection_h */
