TOP = ../../../..
include $(TOP)/mak/config.mak

BINARY = cimple_example
SOURCES = main.cpp TheClass.cpp example.cpp TheClass_Provider.cpp module.cpp
LIBRARIES = cimple
FLAGS += $(SIZE_OPTIMIZATION_FLAGS)

include $(TOP)/mak/rules.mak
