/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.1.2
//
//==============================================================================

#ifndef _cimple_LampIndicB_h
#define _cimple_LampIndicB_h

#include <cimple/cimple.h>
#include "LampIndic.h"

CIMPLE_NAMESPACE_BEGIN

// LampIndicB keys:

/*[928]*/
class LampIndicB : public Instance
{
public:
    // CIM_Indication features:
    Property<String> IndicationIdentifier;
    Property<Array_String> CorrelatedIndications;
    Property<Datetime> IndicationTime;
    Property<uint16> PerceivedSeverity;
    Property<String> OtherSeverity;

    // LampIndic features:
    Property<String> message;

    // LampIndicB features:
    Property<String> messageB;

    CIMPLE_CLASS(LampIndicB)
};

typedef LampIndic_DeliverIndications_method LampIndicB_DeliverIndications_method;

CIMPLE_NAMESPACE_END

#endif /* _cimple_LampIndicB_h */
