/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#ifndef _cimple_LampIndicC_h
#define _cimple_LampIndicC_h

#include <cimple/cimple.h>
#include "LampIndic.h"

CIMPLE_NAMESPACE_BEGIN

// LampIndicC keys:

class LampIndicC : public Instance
{
public:
    // CIM_Indication features:
    Property<String> IndicationIdentifier;
    Property<Array_String> CorrelatedIndications;
    Property<Datetime> IndicationTime;
    Property<uint16> PerceivedSeverity;
    Property<String> OtherSeverity;

    // LampIndic features:
    Property<String> message;

    // LampIndicC features:
    Property<String> messageC;

    CIMPLE_CLASS(LampIndicC)
};

typedef LampIndic_DeliverIndications_method LampIndicC_DeliverIndications_method;

CIMPLE_NAMESPACE_END

#endif /* _cimple_LampIndicC_h */
