/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.0.3
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "Lamp.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_8AF1FAAE16D61BBFA5D2D334913191BD;

extern const Meta_Property
_Lamp_model;

const Meta_Property
_Lamp_model =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_KEY|CIMPLE_FLAG_READ,
    "model",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    STRING,
    0, /* subscript */
    CIMPLE_OFF(Lamp,model),
    0, /* value */
};

extern const Meta_Property
_Lamp_vendor;

const Meta_Property
_Lamp_vendor =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "vendor",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    STRING,
    0, /* subscript */
    CIMPLE_OFF(Lamp,vendor),
    0, /* value */
};

extern const Meta_Property
_Lamp_wattage;

const Meta_Property
_Lamp_wattage =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "wattage",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0, /* subscript */
    CIMPLE_OFF(Lamp,wattage),
    0, /* value */
};

extern const Meta_Property
_Lamp_color;

const Meta_Property
_Lamp_color =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "color",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    STRING,
    0, /* subscript */
    CIMPLE_OFF(Lamp,color),
    0, /* value */
};

static const Meta_Property
_Lamp_foo_arg1 =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "arg1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    STRING,
    0,
    CIMPLE_OFF(Lamp_foo_method,arg1),
    0, /* value */
};

static const Meta_Property
_Lamp_foo_arg2 =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "arg2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    STRING,
    0,
    CIMPLE_OFF(Lamp_foo_method,arg2),
    0, /* value */
};

static const Meta_Property
_Lamp_foo_return_value =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(Lamp_foo_method,return_value),
    0, /* value */
};

static Meta_Feature* _Lamp_foo_MFA[] =
{
    (Meta_Feature*)(void*)&_Lamp_foo_arg1,
    (Meta_Feature*)(void*)&_Lamp_foo_arg2,
    (Meta_Feature*)(void*)&_Lamp_foo_return_value
};

const Meta_Method
Lamp_foo_method::static_meta_class =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_METHOD,
    "foo",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _Lamp_foo_MFA,
    CIMPLE_ARRAY_SIZE(_Lamp_foo_MFA),
    sizeof(Lamp_foo_method),
    UINT32,
};

static Meta_Feature* _Lamp_MFA[] =
{
    (Meta_Feature*)(void*)&_Lamp_model,
    (Meta_Feature*)(void*)&_Lamp_vendor,
    (Meta_Feature*)(void*)&_Lamp_wattage,
    (Meta_Feature*)(void*)&_Lamp_color,
    (Meta_Feature*)(void*)&Lamp_foo_method::static_meta_class,
};

static const Meta_Feature_Local _locals[] =
{
    {1},
    {1},
    {1},
    {1},
    {1},
};

const Meta_Class Lamp::static_meta_class =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_CLASS,
    "Lamp",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _Lamp_MFA,
    CIMPLE_ARRAY_SIZE(_Lamp_MFA),
    sizeof(Lamp),
    _locals,
    0, /* super_class */ 
    1, /* num_keys */
    &__meta_repository_8AF1FAAE16D61BBFA5D2D334913191BD,
};

CIMPLE_NAMESPACE_END

