//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#include <cimple/cimple.h>
#include "repository.h"

CIMPLE_NAMESPACE_BEGIN

static const Meta_Class* _meta_classes[] =
{
    &Static::static_meta_class,
};

static const size_t _num_meta_classes = CIMPLE_ARRAY_SIZE(_meta_classes);

extern const Meta_Repository __meta_repository_7400D548CF2614E59905A1CE809B5EE0;

const Meta_Repository __meta_repository_7400D548CF2614E59905A1CE809B5EE0 =
{
    _meta_classes,
    _num_meta_classes,
};

CIMPLE_NAMESPACE_END

CIMPLE_ID("$Header: /home/cvs/cimple/src/providers/Static/repository.cpp,v 1.3 2007/03/07 20:25:02 mbrasher-public Exp $");
