//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#ifndef _cimple_Test1_h
#define _cimple_Test1_h

#include <cimple/cimple.h>

CIMPLE_NAMESPACE_BEGIN

class Test1 : public Instance
{
public:
    // Test1 features:
    Property<String> key;

    CIMPLE_CLASS(Test1)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_Test1_h */
