/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.1.2
//
//==============================================================================

#ifndef _cimple_Test1_h
#define _cimple_Test1_h

#include <cimple/cimple.h>

CIMPLE_NAMESPACE_BEGIN

// Test1 keys:
//     key

/*[928]*/
class Test1 : public Instance
{
public:
    // Test1 features:
    Property<String> key;

    CIMPLE_CLASS(Test1)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_Test1_h */
