// Person class defined compatible with creation and registration
// of WMI provider

[dynamic, provider("Person")]
class Person
{
    [Key] string SSN;
    string FirstName;
    string LastName;


    [implemented, static]
    uint32 foo([in] string arg);

    [implemented, static]
    string foo1(
	[in] uint32 arg1, 
	[in] string arg2, 
	[in] boolean arg3,
	[in(false), out] uint32 arg4, 
	[in(false), out] string arg5, 
	[in(false), out] boolean arg6);
};
