//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.2.5
//
//==============================================================================

#include <cimple/cimple.h>
#include "repository.h"

CIMPLE_NAMESPACE_BEGIN

/*[2547]*/
static const Meta_Class* _meta_classes[] =
{
    &Person::static_meta_class,
};

static const size_t _num_meta_classes = CIMPLE_ARRAY_SIZE(_meta_classes);

extern const Meta_Repository __meta_repository_6878D911A61C1784B615057E2A1204DE;

/*[2574]*/
const Meta_Repository __meta_repository_6878D911A61C1784B615057E2A1204DE =
{
    _meta_classes,
    _num_meta_classes,
};

CIMPLE_NAMESPACE_END
