ROOT = $(PEGASUS_ROOT)

DIR = Pegasus/Client/tests/set_speed

include $(ROOT)/mak/config.mak

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

LIBRARIES = pegclient pegcommon

EXTRA_INCLUDES = $(SYS_INCLUDES)

PROGRAM = set_speed

SOURCES = main.cpp

include $(ROOT)/mak/program.mak

tests:

genclass:
