/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.1.2
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "All_Class.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_8FB04575347F14F28B3F4E935D6199D7;

/*[1302]*/
extern const Meta_Property
_All_Class_Key;

/*[1325]*/
const Meta_Property
_All_Class_Key =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_KEY|CIMPLE_FLAG_READ,
    "Key",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0, /* subscript */
    CIMPLE_OFF(All_Class,Key),
    0, /* value */
};

/*[1302]*/
extern const Meta_Property
_All_Class_booleanScalar;

/*[1325]*/
const Meta_Property
_All_Class_booleanScalar =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "booleanScalar",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    BOOLEAN,
    0, /* subscript */
    CIMPLE_OFF(All_Class,booleanScalar),
    0, /* value */
};

/*[1302]*/
extern const Meta_Property
_All_Class_uint8Scalar;

/*[1325]*/
const Meta_Property
_All_Class_uint8Scalar =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "uint8Scalar",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT8,
    0, /* subscript */
    CIMPLE_OFF(All_Class,uint8Scalar),
    0, /* value */
};

/*[1302]*/
extern const Meta_Property
_All_Class_sint8Scalar;

/*[1325]*/
const Meta_Property
_All_Class_sint8Scalar =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "sint8Scalar",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    SINT8,
    0, /* subscript */
    CIMPLE_OFF(All_Class,sint8Scalar),
    0, /* value */
};

/*[1302]*/
extern const Meta_Property
_All_Class_uint16Scalar;

/*[1325]*/
const Meta_Property
_All_Class_uint16Scalar =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "uint16Scalar",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT16,
    0, /* subscript */
    CIMPLE_OFF(All_Class,uint16Scalar),
    0, /* value */
};

/*[1302]*/
extern const Meta_Property
_All_Class_sint16Scalar;

/*[1325]*/
const Meta_Property
_All_Class_sint16Scalar =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "sint16Scalar",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    SINT16,
    0, /* subscript */
    CIMPLE_OFF(All_Class,sint16Scalar),
    0, /* value */
};

/*[1302]*/
extern const Meta_Property
_All_Class_uint32Scalar;

/*[1325]*/
const Meta_Property
_All_Class_uint32Scalar =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "uint32Scalar",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0, /* subscript */
    CIMPLE_OFF(All_Class,uint32Scalar),
    0, /* value */
};

/*[1302]*/
extern const Meta_Property
_All_Class_sint32Scalar;

/*[1325]*/
const Meta_Property
_All_Class_sint32Scalar =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "sint32Scalar",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    SINT32,
    0, /* subscript */
    CIMPLE_OFF(All_Class,sint32Scalar),
    0, /* value */
};

/*[1302]*/
extern const Meta_Property
_All_Class_uint64Scalar;

/*[1325]*/
const Meta_Property
_All_Class_uint64Scalar =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "uint64Scalar",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT64,
    0, /* subscript */
    CIMPLE_OFF(All_Class,uint64Scalar),
    0, /* value */
};

/*[1302]*/
extern const Meta_Property
_All_Class_sint64Scalar;

/*[1325]*/
const Meta_Property
_All_Class_sint64Scalar =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "sint64Scalar",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    SINT64,
    0, /* subscript */
    CIMPLE_OFF(All_Class,sint64Scalar),
    0, /* value */
};

/*[1302]*/
extern const Meta_Property
_All_Class_real32Scalar;

/*[1325]*/
const Meta_Property
_All_Class_real32Scalar =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "real32Scalar",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    REAL32,
    0, /* subscript */
    CIMPLE_OFF(All_Class,real32Scalar),
    0, /* value */
};

/*[1302]*/
extern const Meta_Property
_All_Class_real64Scalar;

/*[1325]*/
const Meta_Property
_All_Class_real64Scalar =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "real64Scalar",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    REAL64,
    0, /* subscript */
    CIMPLE_OFF(All_Class,real64Scalar),
    0, /* value */
};

/*[1302]*/
extern const Meta_Property
_All_Class_char16Scalar;

/*[1325]*/
const Meta_Property
_All_Class_char16Scalar =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "char16Scalar",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    CHAR16,
    0, /* subscript */
    CIMPLE_OFF(All_Class,char16Scalar),
    0, /* value */
};

/*[1302]*/
extern const Meta_Property
_All_Class_stringScalar;

/*[1325]*/
const Meta_Property
_All_Class_stringScalar =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "stringScalar",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    STRING,
    0, /* subscript */
    CIMPLE_OFF(All_Class,stringScalar),
    0, /* value */
};

/*[1302]*/
extern const Meta_Property
_All_Class_datetimeScalar;

/*[1325]*/
const Meta_Property
_All_Class_datetimeScalar =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "datetimeScalar",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    DATETIME,
    0, /* subscript */
    CIMPLE_OFF(All_Class,datetimeScalar),
    0, /* value */
};

extern const Meta_Reference
_All_Class_instanceScalar;

/*[1914]*/
const Meta_Reference _All_Class_instanceScalar =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_EMBEDDED_INSTANCE,
    "instanceScalar",
    0, /* meta_qualifiers */
    0, /* num_meta_qualifiers */
    0, /* subscript */
    &All_Part::static_meta_class,
    CIMPLE_OFF(All_Class,instanceScalar)
};

extern const Meta_Reference
_All_Class_objectScalar;

/*[1914]*/
const Meta_Reference _All_Class_objectScalar =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_EMBEDDED_OBJECT,
    "objectScalar",
    0, /* meta_qualifiers */
    0, /* num_meta_qualifiers */
    0, /* subscript */
    &Instance::static_meta_class,
    CIMPLE_OFF(All_Class,objectScalar)
};

/*[1302]*/
extern const Meta_Property
_All_Class_booleanArray;

/*[1325]*/
const Meta_Property
_All_Class_booleanArray =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "booleanArray",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    BOOLEAN,
    -1, /* subscript */
    CIMPLE_OFF(All_Class,booleanArray),
    0, /* value */
};

/*[1302]*/
extern const Meta_Property
_All_Class_uint8Array;

/*[1325]*/
const Meta_Property
_All_Class_uint8Array =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "uint8Array",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT8,
    -1, /* subscript */
    CIMPLE_OFF(All_Class,uint8Array),
    0, /* value */
};

/*[1302]*/
extern const Meta_Property
_All_Class_sint8Array;

/*[1325]*/
const Meta_Property
_All_Class_sint8Array =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "sint8Array",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    SINT8,
    -1, /* subscript */
    CIMPLE_OFF(All_Class,sint8Array),
    0, /* value */
};

/*[1302]*/
extern const Meta_Property
_All_Class_uint16Array;

/*[1325]*/
const Meta_Property
_All_Class_uint16Array =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "uint16Array",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT16,
    -1, /* subscript */
    CIMPLE_OFF(All_Class,uint16Array),
    0, /* value */
};

/*[1302]*/
extern const Meta_Property
_All_Class_sint16Array;

/*[1325]*/
const Meta_Property
_All_Class_sint16Array =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "sint16Array",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    SINT16,
    -1, /* subscript */
    CIMPLE_OFF(All_Class,sint16Array),
    0, /* value */
};

/*[1302]*/
extern const Meta_Property
_All_Class_uint32Array;

/*[1325]*/
const Meta_Property
_All_Class_uint32Array =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "uint32Array",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    -1, /* subscript */
    CIMPLE_OFF(All_Class,uint32Array),
    0, /* value */
};

/*[1302]*/
extern const Meta_Property
_All_Class_sint32Array;

/*[1325]*/
const Meta_Property
_All_Class_sint32Array =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "sint32Array",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    SINT32,
    -1, /* subscript */
    CIMPLE_OFF(All_Class,sint32Array),
    0, /* value */
};

/*[1302]*/
extern const Meta_Property
_All_Class_uint64Array;

/*[1325]*/
const Meta_Property
_All_Class_uint64Array =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "uint64Array",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT64,
    -1, /* subscript */
    CIMPLE_OFF(All_Class,uint64Array),
    0, /* value */
};

/*[1302]*/
extern const Meta_Property
_All_Class_sint64Array;

/*[1325]*/
const Meta_Property
_All_Class_sint64Array =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "sint64Array",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    SINT64,
    -1, /* subscript */
    CIMPLE_OFF(All_Class,sint64Array),
    0, /* value */
};

/*[1302]*/
extern const Meta_Property
_All_Class_real32Array;

/*[1325]*/
const Meta_Property
_All_Class_real32Array =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "real32Array",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    REAL32,
    -1, /* subscript */
    CIMPLE_OFF(All_Class,real32Array),
    0, /* value */
};

/*[1302]*/
extern const Meta_Property
_All_Class_real64Array;

/*[1325]*/
const Meta_Property
_All_Class_real64Array =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "real64Array",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    REAL64,
    -1, /* subscript */
    CIMPLE_OFF(All_Class,real64Array),
    0, /* value */
};

/*[1302]*/
extern const Meta_Property
_All_Class_char16Array;

/*[1325]*/
const Meta_Property
_All_Class_char16Array =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "char16Array",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    CHAR16,
    -1, /* subscript */
    CIMPLE_OFF(All_Class,char16Array),
    0, /* value */
};

/*[1302]*/
extern const Meta_Property
_All_Class_stringArray;

/*[1325]*/
const Meta_Property
_All_Class_stringArray =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "stringArray",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    STRING,
    -1, /* subscript */
    CIMPLE_OFF(All_Class,stringArray),
    0, /* value */
};

/*[1302]*/
extern const Meta_Property
_All_Class_datetimeArray;

/*[1325]*/
const Meta_Property
_All_Class_datetimeArray =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "datetimeArray",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    DATETIME,
    -1, /* subscript */
    CIMPLE_OFF(All_Class,datetimeArray),
    0, /* value */
};

/*[1669]*/
static const Meta_Property
_All_Class_booleanReturn_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    BOOLEAN,
    0,
    CIMPLE_OFF(All_Class_booleanReturn_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_booleanReturn_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_booleanReturn_return_value
};

/*[1847]*/
const Meta_Method
All_Class_booleanReturn_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "booleanReturn",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_booleanReturn_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_booleanReturn_MFA),
    sizeof(All_Class_booleanReturn_method),
    BOOLEAN,
};

/*[1669]*/
static const Meta_Property
_All_Class_uint8Return_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT8,
    0,
    CIMPLE_OFF(All_Class_uint8Return_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_uint8Return_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_uint8Return_return_value
};

/*[1847]*/
const Meta_Method
All_Class_uint8Return_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "uint8Return",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_uint8Return_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_uint8Return_MFA),
    sizeof(All_Class_uint8Return_method),
    UINT8,
};

/*[1669]*/
static const Meta_Property
_All_Class_sint8Return_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    SINT8,
    0,
    CIMPLE_OFF(All_Class_sint8Return_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_sint8Return_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_sint8Return_return_value
};

/*[1847]*/
const Meta_Method
All_Class_sint8Return_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "sint8Return",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_sint8Return_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_sint8Return_MFA),
    sizeof(All_Class_sint8Return_method),
    SINT8,
};

/*[1669]*/
static const Meta_Property
_All_Class_uint16Return_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT16,
    0,
    CIMPLE_OFF(All_Class_uint16Return_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_uint16Return_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_uint16Return_return_value
};

/*[1847]*/
const Meta_Method
All_Class_uint16Return_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "uint16Return",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_uint16Return_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_uint16Return_MFA),
    sizeof(All_Class_uint16Return_method),
    UINT16,
};

/*[1669]*/
static const Meta_Property
_All_Class_sint16Return_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    SINT16,
    0,
    CIMPLE_OFF(All_Class_sint16Return_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_sint16Return_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_sint16Return_return_value
};

/*[1847]*/
const Meta_Method
All_Class_sint16Return_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "sint16Return",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_sint16Return_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_sint16Return_MFA),
    sizeof(All_Class_sint16Return_method),
    SINT16,
};

/*[1669]*/
static const Meta_Property
_All_Class_uint32Return_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_uint32Return_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_uint32Return_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_uint32Return_return_value
};

/*[1847]*/
const Meta_Method
All_Class_uint32Return_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "uint32Return",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_uint32Return_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_uint32Return_MFA),
    sizeof(All_Class_uint32Return_method),
    UINT32,
};

/*[1669]*/
static const Meta_Property
_All_Class_sint32Return_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    SINT32,
    0,
    CIMPLE_OFF(All_Class_sint32Return_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_sint32Return_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_sint32Return_return_value
};

/*[1847]*/
const Meta_Method
All_Class_sint32Return_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "sint32Return",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_sint32Return_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_sint32Return_MFA),
    sizeof(All_Class_sint32Return_method),
    SINT32,
};

/*[1669]*/
static const Meta_Property
_All_Class_uint64Return_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT64,
    0,
    CIMPLE_OFF(All_Class_uint64Return_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_uint64Return_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_uint64Return_return_value
};

/*[1847]*/
const Meta_Method
All_Class_uint64Return_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "uint64Return",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_uint64Return_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_uint64Return_MFA),
    sizeof(All_Class_uint64Return_method),
    UINT64,
};

/*[1669]*/
static const Meta_Property
_All_Class_sint64Return_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    SINT64,
    0,
    CIMPLE_OFF(All_Class_sint64Return_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_sint64Return_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_sint64Return_return_value
};

/*[1847]*/
const Meta_Method
All_Class_sint64Return_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "sint64Return",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_sint64Return_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_sint64Return_MFA),
    sizeof(All_Class_sint64Return_method),
    SINT64,
};

/*[1669]*/
static const Meta_Property
_All_Class_real32Return_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    REAL32,
    0,
    CIMPLE_OFF(All_Class_real32Return_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_real32Return_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_real32Return_return_value
};

/*[1847]*/
const Meta_Method
All_Class_real32Return_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "real32Return",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_real32Return_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_real32Return_MFA),
    sizeof(All_Class_real32Return_method),
    REAL32,
};

/*[1669]*/
static const Meta_Property
_All_Class_real64Return_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    REAL64,
    0,
    CIMPLE_OFF(All_Class_real64Return_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_real64Return_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_real64Return_return_value
};

/*[1847]*/
const Meta_Method
All_Class_real64Return_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "real64Return",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_real64Return_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_real64Return_MFA),
    sizeof(All_Class_real64Return_method),
    REAL64,
};

/*[1669]*/
static const Meta_Property
_All_Class_char16Return_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    CHAR16,
    0,
    CIMPLE_OFF(All_Class_char16Return_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_char16Return_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_char16Return_return_value
};

/*[1847]*/
const Meta_Method
All_Class_char16Return_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "char16Return",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_char16Return_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_char16Return_MFA),
    sizeof(All_Class_char16Return_method),
    CHAR16,
};

/*[1669]*/
static const Meta_Property
_All_Class_stringReturn_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    STRING,
    0,
    CIMPLE_OFF(All_Class_stringReturn_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_stringReturn_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_stringReturn_return_value
};

/*[1847]*/
const Meta_Method
All_Class_stringReturn_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "stringReturn",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_stringReturn_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_stringReturn_MFA),
    sizeof(All_Class_stringReturn_method),
    STRING,
};

/*[1669]*/
static const Meta_Property
_All_Class_datetimeReturn_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    DATETIME,
    0,
    CIMPLE_OFF(All_Class_datetimeReturn_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_datetimeReturn_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_datetimeReturn_return_value
};

/*[1847]*/
const Meta_Method
All_Class_datetimeReturn_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "datetimeReturn",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_datetimeReturn_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_datetimeReturn_MFA),
    sizeof(All_Class_datetimeReturn_method),
    DATETIME,
};

/*[1729]*/
static const Meta_Reference
_All_Class_instanceReturn_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_EMBEDDED_INSTANCE|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qualifiers */
    0, /* subscript */
    &All_Part::static_meta_class,
    CIMPLE_OFF(All_Class_instanceReturn_method, return_value),
};

/*[1645]*/
static Meta_Feature* _All_Class_instanceReturn_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_instanceReturn_return_value
};

/*[1847]*/
const Meta_Method
All_Class_instanceReturn_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "instanceReturn",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_instanceReturn_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_instanceReturn_MFA),
    sizeof(All_Class_instanceReturn_method),
    STRING,
};

/*[1729]*/
static const Meta_Reference
_All_Class_objectReturn_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_OUT|CIMPLE_FLAG_EMBEDDED_OBJECT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qualifiers */
    0, /* subscript */
    &Instance::static_meta_class,
    CIMPLE_OFF(All_Class_objectReturn_method, return_value),
};

/*[1645]*/
static Meta_Feature* _All_Class_objectReturn_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_objectReturn_return_value
};

/*[1847]*/
const Meta_Method
All_Class_objectReturn_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD|CIMPLE_FLAG_EMBEDDED_OBJECT,
    "objectReturn",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_objectReturn_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_objectReturn_MFA),
    sizeof(All_Class_objectReturn_method),
    STRING,
};

/*[1516]*/
static const Meta_Property
_All_Class_booleanScalarParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    BOOLEAN,
    0,
    CIMPLE_OFF(All_Class_booleanScalarParams_method,p1),
    0, /* value */
};

/*[1516]*/
static const Meta_Property
_All_Class_booleanScalarParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    BOOLEAN,
    0,
    CIMPLE_OFF(All_Class_booleanScalarParams_method,p2),
    0, /* value */
};

/*[1669]*/
static const Meta_Property
_All_Class_booleanScalarParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_booleanScalarParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_booleanScalarParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_booleanScalarParams_p1,
    (Meta_Feature*)(void*)&_All_Class_booleanScalarParams_p2,
    (Meta_Feature*)(void*)&_All_Class_booleanScalarParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_booleanScalarParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "booleanScalarParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_booleanScalarParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_booleanScalarParams_MFA),
    sizeof(All_Class_booleanScalarParams_method),
    UINT32,
};

/*[1516]*/
static const Meta_Property
_All_Class_uint8ScalarParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT8,
    0,
    CIMPLE_OFF(All_Class_uint8ScalarParams_method,p1),
    0, /* value */
};

/*[1516]*/
static const Meta_Property
_All_Class_uint8ScalarParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT8,
    0,
    CIMPLE_OFF(All_Class_uint8ScalarParams_method,p2),
    0, /* value */
};

/*[1669]*/
static const Meta_Property
_All_Class_uint8ScalarParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_uint8ScalarParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_uint8ScalarParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_uint8ScalarParams_p1,
    (Meta_Feature*)(void*)&_All_Class_uint8ScalarParams_p2,
    (Meta_Feature*)(void*)&_All_Class_uint8ScalarParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_uint8ScalarParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "uint8ScalarParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_uint8ScalarParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_uint8ScalarParams_MFA),
    sizeof(All_Class_uint8ScalarParams_method),
    UINT32,
};

/*[1516]*/
static const Meta_Property
_All_Class_sint8ScalarParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    SINT8,
    0,
    CIMPLE_OFF(All_Class_sint8ScalarParams_method,p1),
    0, /* value */
};

/*[1516]*/
static const Meta_Property
_All_Class_sint8ScalarParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    SINT8,
    0,
    CIMPLE_OFF(All_Class_sint8ScalarParams_method,p2),
    0, /* value */
};

/*[1669]*/
static const Meta_Property
_All_Class_sint8ScalarParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_sint8ScalarParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_sint8ScalarParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_sint8ScalarParams_p1,
    (Meta_Feature*)(void*)&_All_Class_sint8ScalarParams_p2,
    (Meta_Feature*)(void*)&_All_Class_sint8ScalarParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_sint8ScalarParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "sint8ScalarParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_sint8ScalarParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_sint8ScalarParams_MFA),
    sizeof(All_Class_sint8ScalarParams_method),
    UINT32,
};

/*[1516]*/
static const Meta_Property
_All_Class_uint16ScalarParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT16,
    0,
    CIMPLE_OFF(All_Class_uint16ScalarParams_method,p1),
    0, /* value */
};

/*[1516]*/
static const Meta_Property
_All_Class_uint16ScalarParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT16,
    0,
    CIMPLE_OFF(All_Class_uint16ScalarParams_method,p2),
    0, /* value */
};

/*[1669]*/
static const Meta_Property
_All_Class_uint16ScalarParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_uint16ScalarParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_uint16ScalarParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_uint16ScalarParams_p1,
    (Meta_Feature*)(void*)&_All_Class_uint16ScalarParams_p2,
    (Meta_Feature*)(void*)&_All_Class_uint16ScalarParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_uint16ScalarParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "uint16ScalarParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_uint16ScalarParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_uint16ScalarParams_MFA),
    sizeof(All_Class_uint16ScalarParams_method),
    UINT32,
};

/*[1516]*/
static const Meta_Property
_All_Class_sint16ScalarParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    SINT16,
    0,
    CIMPLE_OFF(All_Class_sint16ScalarParams_method,p1),
    0, /* value */
};

/*[1516]*/
static const Meta_Property
_All_Class_sint16ScalarParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    SINT16,
    0,
    CIMPLE_OFF(All_Class_sint16ScalarParams_method,p2),
    0, /* value */
};

/*[1669]*/
static const Meta_Property
_All_Class_sint16ScalarParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_sint16ScalarParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_sint16ScalarParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_sint16ScalarParams_p1,
    (Meta_Feature*)(void*)&_All_Class_sint16ScalarParams_p2,
    (Meta_Feature*)(void*)&_All_Class_sint16ScalarParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_sint16ScalarParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "sint16ScalarParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_sint16ScalarParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_sint16ScalarParams_MFA),
    sizeof(All_Class_sint16ScalarParams_method),
    UINT32,
};

/*[1516]*/
static const Meta_Property
_All_Class_uint32ScalarParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_uint32ScalarParams_method,p1),
    0, /* value */
};

/*[1516]*/
static const Meta_Property
_All_Class_uint32ScalarParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_uint32ScalarParams_method,p2),
    0, /* value */
};

/*[1669]*/
static const Meta_Property
_All_Class_uint32ScalarParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_uint32ScalarParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_uint32ScalarParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_uint32ScalarParams_p1,
    (Meta_Feature*)(void*)&_All_Class_uint32ScalarParams_p2,
    (Meta_Feature*)(void*)&_All_Class_uint32ScalarParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_uint32ScalarParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "uint32ScalarParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_uint32ScalarParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_uint32ScalarParams_MFA),
    sizeof(All_Class_uint32ScalarParams_method),
    UINT32,
};

/*[1516]*/
static const Meta_Property
_All_Class_sint32ScalarParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    SINT32,
    0,
    CIMPLE_OFF(All_Class_sint32ScalarParams_method,p1),
    0, /* value */
};

/*[1516]*/
static const Meta_Property
_All_Class_sint32ScalarParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    SINT32,
    0,
    CIMPLE_OFF(All_Class_sint32ScalarParams_method,p2),
    0, /* value */
};

/*[1669]*/
static const Meta_Property
_All_Class_sint32ScalarParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_sint32ScalarParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_sint32ScalarParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_sint32ScalarParams_p1,
    (Meta_Feature*)(void*)&_All_Class_sint32ScalarParams_p2,
    (Meta_Feature*)(void*)&_All_Class_sint32ScalarParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_sint32ScalarParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "sint32ScalarParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_sint32ScalarParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_sint32ScalarParams_MFA),
    sizeof(All_Class_sint32ScalarParams_method),
    UINT32,
};

/*[1516]*/
static const Meta_Property
_All_Class_uint64ScalarParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT64,
    0,
    CIMPLE_OFF(All_Class_uint64ScalarParams_method,p1),
    0, /* value */
};

/*[1516]*/
static const Meta_Property
_All_Class_uint64ScalarParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT64,
    0,
    CIMPLE_OFF(All_Class_uint64ScalarParams_method,p2),
    0, /* value */
};

/*[1669]*/
static const Meta_Property
_All_Class_uint64ScalarParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_uint64ScalarParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_uint64ScalarParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_uint64ScalarParams_p1,
    (Meta_Feature*)(void*)&_All_Class_uint64ScalarParams_p2,
    (Meta_Feature*)(void*)&_All_Class_uint64ScalarParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_uint64ScalarParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "uint64ScalarParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_uint64ScalarParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_uint64ScalarParams_MFA),
    sizeof(All_Class_uint64ScalarParams_method),
    UINT32,
};

/*[1516]*/
static const Meta_Property
_All_Class_sint64ScalarParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    SINT64,
    0,
    CIMPLE_OFF(All_Class_sint64ScalarParams_method,p1),
    0, /* value */
};

/*[1516]*/
static const Meta_Property
_All_Class_sint64ScalarParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    SINT64,
    0,
    CIMPLE_OFF(All_Class_sint64ScalarParams_method,p2),
    0, /* value */
};

/*[1669]*/
static const Meta_Property
_All_Class_sint64ScalarParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_sint64ScalarParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_sint64ScalarParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_sint64ScalarParams_p1,
    (Meta_Feature*)(void*)&_All_Class_sint64ScalarParams_p2,
    (Meta_Feature*)(void*)&_All_Class_sint64ScalarParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_sint64ScalarParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "sint64ScalarParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_sint64ScalarParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_sint64ScalarParams_MFA),
    sizeof(All_Class_sint64ScalarParams_method),
    UINT32,
};

/*[1516]*/
static const Meta_Property
_All_Class_real32ScalarParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    REAL32,
    0,
    CIMPLE_OFF(All_Class_real32ScalarParams_method,p1),
    0, /* value */
};

/*[1516]*/
static const Meta_Property
_All_Class_real32ScalarParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    REAL32,
    0,
    CIMPLE_OFF(All_Class_real32ScalarParams_method,p2),
    0, /* value */
};

/*[1669]*/
static const Meta_Property
_All_Class_real32ScalarParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_real32ScalarParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_real32ScalarParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_real32ScalarParams_p1,
    (Meta_Feature*)(void*)&_All_Class_real32ScalarParams_p2,
    (Meta_Feature*)(void*)&_All_Class_real32ScalarParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_real32ScalarParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "real32ScalarParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_real32ScalarParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_real32ScalarParams_MFA),
    sizeof(All_Class_real32ScalarParams_method),
    UINT32,
};

/*[1516]*/
static const Meta_Property
_All_Class_real64ScalarParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    REAL64,
    0,
    CIMPLE_OFF(All_Class_real64ScalarParams_method,p1),
    0, /* value */
};

/*[1516]*/
static const Meta_Property
_All_Class_real64ScalarParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    REAL64,
    0,
    CIMPLE_OFF(All_Class_real64ScalarParams_method,p2),
    0, /* value */
};

/*[1669]*/
static const Meta_Property
_All_Class_real64ScalarParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_real64ScalarParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_real64ScalarParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_real64ScalarParams_p1,
    (Meta_Feature*)(void*)&_All_Class_real64ScalarParams_p2,
    (Meta_Feature*)(void*)&_All_Class_real64ScalarParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_real64ScalarParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "real64ScalarParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_real64ScalarParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_real64ScalarParams_MFA),
    sizeof(All_Class_real64ScalarParams_method),
    UINT32,
};

/*[1516]*/
static const Meta_Property
_All_Class_char16ScalarParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    CHAR16,
    0,
    CIMPLE_OFF(All_Class_char16ScalarParams_method,p1),
    0, /* value */
};

/*[1516]*/
static const Meta_Property
_All_Class_char16ScalarParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    CHAR16,
    0,
    CIMPLE_OFF(All_Class_char16ScalarParams_method,p2),
    0, /* value */
};

/*[1669]*/
static const Meta_Property
_All_Class_char16ScalarParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_char16ScalarParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_char16ScalarParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_char16ScalarParams_p1,
    (Meta_Feature*)(void*)&_All_Class_char16ScalarParams_p2,
    (Meta_Feature*)(void*)&_All_Class_char16ScalarParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_char16ScalarParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "char16ScalarParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_char16ScalarParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_char16ScalarParams_MFA),
    sizeof(All_Class_char16ScalarParams_method),
    UINT32,
};

/*[1516]*/
static const Meta_Property
_All_Class_stringScalarParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    STRING,
    0,
    CIMPLE_OFF(All_Class_stringScalarParams_method,p1),
    0, /* value */
};

/*[1516]*/
static const Meta_Property
_All_Class_stringScalarParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    STRING,
    0,
    CIMPLE_OFF(All_Class_stringScalarParams_method,p2),
    0, /* value */
};

/*[1669]*/
static const Meta_Property
_All_Class_stringScalarParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_stringScalarParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_stringScalarParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_stringScalarParams_p1,
    (Meta_Feature*)(void*)&_All_Class_stringScalarParams_p2,
    (Meta_Feature*)(void*)&_All_Class_stringScalarParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_stringScalarParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "stringScalarParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_stringScalarParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_stringScalarParams_MFA),
    sizeof(All_Class_stringScalarParams_method),
    UINT32,
};

/*[1516]*/
static const Meta_Property
_All_Class_datetimeScalarParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    DATETIME,
    0,
    CIMPLE_OFF(All_Class_datetimeScalarParams_method,p1),
    0, /* value */
};

/*[1516]*/
static const Meta_Property
_All_Class_datetimeScalarParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    DATETIME,
    0,
    CIMPLE_OFF(All_Class_datetimeScalarParams_method,p2),
    0, /* value */
};

/*[1669]*/
static const Meta_Property
_All_Class_datetimeScalarParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_datetimeScalarParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_datetimeScalarParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_datetimeScalarParams_p1,
    (Meta_Feature*)(void*)&_All_Class_datetimeScalarParams_p2,
    (Meta_Feature*)(void*)&_All_Class_datetimeScalarParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_datetimeScalarParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "datetimeScalarParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_datetimeScalarParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_datetimeScalarParams_MFA),
    sizeof(All_Class_datetimeScalarParams_method),
    UINT32,
};

/*[1580]*/
static const Meta_Reference
_All_Class_objectScalarParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_IN|CIMPLE_FLAG_EMBEDDED_OBJECT,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    0, /* subscript */
    &Instance::static_meta_class,
    CIMPLE_OFF(All_Class_objectScalarParams_method,p1)
};

/*[1580]*/
static const Meta_Reference
_All_Class_objectScalarParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_OUT|CIMPLE_FLAG_EMBEDDED_OBJECT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    0, /* subscript */
    &Instance::static_meta_class,
    CIMPLE_OFF(All_Class_objectScalarParams_method,p2)
};

/*[1669]*/
static const Meta_Property
_All_Class_objectScalarParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_objectScalarParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_objectScalarParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_objectScalarParams_p1,
    (Meta_Feature*)(void*)&_All_Class_objectScalarParams_p2,
    (Meta_Feature*)(void*)&_All_Class_objectScalarParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_objectScalarParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "objectScalarParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_objectScalarParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_objectScalarParams_MFA),
    sizeof(All_Class_objectScalarParams_method),
    UINT32,
};

/*[1580]*/
static const Meta_Reference
_All_Class_instanceScalarParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_EMBEDDED_INSTANCE|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    0, /* subscript */
    &All_Part::static_meta_class,
    CIMPLE_OFF(All_Class_instanceScalarParams_method,p1)
};

/*[1580]*/
static const Meta_Reference
_All_Class_instanceScalarParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_EMBEDDED_INSTANCE|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    0, /* subscript */
    &All_Part::static_meta_class,
    CIMPLE_OFF(All_Class_instanceScalarParams_method,p2)
};

/*[1669]*/
static const Meta_Property
_All_Class_instanceScalarParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_instanceScalarParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_instanceScalarParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_instanceScalarParams_p1,
    (Meta_Feature*)(void*)&_All_Class_instanceScalarParams_p2,
    (Meta_Feature*)(void*)&_All_Class_instanceScalarParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_instanceScalarParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "instanceScalarParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_instanceScalarParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_instanceScalarParams_MFA),
    sizeof(All_Class_instanceScalarParams_method),
    UINT32,
};

/*[1455]*/
static const Meta_Reference
_All_Class_referenceScalarParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    0, /* subscript */
    &All_Part::static_meta_class,
    CIMPLE_OFF(All_Class_referenceScalarParams_method,p1)
};

/*[1455]*/
static const Meta_Reference
_All_Class_referenceScalarParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    0, /* subscript */
    &All_Part::static_meta_class,
    CIMPLE_OFF(All_Class_referenceScalarParams_method,p2)
};

/*[1669]*/
static const Meta_Property
_All_Class_referenceScalarParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_referenceScalarParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_referenceScalarParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_referenceScalarParams_p1,
    (Meta_Feature*)(void*)&_All_Class_referenceScalarParams_p2,
    (Meta_Feature*)(void*)&_All_Class_referenceScalarParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_referenceScalarParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "referenceScalarParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_referenceScalarParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_referenceScalarParams_MFA),
    sizeof(All_Class_referenceScalarParams_method),
    UINT32,
};

/*[1516]*/
static const Meta_Property
_All_Class_booleanArrayParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    BOOLEAN,
    -1,
    CIMPLE_OFF(All_Class_booleanArrayParams_method,p1),
    0, /* value */
};

/*[1516]*/
static const Meta_Property
_All_Class_booleanArrayParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    BOOLEAN,
    -1,
    CIMPLE_OFF(All_Class_booleanArrayParams_method,p2),
    0, /* value */
};

/*[1669]*/
static const Meta_Property
_All_Class_booleanArrayParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_booleanArrayParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_booleanArrayParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_booleanArrayParams_p1,
    (Meta_Feature*)(void*)&_All_Class_booleanArrayParams_p2,
    (Meta_Feature*)(void*)&_All_Class_booleanArrayParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_booleanArrayParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "booleanArrayParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_booleanArrayParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_booleanArrayParams_MFA),
    sizeof(All_Class_booleanArrayParams_method),
    UINT32,
};

/*[1516]*/
static const Meta_Property
_All_Class_uint8ArrayParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT8,
    -1,
    CIMPLE_OFF(All_Class_uint8ArrayParams_method,p1),
    0, /* value */
};

/*[1516]*/
static const Meta_Property
_All_Class_uint8ArrayParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT8,
    -1,
    CIMPLE_OFF(All_Class_uint8ArrayParams_method,p2),
    0, /* value */
};

/*[1669]*/
static const Meta_Property
_All_Class_uint8ArrayParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_uint8ArrayParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_uint8ArrayParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_uint8ArrayParams_p1,
    (Meta_Feature*)(void*)&_All_Class_uint8ArrayParams_p2,
    (Meta_Feature*)(void*)&_All_Class_uint8ArrayParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_uint8ArrayParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "uint8ArrayParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_uint8ArrayParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_uint8ArrayParams_MFA),
    sizeof(All_Class_uint8ArrayParams_method),
    UINT32,
};

/*[1516]*/
static const Meta_Property
_All_Class_sint8ArrayParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    SINT8,
    -1,
    CIMPLE_OFF(All_Class_sint8ArrayParams_method,p1),
    0, /* value */
};

/*[1516]*/
static const Meta_Property
_All_Class_sint8ArrayParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    SINT8,
    -1,
    CIMPLE_OFF(All_Class_sint8ArrayParams_method,p2),
    0, /* value */
};

/*[1669]*/
static const Meta_Property
_All_Class_sint8ArrayParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_sint8ArrayParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_sint8ArrayParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_sint8ArrayParams_p1,
    (Meta_Feature*)(void*)&_All_Class_sint8ArrayParams_p2,
    (Meta_Feature*)(void*)&_All_Class_sint8ArrayParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_sint8ArrayParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "sint8ArrayParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_sint8ArrayParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_sint8ArrayParams_MFA),
    sizeof(All_Class_sint8ArrayParams_method),
    UINT32,
};

/*[1516]*/
static const Meta_Property
_All_Class_uint16ArrayParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT16,
    -1,
    CIMPLE_OFF(All_Class_uint16ArrayParams_method,p1),
    0, /* value */
};

/*[1516]*/
static const Meta_Property
_All_Class_uint16ArrayParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT16,
    -1,
    CIMPLE_OFF(All_Class_uint16ArrayParams_method,p2),
    0, /* value */
};

/*[1669]*/
static const Meta_Property
_All_Class_uint16ArrayParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_uint16ArrayParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_uint16ArrayParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_uint16ArrayParams_p1,
    (Meta_Feature*)(void*)&_All_Class_uint16ArrayParams_p2,
    (Meta_Feature*)(void*)&_All_Class_uint16ArrayParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_uint16ArrayParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "uint16ArrayParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_uint16ArrayParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_uint16ArrayParams_MFA),
    sizeof(All_Class_uint16ArrayParams_method),
    UINT32,
};

/*[1516]*/
static const Meta_Property
_All_Class_sint16ArrayParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    SINT16,
    -1,
    CIMPLE_OFF(All_Class_sint16ArrayParams_method,p1),
    0, /* value */
};

/*[1516]*/
static const Meta_Property
_All_Class_sint16ArrayParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    SINT16,
    -1,
    CIMPLE_OFF(All_Class_sint16ArrayParams_method,p2),
    0, /* value */
};

/*[1669]*/
static const Meta_Property
_All_Class_sint16ArrayParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_sint16ArrayParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_sint16ArrayParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_sint16ArrayParams_p1,
    (Meta_Feature*)(void*)&_All_Class_sint16ArrayParams_p2,
    (Meta_Feature*)(void*)&_All_Class_sint16ArrayParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_sint16ArrayParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "sint16ArrayParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_sint16ArrayParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_sint16ArrayParams_MFA),
    sizeof(All_Class_sint16ArrayParams_method),
    UINT32,
};

/*[1516]*/
static const Meta_Property
_All_Class_uint32ArrayParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    -1,
    CIMPLE_OFF(All_Class_uint32ArrayParams_method,p1),
    0, /* value */
};

/*[1516]*/
static const Meta_Property
_All_Class_uint32ArrayParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    -1,
    CIMPLE_OFF(All_Class_uint32ArrayParams_method,p2),
    0, /* value */
};

/*[1669]*/
static const Meta_Property
_All_Class_uint32ArrayParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_uint32ArrayParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_uint32ArrayParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_uint32ArrayParams_p1,
    (Meta_Feature*)(void*)&_All_Class_uint32ArrayParams_p2,
    (Meta_Feature*)(void*)&_All_Class_uint32ArrayParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_uint32ArrayParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "uint32ArrayParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_uint32ArrayParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_uint32ArrayParams_MFA),
    sizeof(All_Class_uint32ArrayParams_method),
    UINT32,
};

/*[1516]*/
static const Meta_Property
_All_Class_sint32ArrayParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    SINT32,
    -1,
    CIMPLE_OFF(All_Class_sint32ArrayParams_method,p1),
    0, /* value */
};

/*[1516]*/
static const Meta_Property
_All_Class_sint32ArrayParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    SINT32,
    -1,
    CIMPLE_OFF(All_Class_sint32ArrayParams_method,p2),
    0, /* value */
};

/*[1669]*/
static const Meta_Property
_All_Class_sint32ArrayParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_sint32ArrayParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_sint32ArrayParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_sint32ArrayParams_p1,
    (Meta_Feature*)(void*)&_All_Class_sint32ArrayParams_p2,
    (Meta_Feature*)(void*)&_All_Class_sint32ArrayParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_sint32ArrayParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "sint32ArrayParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_sint32ArrayParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_sint32ArrayParams_MFA),
    sizeof(All_Class_sint32ArrayParams_method),
    UINT32,
};

/*[1516]*/
static const Meta_Property
_All_Class_uint64ArrayParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT64,
    -1,
    CIMPLE_OFF(All_Class_uint64ArrayParams_method,p1),
    0, /* value */
};

/*[1516]*/
static const Meta_Property
_All_Class_uint64ArrayParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT64,
    -1,
    CIMPLE_OFF(All_Class_uint64ArrayParams_method,p2),
    0, /* value */
};

/*[1669]*/
static const Meta_Property
_All_Class_uint64ArrayParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_uint64ArrayParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_uint64ArrayParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_uint64ArrayParams_p1,
    (Meta_Feature*)(void*)&_All_Class_uint64ArrayParams_p2,
    (Meta_Feature*)(void*)&_All_Class_uint64ArrayParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_uint64ArrayParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "uint64ArrayParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_uint64ArrayParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_uint64ArrayParams_MFA),
    sizeof(All_Class_uint64ArrayParams_method),
    UINT32,
};

/*[1516]*/
static const Meta_Property
_All_Class_sint64ArrayParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    SINT64,
    -1,
    CIMPLE_OFF(All_Class_sint64ArrayParams_method,p1),
    0, /* value */
};

/*[1516]*/
static const Meta_Property
_All_Class_sint64ArrayParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    SINT64,
    -1,
    CIMPLE_OFF(All_Class_sint64ArrayParams_method,p2),
    0, /* value */
};

/*[1669]*/
static const Meta_Property
_All_Class_sint64ArrayParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_sint64ArrayParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_sint64ArrayParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_sint64ArrayParams_p1,
    (Meta_Feature*)(void*)&_All_Class_sint64ArrayParams_p2,
    (Meta_Feature*)(void*)&_All_Class_sint64ArrayParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_sint64ArrayParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "sint64ArrayParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_sint64ArrayParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_sint64ArrayParams_MFA),
    sizeof(All_Class_sint64ArrayParams_method),
    UINT32,
};

/*[1516]*/
static const Meta_Property
_All_Class_real32ArrayParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    REAL32,
    -1,
    CIMPLE_OFF(All_Class_real32ArrayParams_method,p1),
    0, /* value */
};

/*[1516]*/
static const Meta_Property
_All_Class_real32ArrayParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    REAL32,
    -1,
    CIMPLE_OFF(All_Class_real32ArrayParams_method,p2),
    0, /* value */
};

/*[1669]*/
static const Meta_Property
_All_Class_real32ArrayParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_real32ArrayParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_real32ArrayParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_real32ArrayParams_p1,
    (Meta_Feature*)(void*)&_All_Class_real32ArrayParams_p2,
    (Meta_Feature*)(void*)&_All_Class_real32ArrayParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_real32ArrayParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "real32ArrayParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_real32ArrayParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_real32ArrayParams_MFA),
    sizeof(All_Class_real32ArrayParams_method),
    UINT32,
};

/*[1516]*/
static const Meta_Property
_All_Class_real64ArrayParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    REAL64,
    -1,
    CIMPLE_OFF(All_Class_real64ArrayParams_method,p1),
    0, /* value */
};

/*[1516]*/
static const Meta_Property
_All_Class_real64ArrayParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    REAL64,
    -1,
    CIMPLE_OFF(All_Class_real64ArrayParams_method,p2),
    0, /* value */
};

/*[1669]*/
static const Meta_Property
_All_Class_real64ArrayParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_real64ArrayParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_real64ArrayParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_real64ArrayParams_p1,
    (Meta_Feature*)(void*)&_All_Class_real64ArrayParams_p2,
    (Meta_Feature*)(void*)&_All_Class_real64ArrayParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_real64ArrayParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "real64ArrayParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_real64ArrayParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_real64ArrayParams_MFA),
    sizeof(All_Class_real64ArrayParams_method),
    UINT32,
};

/*[1516]*/
static const Meta_Property
_All_Class_char16ArrayParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    CHAR16,
    -1,
    CIMPLE_OFF(All_Class_char16ArrayParams_method,p1),
    0, /* value */
};

/*[1516]*/
static const Meta_Property
_All_Class_char16ArrayParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    CHAR16,
    -1,
    CIMPLE_OFF(All_Class_char16ArrayParams_method,p2),
    0, /* value */
};

/*[1669]*/
static const Meta_Property
_All_Class_char16ArrayParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_char16ArrayParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_char16ArrayParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_char16ArrayParams_p1,
    (Meta_Feature*)(void*)&_All_Class_char16ArrayParams_p2,
    (Meta_Feature*)(void*)&_All_Class_char16ArrayParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_char16ArrayParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "char16ArrayParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_char16ArrayParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_char16ArrayParams_MFA),
    sizeof(All_Class_char16ArrayParams_method),
    UINT32,
};

/*[1516]*/
static const Meta_Property
_All_Class_stringArrayParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    STRING,
    -1,
    CIMPLE_OFF(All_Class_stringArrayParams_method,p1),
    0, /* value */
};

/*[1516]*/
static const Meta_Property
_All_Class_stringArrayParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    STRING,
    -1,
    CIMPLE_OFF(All_Class_stringArrayParams_method,p2),
    0, /* value */
};

/*[1669]*/
static const Meta_Property
_All_Class_stringArrayParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_stringArrayParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_stringArrayParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_stringArrayParams_p1,
    (Meta_Feature*)(void*)&_All_Class_stringArrayParams_p2,
    (Meta_Feature*)(void*)&_All_Class_stringArrayParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_stringArrayParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "stringArrayParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_stringArrayParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_stringArrayParams_MFA),
    sizeof(All_Class_stringArrayParams_method),
    UINT32,
};

/*[1516]*/
static const Meta_Property
_All_Class_datetimeArrayParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    DATETIME,
    -1,
    CIMPLE_OFF(All_Class_datetimeArrayParams_method,p1),
    0, /* value */
};

/*[1516]*/
static const Meta_Property
_All_Class_datetimeArrayParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    DATETIME,
    -1,
    CIMPLE_OFF(All_Class_datetimeArrayParams_method,p2),
    0, /* value */
};

/*[1669]*/
static const Meta_Property
_All_Class_datetimeArrayParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_datetimeArrayParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_datetimeArrayParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_datetimeArrayParams_p1,
    (Meta_Feature*)(void*)&_All_Class_datetimeArrayParams_p2,
    (Meta_Feature*)(void*)&_All_Class_datetimeArrayParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_datetimeArrayParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "datetimeArrayParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_datetimeArrayParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_datetimeArrayParams_MFA),
    sizeof(All_Class_datetimeArrayParams_method),
    UINT32,
};

/*[1580]*/
static const Meta_Reference
_All_Class_objectArrayParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_IN|CIMPLE_FLAG_EMBEDDED_OBJECT,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    -1, /* subscript */
    &Instance::static_meta_class,
    CIMPLE_OFF(All_Class_objectArrayParams_method,p1)
};

/*[1580]*/
static const Meta_Reference
_All_Class_objectArrayParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_OUT|CIMPLE_FLAG_EMBEDDED_OBJECT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    -1, /* subscript */
    &Instance::static_meta_class,
    CIMPLE_OFF(All_Class_objectArrayParams_method,p2)
};

/*[1669]*/
static const Meta_Property
_All_Class_objectArrayParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_objectArrayParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_objectArrayParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_objectArrayParams_p1,
    (Meta_Feature*)(void*)&_All_Class_objectArrayParams_p2,
    (Meta_Feature*)(void*)&_All_Class_objectArrayParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_objectArrayParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "objectArrayParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_objectArrayParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_objectArrayParams_MFA),
    sizeof(All_Class_objectArrayParams_method),
    UINT32,
};

/*[1580]*/
static const Meta_Reference
_All_Class_instanceArrayParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_EMBEDDED_INSTANCE|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    -1, /* subscript */
    &All_Part::static_meta_class,
    CIMPLE_OFF(All_Class_instanceArrayParams_method,p1)
};

/*[1580]*/
static const Meta_Reference
_All_Class_instanceArrayParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_EMBEDDED_INSTANCE|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    -1, /* subscript */
    &All_Part::static_meta_class,
    CIMPLE_OFF(All_Class_instanceArrayParams_method,p2)
};

/*[1669]*/
static const Meta_Property
_All_Class_instanceArrayParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_instanceArrayParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_instanceArrayParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_instanceArrayParams_p1,
    (Meta_Feature*)(void*)&_All_Class_instanceArrayParams_p2,
    (Meta_Feature*)(void*)&_All_Class_instanceArrayParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_instanceArrayParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "instanceArrayParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_instanceArrayParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_instanceArrayParams_MFA),
    sizeof(All_Class_instanceArrayParams_method),
    UINT32,
};

/*[1455]*/
static const Meta_Reference
_All_Class_referenceArrayParams_p1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_IN,
    "p1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    -1, /* subscript */
    &All_Part::static_meta_class,
    CIMPLE_OFF(All_Class_referenceArrayParams_method,p1)
};

/*[1455]*/
static const Meta_Reference
_All_Class_referenceArrayParams_p2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_OUT,
    "p2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    -1, /* subscript */
    &All_Part::static_meta_class,
    CIMPLE_OFF(All_Class_referenceArrayParams_method,p2)
};

/*[1669]*/
static const Meta_Property
_All_Class_referenceArrayParams_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(All_Class_referenceArrayParams_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _All_Class_referenceArrayParams_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_referenceArrayParams_p1,
    (Meta_Feature*)(void*)&_All_Class_referenceArrayParams_p2,
    (Meta_Feature*)(void*)&_All_Class_referenceArrayParams_return_value
};

/*[1847]*/
const Meta_Method
All_Class_referenceArrayParams_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "referenceArrayParams",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_referenceArrayParams_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_referenceArrayParams_MFA),
    sizeof(All_Class_referenceArrayParams_method),
    UINT32,
};

/*[2025]*/
static Meta_Feature* _All_Class_MFA[] =
{
    (Meta_Feature*)(void*)&_All_Class_Key,
    (Meta_Feature*)(void*)&_All_Class_booleanScalar,
    (Meta_Feature*)(void*)&_All_Class_uint8Scalar,
    (Meta_Feature*)(void*)&_All_Class_sint8Scalar,
    (Meta_Feature*)(void*)&_All_Class_uint16Scalar,
    (Meta_Feature*)(void*)&_All_Class_sint16Scalar,
    (Meta_Feature*)(void*)&_All_Class_uint32Scalar,
    (Meta_Feature*)(void*)&_All_Class_sint32Scalar,
    (Meta_Feature*)(void*)&_All_Class_uint64Scalar,
    (Meta_Feature*)(void*)&_All_Class_sint64Scalar,
    (Meta_Feature*)(void*)&_All_Class_real32Scalar,
    (Meta_Feature*)(void*)&_All_Class_real64Scalar,
    (Meta_Feature*)(void*)&_All_Class_char16Scalar,
    (Meta_Feature*)(void*)&_All_Class_stringScalar,
    (Meta_Feature*)(void*)&_All_Class_datetimeScalar,
    (Meta_Feature*)(void*)&_All_Class_instanceScalar,
    (Meta_Feature*)(void*)&_All_Class_objectScalar,
    (Meta_Feature*)(void*)&_All_Class_booleanArray,
    (Meta_Feature*)(void*)&_All_Class_uint8Array,
    (Meta_Feature*)(void*)&_All_Class_sint8Array,
    (Meta_Feature*)(void*)&_All_Class_uint16Array,
    (Meta_Feature*)(void*)&_All_Class_sint16Array,
    (Meta_Feature*)(void*)&_All_Class_uint32Array,
    (Meta_Feature*)(void*)&_All_Class_sint32Array,
    (Meta_Feature*)(void*)&_All_Class_uint64Array,
    (Meta_Feature*)(void*)&_All_Class_sint64Array,
    (Meta_Feature*)(void*)&_All_Class_real32Array,
    (Meta_Feature*)(void*)&_All_Class_real64Array,
    (Meta_Feature*)(void*)&_All_Class_char16Array,
    (Meta_Feature*)(void*)&_All_Class_stringArray,
    (Meta_Feature*)(void*)&_All_Class_datetimeArray,
    (Meta_Feature*)(void*)&All_Class_booleanReturn_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_uint8Return_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_sint8Return_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_uint16Return_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_sint16Return_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_uint32Return_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_sint32Return_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_uint64Return_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_sint64Return_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_real32Return_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_real64Return_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_char16Return_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_stringReturn_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_datetimeReturn_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_instanceReturn_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_objectReturn_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_booleanScalarParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_uint8ScalarParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_sint8ScalarParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_uint16ScalarParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_sint16ScalarParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_uint32ScalarParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_sint32ScalarParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_uint64ScalarParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_sint64ScalarParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_real32ScalarParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_real64ScalarParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_char16ScalarParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_stringScalarParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_datetimeScalarParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_objectScalarParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_instanceScalarParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_referenceScalarParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_booleanArrayParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_uint8ArrayParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_sint8ArrayParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_uint16ArrayParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_sint16ArrayParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_uint32ArrayParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_sint32ArrayParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_uint64ArrayParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_sint64ArrayParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_real32ArrayParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_real64ArrayParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_char16ArrayParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_stringArrayParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_datetimeArrayParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_objectArrayParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_instanceArrayParams_method::static_meta_class,
    (Meta_Feature*)(void*)&All_Class_referenceArrayParams_method::static_meta_class,
};

/*[2072]*/
static const Meta_Feature_Local _locals[] =
{
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
};

/*[2092]*/
const Meta_Class All_Class::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_CLASS,
    "All_Class",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _All_Class_MFA,
    CIMPLE_ARRAY_SIZE(_All_Class_MFA),
    sizeof(All_Class),
    _locals,
    0, /* super_class */ 
    1, /* num_keys */
    &__meta_repository_8FB04575347F14F28B3F4E935D6199D7,
};

CIMPLE_NAMESPACE_END

