/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.1.2
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "CIM_IndicationHandlerCIMXML.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_8FB04575347F14F28B3F4E935D6199D7;

/*[1302]*/
extern const Meta_Property
_CIM_ManagedElement_Caption;

/*[1302]*/
extern const Meta_Property
_CIM_ManagedElement_Description;

/*[1302]*/
extern const Meta_Property
_CIM_ManagedElement_ElementName;

/*[1302]*/
extern const Meta_Property
_CIM_ListenerDestination_SystemCreationClassName;

/*[1302]*/
extern const Meta_Property
_CIM_ListenerDestination_SystemName;

/*[1302]*/
extern const Meta_Property
_CIM_ListenerDestination_CreationClassName;

/*[1302]*/
extern const Meta_Property
_CIM_ListenerDestination_Name;

/*[1302]*/
extern const Meta_Property
_CIM_ListenerDestination_PersistenceType;

/*[1302]*/
extern const Meta_Property
_CIM_ListenerDestination_OtherPersistenceType;

/*[1302]*/
extern const Meta_Property
_CIM_IndicationHandler_Owner;

/*[1302]*/
extern const Meta_Property
_CIM_IndicationHandlerCIMXML_Destination;

/*[1325]*/
const Meta_Property
_CIM_IndicationHandlerCIMXML_Destination =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ|CIMPLE_FLAG_REQUIRED,
    "Destination",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    STRING,
    0, /* subscript */
    CIMPLE_OFF(CIM_IndicationHandlerCIMXML,Destination),
    0, /* value */
};

/*[2025]*/
static Meta_Feature* _CIM_IndicationHandlerCIMXML_MFA[] =
{
    (Meta_Feature*)(void*)&_CIM_ManagedElement_Caption,
    (Meta_Feature*)(void*)&_CIM_ManagedElement_Description,
    (Meta_Feature*)(void*)&_CIM_ManagedElement_ElementName,
    (Meta_Feature*)(void*)&_CIM_ListenerDestination_SystemCreationClassName,
    (Meta_Feature*)(void*)&_CIM_ListenerDestination_SystemName,
    (Meta_Feature*)(void*)&_CIM_ListenerDestination_CreationClassName,
    (Meta_Feature*)(void*)&_CIM_ListenerDestination_Name,
    (Meta_Feature*)(void*)&_CIM_ListenerDestination_PersistenceType,
    (Meta_Feature*)(void*)&_CIM_ListenerDestination_OtherPersistenceType,
    (Meta_Feature*)(void*)&_CIM_IndicationHandler_Owner,
    (Meta_Feature*)(void*)&_CIM_IndicationHandlerCIMXML_Destination,
};

/*[2072]*/
static const Meta_Feature_Local _locals[] =
{
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {1},
};

/*[2092]*/
const Meta_Class CIM_IndicationHandlerCIMXML::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_CLASS,
    "CIM_IndicationHandlerCIMXML",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _CIM_IndicationHandlerCIMXML_MFA,
    CIMPLE_ARRAY_SIZE(_CIM_IndicationHandlerCIMXML_MFA),
    sizeof(CIM_IndicationHandlerCIMXML),
    _locals,
    &CIM_IndicationHandler::static_meta_class,
    4, /* num_keys */
    &__meta_repository_8FB04575347F14F28B3F4E935D6199D7,
};

CIMPLE_NAMESPACE_END

