//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.1.2
//
//==============================================================================

#include <cimple/cimple.h>
#include "repository.h"

CIMPLE_NAMESPACE_BEGIN

/*[2528]*/
static const Meta_Class* _meta_classes[] =
{
    &Employee::static_meta_class,
    &Manager::static_meta_class,
    &Link::static_meta_class,
    &OutOfOfficeNotice::static_meta_class,
    &All_Part::static_meta_class,
    &All_Class::static_meta_class,
    &CIM_ManagedElement::static_meta_class,
    &CIM_IndicationFilter::static_meta_class,
    &CIM_ListenerDestination::static_meta_class,
    &CIM_IndicationSubscription::static_meta_class,
    &CIM_IndicationHandler::static_meta_class,
    &CIM_IndicationHandlerCIMXML::static_meta_class,
    &CIM_ManagedSystemElement::static_meta_class,
    &CIM_LogicalElement::static_meta_class,
    &CIM_Job::static_meta_class,
    &CIM_ConcreteJob::static_meta_class,
    &CIM_EnabledLogicalElement::static_meta_class,
    &CIM_System::static_meta_class,
    &CIM_ComputerSystem::static_meta_class,
};

static const size_t _num_meta_classes = CIMPLE_ARRAY_SIZE(_meta_classes);

extern const Meta_Repository __meta_repository_8FB04575347F14F28B3F4E935D6199D7;

/*[2555]*/
const Meta_Repository __meta_repository_8FB04575347F14F28B3F4E935D6199D7 =
{
    _meta_classes,
    _num_meta_classes,
};

CIMPLE_NAMESPACE_END
