TOP = ../../..
include $(TOP)/mak/config.mak

STATIC_LIBRARY = cimplepegutils

SOURCES = \
    print.cpp \
    Containers.cpp

LIBRARIES = \
    pegcommon

include $(TOP)/mak/pegasus.mak
include $(TOP)/mak/rules.mak
include ../check-pegasus.mak
