TOP = ../../../..
include $(TOP)/mak/config.mak

BINARY = test_facade
SOURCES = Base.cpp Thing.cpp Assoc.cpp main.cpp
LIBRARIES = -lcimpledisp -lcimple

include $(TOP)/mak/rules.mak

genclass:

tests:
	$(TARGET)
