/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#ifndef _cimple_CIM_CommonDatabase_h
#define _cimple_CIM_CommonDatabase_h

#include <cimple/cimple.h>
#include "CIM_EnabledLogicalElement.h"

#if (0x00633800 > CIMPLE_VERSION)
# error "The version of genclass used to generate this file (0.99.56) is newer than the version of <cimple/cimple.h> found on the include path. Please place the matching version of <cimple/cimple.h> on the include path."
#endif

#if (0x00633800 < CIMPLE_VERSION)
# error "The version of genclass used to generate this file (0.99.56) is older than the version of <cimple/cimple.h> found on the include path. Please regenerate the sources with the matching version of genclass."
#endif


CIMPLE_NAMESPACE_BEGIN

class CIM_CommonDatabase : public Instance
{
public:
    // CIM_ManagedElement features:
    Property<String> Caption;
    Property<String> Description;
    Property<String> ElementName;

    // CIM_ManagedSystemElement features:
    Property<Datetime> InstallDate;
    Property<String> Name;
    Property<Array_uint16> OperationalStatus;
    Property<Array_String> StatusDescriptions;
    Property<String> Status;
    Property<uint16> HealthState;

    // CIM_LogicalElement features:

    // CIM_EnabledLogicalElement features:
    Property<uint16> EnabledState;
    Property<String> OtherEnabledState;
    Property<uint16> RequestedState;
    Property<uint16> EnabledDefault;
    Property<Datetime> TimeOfLastStateChange;

    // CIM_CommonDatabase features:
    Property<String> InstanceID; // KEY
    Property<String> DatabaseVersion;
    Property<Datetime> LastBackup;
    Property<uint32> SizeAllocated;
    Property<uint16> SizeUnits;

    CIMPLE_CLASS(CIM_CommonDatabase)
};

typedef CIM_EnabledLogicalElement_RequestStateChange_method CIM_CommonDatabase_RequestStateChange_method;

CIMPLE_NAMESPACE_END

#endif /* _cimple_CIM_CommonDatabase_h */
