/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.1.2
//
//==============================================================================

#ifndef _cimple_CIM_CommonDatabase_h
#define _cimple_CIM_CommonDatabase_h

#include <cimple/cimple.h>
#include "CIM_EnabledLogicalElement.h"

CIMPLE_NAMESPACE_BEGIN

// CIM_CommonDatabase keys:
//     InstanceID

/*[928]*/
class CIM_CommonDatabase : public Instance
{
public:
    // CIM_ManagedElement features:
    Property<String> Caption;
    Property<String> Description;
    Property<String> ElementName;

    // CIM_ManagedSystemElement features:
    Property<Datetime> InstallDate;
    Property<String> Name;
    Property<Array_uint16> OperationalStatus;
    Property<Array_String> StatusDescriptions;
    Property<String> Status;
    Property<uint16> HealthState;

    // CIM_LogicalElement features:

    // CIM_EnabledLogicalElement features:
    Property<uint16> EnabledState;
    Property<String> OtherEnabledState;
    Property<uint16> RequestedState;
    Property<uint16> EnabledDefault;
    Property<Datetime> TimeOfLastStateChange;

    // CIM_CommonDatabase features:
    Property<String> InstanceID;
    Property<String> DatabaseVersion;
    Property<Datetime> LastBackup;
    Property<uint32> SizeAllocated;
    Property<uint16> SizeUnits;

    CIMPLE_CLASS(CIM_CommonDatabase)
};

typedef CIM_EnabledLogicalElement_RequestStateChange_method CIM_CommonDatabase_RequestStateChange_method;

CIMPLE_NAMESPACE_END

#endif /* _cimple_CIM_CommonDatabase_h */
