//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "CIM_CommonDatabase.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern CIMPLE_HIDE const Meta_Property _CIM_ManagedElement_Caption;

extern CIMPLE_HIDE const Meta_Property _CIM_ManagedElement_Description;

extern CIMPLE_HIDE const Meta_Property _CIM_ManagedElement_ElementName;

extern CIMPLE_HIDE const Meta_Property _CIM_ManagedSystemElement_InstallDate;

extern CIMPLE_HIDE const Meta_Property _CIM_ManagedSystemElement_Name;

extern CIMPLE_HIDE const Meta_Property _CIM_ManagedSystemElement_OperationalStatus;

extern CIMPLE_HIDE const Meta_Property _CIM_ManagedSystemElement_StatusDescriptions;

extern CIMPLE_HIDE const Meta_Property _CIM_ManagedSystemElement_Status;

extern CIMPLE_HIDE const Meta_Property _CIM_EnabledLogicalElement_EnabledState;

extern CIMPLE_HIDE const Meta_Property _CIM_EnabledLogicalElement_OtherEnabledState;

extern CIMPLE_HIDE const Meta_Property _CIM_EnabledLogicalElement_RequestedState;

extern CIMPLE_HIDE const Meta_Property _CIM_EnabledLogicalElement_EnabledDefault;

extern CIMPLE_HIDE const Meta_Property _CIM_EnabledLogicalElement_TimeOfLastStateChange;

extern CIMPLE_HIDE const Meta_Property _CIM_CommonDatabase_InstanceID;

const Meta_Property _CIM_CommonDatabase_InstanceID =
{
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_KEY,
    "InstanceID",
    STRING,
    0,
    CIMPLE_OFF(CIM_CommonDatabase,InstanceID)
};

extern CIMPLE_HIDE const Meta_Property _CIM_CommonDatabase_DatabaseVersion;

const Meta_Property _CIM_CommonDatabase_DatabaseVersion =
{
    CIMPLE_FLAG_PROPERTY,
    "DatabaseVersion",
    STRING,
    0,
    CIMPLE_OFF(CIM_CommonDatabase,DatabaseVersion)
};

extern CIMPLE_HIDE const Meta_Property _CIM_CommonDatabase_LastBackup;

const Meta_Property _CIM_CommonDatabase_LastBackup =
{
    CIMPLE_FLAG_PROPERTY,
    "LastBackup",
    DATETIME,
    0,
    CIMPLE_OFF(CIM_CommonDatabase,LastBackup)
};

extern CIMPLE_HIDE const Meta_Property _CIM_CommonDatabase_SizeAllocated;

const Meta_Property _CIM_CommonDatabase_SizeAllocated =
{
    CIMPLE_FLAG_PROPERTY,
    "SizeAllocated",
    UINT32,
    0,
    CIMPLE_OFF(CIM_CommonDatabase,SizeAllocated)
};

extern CIMPLE_HIDE const Meta_Property _CIM_CommonDatabase_SizeUnits;

const Meta_Property _CIM_CommonDatabase_SizeUnits =
{
    CIMPLE_FLAG_PROPERTY,
    "SizeUnits",
    UINT16,
    0,
    CIMPLE_OFF(CIM_CommonDatabase,SizeUnits)
};

static Meta_Feature* _CIM_CommonDatabase_meta_features[] =
{
    (Meta_Feature*)&_CIM_ManagedElement_Caption,
    (Meta_Feature*)&_CIM_ManagedElement_Description,
    (Meta_Feature*)&_CIM_ManagedElement_ElementName,
    (Meta_Feature*)&_CIM_ManagedSystemElement_InstallDate,
    (Meta_Feature*)&_CIM_ManagedSystemElement_Name,
    (Meta_Feature*)&_CIM_ManagedSystemElement_OperationalStatus,
    (Meta_Feature*)&_CIM_ManagedSystemElement_StatusDescriptions,
    (Meta_Feature*)&_CIM_ManagedSystemElement_Status,
    (Meta_Feature*)&_CIM_EnabledLogicalElement_EnabledState,
    (Meta_Feature*)&_CIM_EnabledLogicalElement_OtherEnabledState,
    (Meta_Feature*)&_CIM_EnabledLogicalElement_RequestedState,
    (Meta_Feature*)&_CIM_EnabledLogicalElement_EnabledDefault,
    (Meta_Feature*)&_CIM_EnabledLogicalElement_TimeOfLastStateChange,
    (Meta_Feature*)&CIM_EnabledLogicalElement_RequestStateChange_method::static_meta_class,
    (Meta_Feature*)&_CIM_CommonDatabase_InstanceID,
    (Meta_Feature*)&_CIM_CommonDatabase_DatabaseVersion,
    (Meta_Feature*)&_CIM_CommonDatabase_LastBackup,
    (Meta_Feature*)&_CIM_CommonDatabase_SizeAllocated,
    (Meta_Feature*)&_CIM_CommonDatabase_SizeUnits,
};

const Meta_Class CIM_CommonDatabase::static_meta_class =
{
    CIMPLE_FLAG_CLASS,
    "CIM_CommonDatabase",
    _CIM_CommonDatabase_meta_features,
    CIMPLE_ARRAY_SIZE(_CIM_CommonDatabase_meta_features),
    sizeof(CIM_CommonDatabase),
    &CIM_EnabledLogicalElement::static_meta_class,
    1,
    0x8A85F4E2,
    0,
};

CIMPLE_NAMESPACE_END

