//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#ifndef _repository_h
#define _repository_h

#include <cimple/cimple.h>
#include "CIM_ManagedElement.h"
#include "CIM_ManagedSystemElement.h"
#include "CIM_LogicalElement.h"
#include "CIM_Job.h"
#include "CIM_ConcreteJob.h"
#include "CIM_EnabledLogicalElement.h"
#include "CIM_System.h"
#include "CIM_ComputerSystem.h"

CIMPLE_NAMESPACE_BEGIN

CIMPLE_NAMESPACE_END

#endif /* _repository_h */
