# Include just before the rules.mak
INCLUDES += -I$(WITH_PEGASUS_INCLUDES_OPT) -I$(TOP)/src/pegasus/include

DEFINES += -DPEGASUS_PLATFORM_$(PLATFORM)

ifeq ($(PLATFORM),LINUX_S390_GNU)
    DEFINES += -DPEGASUS_PLATFORM_LINUX_ZSERIES_GNU
endif

ifeq ($(PLATFORM),LINUX_S390X_GNU)
    DEFINES += -DPEGASUS_PLATFORM_LINUX_ZSERIES64_GNU
endif
