TOP = ../../../..
include $(TOP)/mak/config.mak

BINARY = test_dzt_string
SOURCES = main.cpp
LIBRARIES = -lcimpledisp -lcimple

include $(TOP)/mak/rules.mak

tests:
	@ $(BIN)/test_dzt_string

genclass:
