TOP = ../../../..
include $(TOP)/mak/config.mak

BINARY = test_dzt_string
SOURCES = main.cpp
LIBRARIES = cimpledisp cimple

include $(TOP)/mak/rules.mak

tests:
	@ $(BIN_DIR)/test_dzt_string

genclass:
