//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.1
//
//==============================================================================

#include <cimple/cimple.h>
#include "repository.h"

CIMPLE_NAMESPACE_BEGIN

/*[2547]*/
static const Meta_Class* _meta_classes[] =
{
    &Thing::static_meta_class,
    &ThingLink::static_meta_class,
};

static const size_t _num_meta_classes = CIMPLE_ARRAY_SIZE(_meta_classes);

extern const Meta_Repository __meta_repository_46CE1E6F52CD1E6593D6461243D92844;

/*[2574]*/
const Meta_Repository __meta_repository_46CE1E6F52CD1E6593D6461243D92844 =
{
    _meta_classes,
    _num_meta_classes,
};

CIMPLE_NAMESPACE_END
