/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.0.22
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "ThingLink.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_19AD18AE91F41191AC602DE73514CB3C;

/*[1387]*/
extern const Meta_Reference
_ThingLink_left;

/*[1398]*/
const Meta_Reference
_ThingLink_left =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_KEY,
    "left",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    0, /* subscript */
    &Thing::static_meta_class,
    CIMPLE_OFF(ThingLink,left)
};

/*[1387]*/
extern const Meta_Reference
_ThingLink_right;

/*[1398]*/
const Meta_Reference
_ThingLink_right =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_KEY,
    "right",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    0, /* subscript */
    &Thing::static_meta_class,
    CIMPLE_OFF(ThingLink,right)
};

/*[2025]*/
static Meta_Feature* _ThingLink_MFA[] =
{
    (Meta_Feature*)(void*)&_ThingLink_left,
    (Meta_Feature*)(void*)&_ThingLink_right,
};

/*[2072]*/
static const Meta_Feature_Local _locals[] =
{
    {1},
    {1},
};

/*[2092]*/
const Meta_Class ThingLink::static_meta_class =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_ASSOCIATION,
    "ThingLink",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _ThingLink_MFA,
    CIMPLE_ARRAY_SIZE(_ThingLink_MFA),
    sizeof(ThingLink),
    _locals,
    0, /* super_class */ 
    2, /* num_keys */
    &__meta_repository_19AD18AE91F41191AC602DE73514CB3C,
};

CIMPLE_NAMESPACE_END

