/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.0.3
//
//==============================================================================

#ifndef _cimple_Arg_h
#define _cimple_Arg_h

#include <cimple/cimple.h>

CIMPLE_NAMESPACE_BEGIN

// Arg keys:
//     key

class Arg : public Instance
{
public:
    // Arg features:
    Property<uint32> key;

    CIMPLE_CLASS(Arg)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_Arg_h */
