class Argument
{
    [key] uint32 key;
};

class Methods
{
    [key] uint32 key;

    string foo(
	[in] uint32 arg1, 
	[in] string arg2, 
	[in] boolean arg3,
	[in(false), out] uint32 arg4, 
	[in(false), out] string arg5, 
	[in(false), out] boolean arg6);

    string foo2(
	[in] Argument ref arg1, 
	[in(false), out] Argument ref arg2);

    [Static] string foo3();

    uint32 foo4(
        [in] string arr1[],
        [in(false), out] string arr2[]);

    uint32 foo5(
        [in(true), out(false)] uint32 in_arg,
        [in(true), out(true)] uint32 in_out_arg,
        [in(false), out(true)] uint32 out_arg);

    uint32 junk(uint32 x, uint32 y);
};

class Methods2 : Methods
{
    uint32 junk(uint32 x, uint32 y);
};
