/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "OutOfOfficeNotice.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_FCF0725B97671F55BDA3CAE31C40B60A;

extern const Meta_Reference
_OutOfOfficeNotice_employee;

const Meta_Reference _OutOfOfficeNotice_employee =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_EMBEDDED_OBJECT,
    "employee",
    0, /* meta_qualifiers */
    0, /* num_meta_qualifiers */
    0, /* subscript */
    &Instance::static_meta_class,
    CIMPLE_OFF(OutOfOfficeNotice,employee)
};

static Meta_Feature* _OutOfOfficeNotice_MFA[] =
{
    (Meta_Feature*)(void*)&_OutOfOfficeNotice_employee,
};

static const Meta_Feature_Local _locals[] =
{
    {1},
};

const Meta_Class OutOfOfficeNotice::static_meta_class =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_INDICATION,
    "OutOfOfficeNotice",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _OutOfOfficeNotice_MFA,
    CIMPLE_ARRAY_SIZE(_OutOfOfficeNotice_MFA),
    sizeof(OutOfOfficeNotice),
    _locals,
    0, /* super_class */ 
    0, /* num_keys */
    0x645CEB3A, /* crc */
    &__meta_repository_FCF0725B97671F55BDA3CAE31C40B60A,
};

CIMPLE_NAMESPACE_END

CIMPLE_ID("$Header: /home/cvs/cimple/src/providers/Employee/OutOfOfficeNotice.cpp,v 1.3 2007/04/24 20:51:57 mbrasher-public Exp $");
