/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#ifndef _cimple_CIM_RegisteredProfile_h
#define _cimple_CIM_RegisteredProfile_h

#include <cimple/cimple.h>
#include "CIM_ManagedElement.h"

#if (0x00632900 > CIMPLE_VERSION)
# error "The version of genclass used to generate this file (0.99.41) is newer than the version of <cimple/cimple.h> found on the include path. Please place the matching version of <cimple/cimple.h> on the include path."
#endif

#if (0x00632900 < CIMPLE_VERSION)
# error "The version of genclass used to generate this file (0.99.41) is older than the version of <cimple/cimple.h> found on the include path. Please regenerate the sources with the matching version of genclass."
#endif


CIMPLE_NAMESPACE_BEGIN

class CIM_RegisteredProfile : public Instance
{
public:
    // CIM_ManagedElement features:
    Property<String> Caption;
    Property<String> Description;
    Property<String> ElementName;

    // CIM_RegisteredProfile features:
    Property<String> InstanceID;
    Property<uint16> RegisteredOrganization;
    Property<String> OtherRegisteredOrganization;
    Property<String> RegisteredName;
    Property<String> RegisteredVersion;
    Property<Array_uint16> AdvertiseTypes;
    Property<Array_String> AdvertiseTypeDescriptions;

    CIMPLE_CLASS(CIM_RegisteredProfile)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_CIM_RegisteredProfile_h */
