/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "Upcall3.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_2B5D31521FC118CB9D77B202292D3562;

extern const Meta_Reference
_Upcall3_ConformantStandard;

const Meta_Reference
_Upcall3_ConformantStandard =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_KEY,
    "ConformantStandard",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    &Upcall3Part::static_meta_class,
    CIMPLE_OFF(Upcall3,ConformantStandard)
};

extern const Meta_Reference
_Upcall3_ManagedElement;

const Meta_Reference
_Upcall3_ManagedElement =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_KEY,
    "ManagedElement",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    &CIM_ComputerSystem::static_meta_class,
    CIMPLE_OFF(Upcall3,ManagedElement)
};

static Meta_Feature* _Upcall3_MFA[] =
{
    (Meta_Feature*)&_Upcall3_ConformantStandard,
    (Meta_Feature*)&_Upcall3_ManagedElement,
};

static const Meta_Feature_Local _locals[] =
{
    {1},
    {1},
};

const Meta_Class Upcall3::static_meta_class =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_ASSOCIATION,
    "Upcall3",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _Upcall3_MFA,
    CIMPLE_ARRAY_SIZE(_Upcall3_MFA),
    sizeof(Upcall3),
    _locals,
    &CIM_ElementConformsToProfile::static_meta_class,
    2, /* num_keys */
    0x82A2B29F, /* crc */
    &__meta_repository_2B5D31521FC118CB9D77B202292D3562,
};

CIMPLE_NAMESPACE_END

CIMPLE_ID("$Header: /home/cvs/cimple/src/providers/Upcall3/Upcall3.cpp,v 1.3 2007/03/07 20:25:29 mbrasher-public Exp $");
