/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.0.11
//
//==============================================================================

#ifndef _cimple_C_h
#define _cimple_C_h

#include <cimple/cimple.h>

CIMPLE_NAMESPACE_BEGIN

// C keys:
//     key

class C : public Instance
{
public:
    // C features:
    Property<uint32> key;

    CIMPLE_CLASS(C)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_C_h */
