/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.1.2
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "X.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_DA54B7B339111E7981DE1ECA2A4CE679;

extern const Meta_Reference
_X_a;

/*[1914]*/
const Meta_Reference _X_a =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_EMBEDDED_INSTANCE,
    "a",
    0, /* meta_qualifiers */
    0, /* num_meta_qualifiers */
    0, /* subscript */
    &A::static_meta_class,
    CIMPLE_OFF(X,a)
};

/*[1729]*/
static const Meta_Reference
_X_foo1_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_EMBEDDED_INSTANCE|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qualifiers */
    0, /* subscript */
    &B::static_meta_class,
    CIMPLE_OFF(X_foo1_method, return_value),
};

/*[1645]*/
static Meta_Feature* _X_foo1_MFA[] =
{
    (Meta_Feature*)(void*)&_X_foo1_return_value
};

/*[1847]*/
const Meta_Method
X_foo1_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "foo1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _X_foo1_MFA,
    CIMPLE_ARRAY_SIZE(_X_foo1_MFA),
    sizeof(X_foo1_method),
    STRING,
};

/*[1580]*/
static const Meta_Reference
_X_foo2_c =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_EMBEDDED_INSTANCE|CIMPLE_FLAG_IN|CIMPLE_FLAG_OUT,
    "c",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    0, /* subscript */
    &C::static_meta_class,
    CIMPLE_OFF(X_foo2_method,c)
};

/*[1669]*/
static const Meta_Property
_X_foo2_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    STRING,
    0,
    CIMPLE_OFF(X_foo2_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _X_foo2_MFA[] =
{
    (Meta_Feature*)(void*)&_X_foo2_c,
    (Meta_Feature*)(void*)&_X_foo2_return_value
};

/*[1847]*/
const Meta_Method
X_foo2_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "foo2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _X_foo2_MFA,
    CIMPLE_ARRAY_SIZE(_X_foo2_MFA),
    sizeof(X_foo2_method),
    STRING,
};

/*[2025]*/
static Meta_Feature* _X_MFA[] =
{
    (Meta_Feature*)(void*)&_X_a,
    (Meta_Feature*)(void*)&X_foo1_method::static_meta_class,
    (Meta_Feature*)(void*)&X_foo2_method::static_meta_class,
};

/*[2072]*/
static const Meta_Feature_Local _locals[] =
{
    {1},
    {1},
    {1},
};

/*[2092]*/
const Meta_Class X::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_CLASS,
    "X",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _X_MFA,
    CIMPLE_ARRAY_SIZE(_X_MFA),
    sizeof(X),
    _locals,
    0, /* super_class */ 
    0, /* num_keys */
    &__meta_repository_DA54B7B339111E7981DE1ECA2A4CE679,
};

CIMPLE_NAMESPACE_END

