/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#ifndef _cimple_BB_h
#define _cimple_BB_h

#include <cimple/cimple.h>
#include "AA.h"
#include "B.h"
#include "B.h"

CIMPLE_NAMESPACE_BEGIN

class BB : public Instance
{
public:
    // AA features:
    B* left;
    B* right;

    // BB features:

    CIMPLE_CLASS(BB)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_BB_h */
