/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.1.0
//
//==============================================================================

#ifndef _cimple_Employee_h
#define _cimple_Employee_h

#include <cimple/cimple.h>

CIMPLE_NAMESPACE_BEGIN

// Employee keys:
//     Id

/*[1195]*/
class Employee : public Instance
{
public:
    // Employee features:
    Property<uint32> Id;
    Property<String> First;
    Property<String> Last;
    Property<uint32> Gender;
    Property<boolean> Active;

    CIMPLE_CLASS(Employee)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_Employee_h */
