class Employee
{
    [Key] uint32 Id;
    string First;
    string Last;
    [Values{"Male", "Female"}, ValueMap{"1", "2"}]
    uint32 Gender;
    boolean Active = true;
};

class Manager : Employee
{
    uint32 NumEmployees;
    uint32 Budget;
};

[Association]
class Link
{
    [Key] Manager REF Mgr;
    [Key] Employee REF Emp;
};

class A
{
    [Key] uint32 w;
};

class B : A
{
    boolean x;
    string y;
};

class C : B
{
    datetime z;
};

[Association]
class AA
{
    [Key] A ref left;
    [Key] A ref right;
};

[Association]
class BB : AA
{
    [Key] B ref left;
    [Key] B ref right;
};

[Indication]
class OutOfOfficeNotice
{
    [EmbeddedObject]
    string employee;
};

// Define each property type and corresponding array except
// embedded.
class Everything
{
    boolean a;
    uint8 b;
    uint16 c;
    uint32 d;
    uint64 e;
    real32 f;
    real64 g;
    char16 h;
    string i;
    datetime j;
    string k;
    uint32 l;
    boolean m;

    boolean aa[];
    uint8 bb[];
    uint16 cc[];
    uint32 dd[];
    uint64 ee[];
    real32 ff[];
    real64 gg[];
    char16 hh[];
    string ii[];
    datetime jj[];
    string kk[];
    uint32 ll[];
    boolean mm[];
};

// Define each property type and corresponding array except
// embedded but with default values defined for each
class EverythingDefaults
{
    boolean a = false;
    uint8 b = 8;
    uint16 c = 32;
    uint32 d = 9999;
    uint64 e = 99999;
    real32 f = 2936.88;
    real64 g;
    char16 h;
    string i = "hello";
    datetime j = "00000001020304.000005:000";
    string k = "";
    uint32 l = 0;
    boolean m = true;

    boolean aa[] = {true, false, true};

    sint8 bs[] = {0, 60, 127};
    uint8 bb[] = {0, 128, 255};

    sint16 cs[] = {0, 1000, 32000};
    uint16 cc[] = {0, 1000, 65535};

    // Issue: the max should be 4294967295 but we have compile error
    // on 32 bit linux systems with large uint32 and uint64 integers
    // translated through the compiler

    sint32 ds[] = {0, 8192, 2147483647};
    uint32 dd[] = {0, 8192, 4294967295};

    sint64 es[] = {0, 9999999, 9223372036854775807 };
    // Issue.  the max should be 18446744073709551615 but when we
    // use this, we get back 9223372036854775807
    uint64 ee[] = {0, 9999999, 18446744073709551615 };
    real32 ff[] = {1.5, 1.5};
    real64 gg[] = {1.5, 1.5};
    char16 hh[] = {'A', 'a'};   
    // NOTE: Use of 4 backslashes to achieve a pair in the .cpp file.
    string ii[] = {"",
		 "abcdefghijklmnopqurstuvwxyz0123456789", 
                 "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
                 "!\"#$%\'()*+`-,/:;<=>?@[\\\\]^_{|}~" };
                    
    datetime jj[] = {"00000001020304.000005:000", "00000001020304.000005:000"};
    string kk[];
    uint32 ll[];
    boolean mm[];
};
