//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#include <cimple/cimple.h>
#include "repository.h"

CIMPLE_NAMESPACE_BEGIN

static const Meta_Class* _meta_classes[] =
{
    &Arg::static_meta_class,
    &Methods::static_meta_class,
};

static const size_t _num_meta_classes = CIMPLE_ARRAY_SIZE(_meta_classes);

extern const Meta_Repository __meta_repository_2219D4AD98751D4BBC63498EB8736572;

const Meta_Repository __meta_repository_2219D4AD98751D4BBC63498EB8736572 =
{
    _meta_classes,
    _num_meta_classes,
};

CIMPLE_NAMESPACE_END
