// Generated by genprov 1.0.7
#include "DualNamespace2_Provider.h"

CIMPLE_NAMESPACE_BEGIN

DualNamespace2_Provider::DualNamespace2_Provider()
{
}

DualNamespace2_Provider::~DualNamespace2_Provider()
{
}

Load_Status DualNamespace2_Provider::load()
{
    return LOAD_OK;
}

Unload_Status DualNamespace2_Provider::unload()
{
    return UNLOAD_OK;
}

Get_Instance_Status DualNamespace2_Provider::get_instance(
    const DualNamespace2* model,
    DualNamespace2*& instance)
{
    return GET_INSTANCE_UNSUPPORTED;
}

Enum_Instances_Status DualNamespace2_Provider::enum_instances(
    const DualNamespace2* model,
    Enum_Instances_Handler<DualNamespace2>* handler)
{
    return ENUM_INSTANCES_OK;
}

Create_Instance_Status DualNamespace2_Provider::create_instance(
    DualNamespace2* instance)
{
    return CREATE_INSTANCE_UNSUPPORTED;
}

Delete_Instance_Status DualNamespace2_Provider::delete_instance(
    const DualNamespace2* instance)
{
    return DELETE_INSTANCE_UNSUPPORTED;
}

Modify_Instance_Status DualNamespace2_Provider::modify_instance(
    const DualNamespace2* model,
    const DualNamespace2* instance)
{
    return MODIFY_INSTANCE_UNSUPPORTED;
}

/*@END@*/

CIMPLE_NAMESPACE_END
