// Generated by genprov 1.0.7
#ifndef _DualNamespace2_Provider_h
#define _DualNamespace2_Provider_h

#include <cimple/cimple.h>
#include "DualNamespace2.h"

CIMPLE_NAMESPACE_BEGIN

class DualNamespace2_Provider
{
public:

    typedef DualNamespace2 Class;

    DualNamespace2_Provider();

    ~DualNamespace2_Provider();

    Load_Status load();

    Unload_Status unload();

    Get_Instance_Status get_instance(
        const DualNamespace2* model,
        DualNamespace2*& instance);

    Enum_Instances_Status enum_instances(
        const DualNamespace2* model,
        Enum_Instances_Handler<DualNamespace2>* handler);

    Create_Instance_Status create_instance(
        DualNamespace2* instance);

    Delete_Instance_Status delete_instance(
        const DualNamespace2* instance);

    Modify_Instance_Status modify_instance(
        const DualNamespace2* model,
        const DualNamespace2* instance);

    /*@END@*/
};

CIMPLE_NAMESPACE_END

#endif /* _DualNamespace2_Provider_h */
