/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.0.7
//
//==============================================================================

#ifndef _cimple_DualNamespace1_h
#define _cimple_DualNamespace1_h

#include <cimple/cimple.h>

CIMPLE_NAMESPACE_BEGIN

// DualNamespace1 keys:
//     Key

class DualNamespace1 : public Instance
{
public:
    // DualNamespace1 features:
    Property<uint32> Key;

    CIMPLE_CLASS(DualNamespace1)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_DualNamespace1_h */
