TOP = ../../../..
include $(TOP)/mak/config.mak

BINARY = TestEmbedded

SOURCES = main.cpp

LIBRARIES = cimple cimplepegutils pegclient pegcommon

include $(TOP)/mak/pegasus.mak
include $(TOP)/mak/rules.mak

live:
	$(TARGET)
