//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "CIM_Component.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_B91863F7A56D16BB82F3EE00F1B6B434;

extern const Meta_Reference _CIM_Component_GroupComponent;

const Meta_Reference _CIM_Component_GroupComponent =
{
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_KEY,
    "GroupComponent",
    &CIM_ManagedElement::static_meta_class,
    CIMPLE_OFF(CIM_Component,GroupComponent)
};

extern const Meta_Reference _CIM_Component_PartComponent;

const Meta_Reference _CIM_Component_PartComponent =
{
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_KEY,
    "PartComponent",
    &CIM_ManagedElement::static_meta_class,
    CIMPLE_OFF(CIM_Component,PartComponent)
};

static Meta_Feature* _CIM_Component_meta_features[] =
{
    (Meta_Feature*)&_CIM_Component_GroupComponent,
    (Meta_Feature*)&_CIM_Component_PartComponent,
};

static const Meta_Feature_Local _locals[] =
{
    {1},
    {1},
};

const Meta_Class CIM_Component::static_meta_class =
{
    CIMPLE_FLAG_ASSOCIATION,
    "CIM_Component",
    _CIM_Component_meta_features,
    CIMPLE_ARRAY_SIZE(_CIM_Component_meta_features),
    sizeof(CIM_Component),
    _locals,
    0, /* super_class */ 
    0, /* super_classes */
    0, /* num_super_classes */
    2, /* num_keys */
    0xD1D41B62,/* crc */
    &__meta_repository_B91863F7A56D16BB82F3EE00F1B6B434,
};

CIMPLE_NAMESPACE_END

