//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "CIM_ComputerSystem.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_48D39CF2E1A81164BA57916E443B1258;

extern const Meta_Property _CIM_ManagedElement_Caption;

extern const Meta_Property _CIM_ManagedElement_Description;

extern const Meta_Property _CIM_ManagedElement_ElementName;

extern const Meta_Property _CIM_ManagedSystemElement_InstallDate;

extern const Meta_Property _CIM_System_Name;

extern const Meta_Property _CIM_ManagedSystemElement_OperationalStatus;

extern const Meta_Property _CIM_ManagedSystemElement_StatusDescriptions;

extern const Meta_Property _CIM_ManagedSystemElement_Status;

extern const Meta_Property _CIM_EnabledLogicalElement_EnabledState;

extern const Meta_Property _CIM_EnabledLogicalElement_OtherEnabledState;

extern const Meta_Property _CIM_EnabledLogicalElement_RequestedState;

extern const Meta_Property _CIM_EnabledLogicalElement_EnabledDefault;

extern const Meta_Property _CIM_EnabledLogicalElement_TimeOfLastStateChange;

extern const Meta_Property _CIM_System_CreationClassName;

extern const Meta_Property _CIM_ComputerSystem_NameFormat;

const Meta_Property _CIM_ComputerSystem_NameFormat =
{
    CIMPLE_FLAG_PROPERTY,
    "NameFormat",
    STRING,
    0,
    CIMPLE_OFF(CIM_ComputerSystem,NameFormat)
};

extern const Meta_Property _CIM_System_PrimaryOwnerName;

extern const Meta_Property _CIM_System_PrimaryOwnerContact;

extern const Meta_Property _CIM_System_Roles;

extern const Meta_Property _CIM_ComputerSystem_OtherIdentifyingInfo;

const Meta_Property _CIM_ComputerSystem_OtherIdentifyingInfo =
{
    CIMPLE_FLAG_PROPERTY,
    "OtherIdentifyingInfo",
    STRING,
    -1,
    CIMPLE_OFF(CIM_ComputerSystem,OtherIdentifyingInfo)
};

extern const Meta_Property _CIM_ComputerSystem_IdentifyingDescriptions;

const Meta_Property _CIM_ComputerSystem_IdentifyingDescriptions =
{
    CIMPLE_FLAG_PROPERTY,
    "IdentifyingDescriptions",
    STRING,
    -1,
    CIMPLE_OFF(CIM_ComputerSystem,IdentifyingDescriptions)
};

extern const Meta_Property _CIM_ComputerSystem_Dedicated;

const Meta_Property _CIM_ComputerSystem_Dedicated =
{
    CIMPLE_FLAG_PROPERTY,
    "Dedicated",
    UINT16,
    -1,
    CIMPLE_OFF(CIM_ComputerSystem,Dedicated)
};

extern const Meta_Property _CIM_ComputerSystem_OtherDedicatedDescriptions;

const Meta_Property _CIM_ComputerSystem_OtherDedicatedDescriptions =
{
    CIMPLE_FLAG_PROPERTY,
    "OtherDedicatedDescriptions",
    STRING,
    -1,
    CIMPLE_OFF(CIM_ComputerSystem,OtherDedicatedDescriptions)
};

extern const Meta_Property _CIM_ComputerSystem_ResetCapability;

const Meta_Property _CIM_ComputerSystem_ResetCapability =
{
    CIMPLE_FLAG_PROPERTY,
    "ResetCapability",
    UINT16,
    0,
    CIMPLE_OFF(CIM_ComputerSystem,ResetCapability)
};

extern const Meta_Property _CIM_ComputerSystem_PowerManagementCapabilities;

const Meta_Property _CIM_ComputerSystem_PowerManagementCapabilities =
{
    CIMPLE_FLAG_PROPERTY,
    "PowerManagementCapabilities",
    UINT16,
    -1,
    CIMPLE_OFF(CIM_ComputerSystem,PowerManagementCapabilities)
};

static const Meta_Property _CIM_ComputerSystem_SetPowerState_PowerState =
{
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "PowerState",
    UINT32,
    0,
    CIMPLE_OFF(CIM_ComputerSystem_SetPowerState_method,PowerState)
};

static const Meta_Property _CIM_ComputerSystem_SetPowerState_Time =
{
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "Time",
    DATETIME,
    0,
    CIMPLE_OFF(CIM_ComputerSystem_SetPowerState_method,Time)
};

static const Meta_Property _CIM_ComputerSystem_SetPowerState_return_value =
{
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    UINT32,
    0,
    CIMPLE_OFF(CIM_ComputerSystem_SetPowerState_method,return_value)
};

static Meta_Feature* _CIM_ComputerSystem_SetPowerState_meta_features[] =
{
    (Meta_Feature*)&_CIM_ComputerSystem_SetPowerState_PowerState,
    (Meta_Feature*)&_CIM_ComputerSystem_SetPowerState_Time,
    (Meta_Feature*)&_CIM_ComputerSystem_SetPowerState_return_value
};

const Meta_Method CIM_ComputerSystem_SetPowerState_method::static_meta_class =
{
    CIMPLE_FLAG_METHOD,
    "SetPowerState",
    _CIM_ComputerSystem_SetPowerState_meta_features,
    CIMPLE_ARRAY_SIZE(_CIM_ComputerSystem_SetPowerState_meta_features),
    sizeof(CIM_ComputerSystem_SetPowerState_method),
    UINT32,
};

static Meta_Feature* _CIM_ComputerSystem_meta_features[] =
{
    (Meta_Feature*)&_CIM_ManagedElement_Caption,
    (Meta_Feature*)&_CIM_ManagedElement_Description,
    (Meta_Feature*)&_CIM_ManagedElement_ElementName,
    (Meta_Feature*)&_CIM_ManagedSystemElement_InstallDate,
    (Meta_Feature*)&_CIM_System_Name,
    (Meta_Feature*)&_CIM_ManagedSystemElement_OperationalStatus,
    (Meta_Feature*)&_CIM_ManagedSystemElement_StatusDescriptions,
    (Meta_Feature*)&_CIM_ManagedSystemElement_Status,
    (Meta_Feature*)&_CIM_EnabledLogicalElement_EnabledState,
    (Meta_Feature*)&_CIM_EnabledLogicalElement_OtherEnabledState,
    (Meta_Feature*)&_CIM_EnabledLogicalElement_RequestedState,
    (Meta_Feature*)&_CIM_EnabledLogicalElement_EnabledDefault,
    (Meta_Feature*)&_CIM_EnabledLogicalElement_TimeOfLastStateChange,
    (Meta_Feature*)&CIM_EnabledLogicalElement_RequestStateChange_method::static_meta_class,
    (Meta_Feature*)&_CIM_System_CreationClassName,
    (Meta_Feature*)&_CIM_ComputerSystem_NameFormat,
    (Meta_Feature*)&_CIM_System_PrimaryOwnerName,
    (Meta_Feature*)&_CIM_System_PrimaryOwnerContact,
    (Meta_Feature*)&_CIM_System_Roles,
    (Meta_Feature*)&_CIM_ComputerSystem_OtherIdentifyingInfo,
    (Meta_Feature*)&_CIM_ComputerSystem_IdentifyingDescriptions,
    (Meta_Feature*)&_CIM_ComputerSystem_Dedicated,
    (Meta_Feature*)&_CIM_ComputerSystem_OtherDedicatedDescriptions,
    (Meta_Feature*)&_CIM_ComputerSystem_ResetCapability,
    (Meta_Feature*)&_CIM_ComputerSystem_PowerManagementCapabilities,
    (Meta_Feature*)&CIM_ComputerSystem_SetPowerState_method::static_meta_class,
};

static const char* _super_classes[] =
{
    "CIM_System",
    "CIM_EnabledLogicalElement",
    "CIM_LogicalElement",
    "CIM_ManagedSystemElement",
    "CIM_ManagedElement",
};

static const Meta_Feature_Local _locals[] =
{
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {1},
    {0},
    {0},
    {0},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
};

const Meta_Class CIM_ComputerSystem::static_meta_class =
{
    CIMPLE_FLAG_CLASS,
    "CIM_ComputerSystem",
    _CIM_ComputerSystem_meta_features,
    CIMPLE_ARRAY_SIZE(_CIM_ComputerSystem_meta_features),
    sizeof(CIM_ComputerSystem),
    _locals,
    &CIM_System::static_meta_class,
    _super_classes,
    CIMPLE_ARRAY_SIZE(_super_classes),
    2, /* num_keys */
    0x18F2C8F2,/* crc */
    &__meta_repository_48D39CF2E1A81164BA57916E443B1258,
};

CIMPLE_NAMESPACE_END

