//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "ComputerSystemDiskDrive.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern CIMPLE_HIDE const Meta_Reference _ComputerSystemDiskDrive_GroupComponent;

const Meta_Reference _ComputerSystemDiskDrive_GroupComponent =
{
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_KEY,
    "GroupComponent",
    &ComputerSystem::static_meta_class,
    CIMPLE_OFF(ComputerSystemDiskDrive,GroupComponent)
};

extern CIMPLE_HIDE const Meta_Reference _ComputerSystemDiskDrive_PartComponent;

const Meta_Reference _ComputerSystemDiskDrive_PartComponent =
{
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_KEY,
    "PartComponent",
    &DiskDrive::static_meta_class,
    CIMPLE_OFF(ComputerSystemDiskDrive,PartComponent)
};

static Meta_Feature* _ComputerSystemDiskDrive_meta_features[] =
{
    (Meta_Feature*)&_ComputerSystemDiskDrive_GroupComponent,
    (Meta_Feature*)&_ComputerSystemDiskDrive_PartComponent,
};

const Meta_Class ComputerSystemDiskDrive::static_meta_class =
{
    CIMPLE_FLAG_ASSOCIATION,
    "ComputerSystemDiskDrive",
    _ComputerSystemDiskDrive_meta_features,
    CIMPLE_ARRAY_SIZE(_ComputerSystemDiskDrive_meta_features),
    sizeof(ComputerSystemDiskDrive),
    &CIM_SystemDevice::static_meta_class,
    2,
    0x51E0A9ED,
};

CIMPLE_NAMESPACE_END

