/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "House.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_F4A795C4F3BC1F5C8B8959AFA40EE849;

extern const Meta_Property
_House_key;

const Meta_Property
_House_key =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_KEY|CIMPLE_FLAG_READ,
    "key",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    STRING,
    0, /* subscript */
    CIMPLE_OFF(House,key),
    0, /* value */
};

static Meta_Feature* _House_MFA[] =
{
    (Meta_Feature*)&_House_key,
};

static const Meta_Feature_Local _locals[] =
{
    {1},
};

const Meta_Class House::static_meta_class =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_CLASS,
    "House",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _House_MFA,
    CIMPLE_ARRAY_SIZE(_House_MFA),
    sizeof(House),
    _locals,
    0, /* super_class */ 
    1, /* num_keys */
    0x1E1F23CB, /* crc */
    &__meta_repository_F4A795C4F3BC1F5C8B8959AFA40EE849,
};

CIMPLE_NAMESPACE_END

