/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#ifndef _cimple_House_h
#define _cimple_House_h

#include <cimple/cimple.h>

CIMPLE_NAMESPACE_BEGIN

class CIMPLE_LINKAGE House : public Instance
{
public:
    // House features:
    Property<String> key;

    CIMPLE_CLASS(House)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_House_h */
