//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#ifndef _cimple_LampLink_h
#define _cimple_LampLink_h

#include <cimple/cimple.h>
#include "Lamp.h"
#include "Lamp.h"

CIMPLE_NAMESPACE_BEGIN

class CIMPLE_LINKAGE LampLink : public Instance
{
public:
    // LampLink features:
    CIMPLE_REF(Lamp,left);
    CIMPLE_REF(Lamp,right);

    CIMPLE_CLASS(LampLink)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_LampLink_h */
