//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "Link.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_E277BAB546AC1F9B84FD3C4B6BE00B1C;

extern const Meta_Reference _Link_parent;

const Meta_Reference _Link_parent =
{
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_KEY,
    "parent",
    &Person::static_meta_class,
    CIMPLE_OFF(Link,parent)
};

extern const Meta_Reference _Link_child;

const Meta_Reference _Link_child =
{
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_KEY,
    "child",
    &Person::static_meta_class,
    CIMPLE_OFF(Link,child)
};

static Meta_Feature* _Link_meta_features[] =
{
    (Meta_Feature*)&_Link_parent,
    (Meta_Feature*)&_Link_child,
};

const Meta_Class Link::static_meta_class =
{
    CIMPLE_FLAG_ASSOCIATION,
    "Link",
    _Link_meta_features,
    CIMPLE_ARRAY_SIZE(_Link_meta_features),
    sizeof(Link),
    0,
    2,
    0x9B686A76,
    &__meta_repository_E277BAB546AC1F9B84FD3C4B6BE00B1C,
};

CIMPLE_NAMESPACE_END

