/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#ifndef _cimple_Methods_h
#define _cimple_Methods_h

#include <cimple/cimple.h>
#include "Arg.h"
#include "Arg.h"

#if (0x00633800 > CIMPLE_VERSION)
# error "The version of genclass used to generate this file (0.99.56) is newer than the version of <cimple/cimple.h> found on the include path. Please place the matching version of <cimple/cimple.h> on the include path."
#endif

#if (0x00633800 < CIMPLE_VERSION)
# error "The version of genclass used to generate this file (0.99.56) is older than the version of <cimple/cimple.h> found on the include path. Please regenerate the sources with the matching version of genclass."
#endif


CIMPLE_NAMESPACE_BEGIN

class CIMPLE_LINKAGE Methods : public Instance
{
public:
    // Methods features:
    Property<uint32> key; // KEY

    CIMPLE_CLASS(Methods)
};

class CIMPLE_LINKAGE Methods_foo_method : public Instance
{
public:
    Property<uint32> arg1;
    Property<String> arg2;
    Property<boolean> arg3;
    Property<uint32> arg4;
    Property<String> arg5;
    Property<boolean> arg6;
    Property<String> return_value;
    CIMPLE_METHOD(Methods_foo_method)
};

class CIMPLE_LINKAGE Methods_foo2_method : public Instance
{
public:
    Arg* arg1;
    Arg* arg2;
    Property<String> return_value;
    CIMPLE_METHOD(Methods_foo2_method)
};

class CIMPLE_LINKAGE Methods_foo3_method : public Instance
{
public:
    Property<String> return_value;
    CIMPLE_METHOD(Methods_foo3_method)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_Methods_h */
