/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "Person.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_F4A795C4F3BC1F5C8B8959AFA40EE849;

extern const Meta_Property
_Person_ssn;

const Meta_Property
_Person_ssn =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_KEY|CIMPLE_FLAG_READ,
    "ssn",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0, /* subscript */
    CIMPLE_OFF(Person,ssn),
    0, /* value */
};

extern const Meta_Property
_Person_first;

const Meta_Property
_Person_first =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "first",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    STRING,
    0, /* subscript */
    CIMPLE_OFF(Person,first),
    0, /* value */
};

extern const Meta_Property
_Person_last;

const Meta_Property
_Person_last =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "last",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    STRING,
    0, /* subscript */
    CIMPLE_OFF(Person,last),
    0, /* value */
};

static Meta_Feature* _Person_MFA[] =
{
    (Meta_Feature*)&_Person_ssn,
    (Meta_Feature*)&_Person_first,
    (Meta_Feature*)&_Person_last,
};

static const Meta_Feature_Local _locals[] =
{
    {1},
    {1},
    {1},
};

const Meta_Class Person::static_meta_class =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_CLASS,
    "Person",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _Person_MFA,
    CIMPLE_ARRAY_SIZE(_Person_MFA),
    sizeof(Person),
    _locals,
    0, /* super_class */ 
    1, /* num_keys */
    0xFD25E1F3, /* crc */
    &__meta_repository_F4A795C4F3BC1F5C8B8959AFA40EE849,
};

CIMPLE_NAMESPACE_END

