
class Person
{
    [key] uint32 ssn;
    string first;
    string last;
};


[association]
class Link
{
    [key] Person ref parent;
    [key] Person ref child;
};

class Salesman : Person
{
    uint32 budget;
};
