//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#include <cimple/cimple.h>
#include "repository.h"

CIMPLE_NAMESPACE_BEGIN

static const Meta_Class* _meta_classes[] =
{
    &Fan::static_meta_class,
    &CIM_Indication::static_meta_class,
    &MyIndication::static_meta_class,
    &DerivedIndication::static_meta_class,
    &House::static_meta_class,
    &Example::static_meta_class,
    &CIM_ManagedElement::static_meta_class,
    &CIM_ManagedSystemElement::static_meta_class,
    &CIM_LogicalElement::static_meta_class,
    &CIM_Job::static_meta_class,
    &CIM_ConcreteJob::static_meta_class,
    &CIM_EnabledLogicalElement::static_meta_class,
    &CIM_System::static_meta_class,
    &CIM_ComputerSystem::static_meta_class,
    &LinuxComputerSystem::static_meta_class,
    &Person::static_meta_class,
    &Link::static_meta_class,
    &Arg::static_meta_class,
    &Methods::static_meta_class,
    &UnixUser::static_meta_class,
    &MyEmbeddedClass::static_meta_class,
    &CIM_LogicalDevice::static_meta_class,
    &CIM_MediaAccessDevice::static_meta_class,
    &CIM_DiskDrive::static_meta_class,
    &DiskDrive::static_meta_class,
    &ComputerSystem::static_meta_class,
    &CIM_Component::static_meta_class,
    &CIM_SystemComponent::static_meta_class,
    &CIM_SystemDevice::static_meta_class,
    &ComputerSystemDiskDrive::static_meta_class,
    &Thing::static_meta_class,
    &ThingLink::static_meta_class,
};

static const size_t _num_meta_classes = CIMPLE_ARRAY_SIZE(_meta_classes);

CIMPLE_ENTRY_POINT void cimple_repository(
    const Meta_Class* const*& meta_classes,
    size_t& num_meta_classes)
{
   meta_classes = _meta_classes; 
   num_meta_classes = _num_meta_classes; 
}

CIMPLE_NAMESPACE_END
