#pragma include ("Fan.mof")
#pragma include ("DerivedIndication.mof")
#pragma include ("Example.mof")
#pragma include ("LinuxComputerSystem.mof")
#pragma include ("Methods.mof")
#pragma include ("Person.mof")
#pragma include ("UnixUser.mof")
#pragma include ("MyEmbeddedClass.mof")
#pragma include ("ComputerSystemDiskDrive.mof")
#pragma include ("Thing.mof")
#pragma include ("Person2.mof")
#pragma include ("User.mof")
#pragma include ("Lamp.mof")
