/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "Salesman.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_21EDCD70A42E172A9DC460386EA6D93B;

extern const Meta_Property
_Person_ssn;

extern const Meta_Property
_Person_first;

extern const Meta_Property
_Person_last;

extern const Meta_Property
_Salesman_budget;

const Meta_Property
_Salesman_budget =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "budget",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0, /* subscript */
    CIMPLE_OFF(Salesman,budget),
    0, /* value */
};

static Meta_Feature* _Salesman_MFA[] =
{
    (Meta_Feature*)&_Person_ssn,
    (Meta_Feature*)&_Person_first,
    (Meta_Feature*)&_Person_last,
    (Meta_Feature*)&_Salesman_budget,
};

static const Meta_Feature_Local _locals[] =
{
    {0},
    {0},
    {0},
    {1},
};

const Meta_Class Salesman::static_meta_class =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_CLASS,
    "Salesman",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _Salesman_MFA,
    CIMPLE_ARRAY_SIZE(_Salesman_MFA),
    sizeof(Salesman),
    _locals,
    &Person::static_meta_class,
    1, /* num_keys */
    0x7EA2FB5C, /* crc */
    &__meta_repository_21EDCD70A42E172A9DC460386EA6D93B,
};

CIMPLE_NAMESPACE_END

CIMPLE_ID("$Header: /home/cvs/cimple/src/providers/repository/Salesman.cpp,v 1.48 2007/03/13 22:53:19 mbrasher-public Exp $");
