//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "Thing.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern CIMPLE_HIDE const Meta_Property _Thing_key;

const Meta_Property _Thing_key =
{
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_KEY,
    "key",
    UINT32,
    0,
    CIMPLE_OFF(Thing,key)
};

static Meta_Feature* _Thing_meta_features[] =
{
    (Meta_Feature*)&_Thing_key,
};

const Meta_Class Thing::static_meta_class =
{
    CIMPLE_FLAG_CLASS,
    "Thing",
    _Thing_meta_features,
    CIMPLE_ARRAY_SIZE(_Thing_meta_features),
    sizeof(Thing),
    0,
    1,
    0x60EE9C0C,
};

CIMPLE_NAMESPACE_END

