/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#ifndef _cimple_ThingLink_h
#define _cimple_ThingLink_h

#include <cimple/cimple.h>
#include "Thing.h"
#include "Thing.h"

#if (0x00633800 > CIMPLE_VERSION)
# error "The version of genclass used to generate this file (0.99.56) is newer than the version of <cimple/cimple.h> found on the include path. Please place the matching version of <cimple/cimple.h> on the include path."
#endif

#if (0x00633800 < CIMPLE_VERSION)
# error "The version of genclass used to generate this file (0.99.56) is older than the version of <cimple/cimple.h> found on the include path. Please regenerate the sources with the matching version of genclass."
#endif


CIMPLE_NAMESPACE_BEGIN

class CIMPLE_LINKAGE ThingLink : public Instance
{
public:
    // ThingLink features:
    Thing* left;
    Thing* right;

    CIMPLE_CLASS(ThingLink)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_ThingLink_h */
