ROOT = $(PEGASUS_ROOT)
DIR = Pegasus/Client/tests/get_instance
include $(ROOT)/mak/config.mak
LIBRARIES = pegclient pegcommon

EXTRA_INCLUDES = $(SYS_INCLUDES)

PROGRAM = get_instance

SOURCES = main.cpp

include $(ROOT)/mak/program.mak

tests:
