/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.1.2
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "RefArray.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_397F5277BF1B1A71BBCFC1D3455DBA20;

/*[1302]*/
extern const Meta_Property
_RefArray_key;

/*[1325]*/
const Meta_Property
_RefArray_key =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_KEY|CIMPLE_FLAG_READ,
    "key",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0, /* subscript */
    CIMPLE_OFF(RefArray,key),
    0, /* value */
};

/*[1455]*/
static const Meta_Reference
_RefArray_SendRefArray_arr1 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_IN,
    "arr1",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    -1, /* subscript */
    &RefArrayParam::static_meta_class,
    CIMPLE_OFF(RefArray_SendRefArray_method,arr1)
};

/*[1455]*/
static const Meta_Reference
_RefArray_SendRefArray_arr2 =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_OUT,
    "arr2",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    -1, /* subscript */
    &RefArrayParam::static_meta_class,
    CIMPLE_OFF(RefArray_SendRefArray_method,arr2)
};

/*[1669]*/
static const Meta_Property
_RefArray_SendRefArray_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(RefArray_SendRefArray_method,return_value),
    0, /* value */
};

/*[1645]*/
static Meta_Feature* _RefArray_SendRefArray_MFA[] =
{
    (Meta_Feature*)(void*)&_RefArray_SendRefArray_arr1,
    (Meta_Feature*)(void*)&_RefArray_SendRefArray_arr2,
    (Meta_Feature*)(void*)&_RefArray_SendRefArray_return_value
};

/*[1847]*/
const Meta_Method
RefArray_SendRefArray_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "SendRefArray",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _RefArray_SendRefArray_MFA,
    CIMPLE_ARRAY_SIZE(_RefArray_SendRefArray_MFA),
    sizeof(RefArray_SendRefArray_method),
    UINT32,
};

/*[2025]*/
static Meta_Feature* _RefArray_MFA[] =
{
    (Meta_Feature*)(void*)&_RefArray_key,
    (Meta_Feature*)(void*)&RefArray_SendRefArray_method::static_meta_class,
};

/*[2072]*/
static const Meta_Feature_Local _locals[] =
{
    {1},
    {1},
};

/*[2092]*/
const Meta_Class RefArray::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_CLASS,
    "RefArray",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _RefArray_MFA,
    CIMPLE_ARRAY_SIZE(_RefArray_MFA),
    sizeof(RefArray),
    _locals,
    0, /* super_class */ 
    1, /* num_keys */
    &__meta_repository_397F5277BF1B1A71BBCFC1D3455DBA20,
};

CIMPLE_NAMESPACE_END

