/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.0.3
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "RefArrayParam.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_30E568CB337A17A5A1919ACD26FE1897;

extern const Meta_Property
_RefArrayParam_key;

const Meta_Property
_RefArrayParam_key =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_KEY|CIMPLE_FLAG_READ,
    "key",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0, /* subscript */
    CIMPLE_OFF(RefArrayParam,key),
    0, /* value */
};

static Meta_Feature* _RefArrayParam_MFA[] =
{
    (Meta_Feature*)(void*)&_RefArrayParam_key,
};

static const Meta_Feature_Local _locals[] =
{
    {1},
};

const Meta_Class RefArrayParam::static_meta_class =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_CLASS,
    "RefArrayParam",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _RefArrayParam_MFA,
    CIMPLE_ARRAY_SIZE(_RefArrayParam_MFA),
    sizeof(RefArrayParam),
    _locals,
    0, /* super_class */ 
    1, /* num_keys */
    &__meta_repository_30E568CB337A17A5A1919ACD26FE1897,
};

CIMPLE_NAMESPACE_END

CIMPLE_ID("$Header: /home/cvs/cimple/src/providers/RefArray/RefArrayParam.cpp,v 1.12 2007/06/19 15:25:01 mbrasher-public Exp $");
