//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.1.2
//
//==============================================================================

#include <cimple/cimple.h>
#include "repository.h"

CIMPLE_NAMESPACE_BEGIN

/*[2528]*/
static const Meta_Class* _meta_classes[] =
{
    &RefArrayParam::static_meta_class,
    &RefArray::static_meta_class,
};

static const size_t _num_meta_classes = CIMPLE_ARRAY_SIZE(_meta_classes);

extern const Meta_Repository __meta_repository_397F5277BF1B1A71BBCFC1D3455DBA20;

/*[2555]*/
const Meta_Repository __meta_repository_397F5277BF1B1A71BBCFC1D3455DBA20 =
{
    _meta_classes,
    _num_meta_classes,
};

CIMPLE_NAMESPACE_END
