// Copyright I 2005 DMTF.  All rights reserved.
// <change cr="SMWGCR00068" type ="new">Added class.</change>
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_PhysicalAssetCapabilities
// ==================================================================
   [Experimental, UMLPackagePath ( "CIM::Physical::Misc" ),
       Version ( "2.12.0" ), Description (
       "PhysicalAssetCapabilities describes the capabilities of "
       "representing the FRU related information of the associated "
       "instance of the CIM_PhysicalElement subclass.")]
class CIM_PhysicalAssetCapabilities : CIM_Capabilities {

      [Description (
          "Boolean indicating whether the PartNumber, Serial Number, "
          "Model, Manufacturer, and SKU properties of PhysicalElement "
          "are non-null, non-blank values, and the availability of the "
          "complete FRU information."), 
       ModelCorrespondence { "CIM_PhysicalElement.PartNumber",
          "CIM_PhysicalElement.SerialNumber",
          "CIM_PhysicalElement.Model",
          "CIM_PhysicalElement.Manufacturer",
       "CIM_PhysicalElement.SKU" }]
   boolean FRUInfoSupported;

};

