ROOT = $(PEGASUS_ROOT)
DIR = Pegasus/Client/tests/main
include $(ROOT)/mak/config.mak
LIBRARIES = pegclient pegcommon

EXTRA_INCLUDES = $(SYS_INCLUDES)

PROGRAM = im_Model

SOURCES = main.cpp

include $(ROOT)/mak/program.mak

tests:
