Instance of __Win32Provider as $P
{
    Name = "GadgetProvider";   
    ClsId = "{31777099-4d40-1bab-8c3b-ecc9128b55c8}";
};

instance of __InstanceProviderRegistration
{
    Provider = $P;
    SupportsPut = TRUE;
    SupportsGet = TRUE;
    SupportsDelete = TRUE;
    SupportsEnumeration = TRUE;
    QuerySupportLevels = { "WQL:UnarySelect" };
};

instance of __MethodProviderRegistration
{
    Provider = $P;
};

instance of __EventProviderRegistration
{
    Provider = $P;
    EventQueryList =
    {
        "SELECT * FROM Buzzer"
    };
};
