/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.2.5
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "Upcall.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_1D5858A9C3AF1CDE82C2389F433E4440;

/*[1304]*/
extern const Meta_Property
_Upcall_key;

/*[1327]*/
const Meta_Property
_Upcall_key =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_KEY|CIMPLE_FLAG_READ,
    "key",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0, /* subscript */
    CIMPLE_OFF(Upcall,key),
    0, /* value */
};

/*[1671]*/
static const Meta_Property
_Upcall_upcalls_return_value =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(Upcall_upcalls_method,return_value),
    0, /* value */
};

/*[1647]*/
static Meta_Feature* _Upcall_upcalls_MFA[] =
{
    (Meta_Feature*)(void*)&_Upcall_upcalls_return_value
};

/*[1849]*/
const Meta_Method
Upcall_upcalls_method::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_METHOD,
    "upcalls",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _Upcall_upcalls_MFA,
    CIMPLE_ARRAY_SIZE(_Upcall_upcalls_MFA),
    sizeof(Upcall_upcalls_method),
    UINT32,
};

/*[2027]*/
static Meta_Feature* _Upcall_MFA[] =
{
    (Meta_Feature*)(void*)&_Upcall_key,
    (Meta_Feature*)(void*)&Upcall_upcalls_method::static_meta_class,
};

/*[2074]*/
static const Meta_Feature_Local _locals[] =
{
    {1},
    {1},
};

/*[2094]*/
const Meta_Class Upcall::static_meta_class =
{
    CIMPLE_ATOMIC_INITIALIZER, /* refs */
    CIMPLE_FLAG_CLASS,
    "Upcall",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _Upcall_MFA,
    CIMPLE_ARRAY_SIZE(_Upcall_MFA),
    sizeof(Upcall),
    _locals,
    0, /* super_class */ 
    1, /* num_keys */
    &__meta_repository_1D5858A9C3AF1CDE82C2389F433E4440,
};

CIMPLE_NAMESPACE_END

