// The following qualifiers are required for wmi providers
// 
// Added for Windows. Reqired to register providers
Qualifier Dynamic : boolean = false, 

    Scope(class, association, indication);

// Added for Windows.
Qualifier PropertyContext : string = Null, 

    Scope(property);

// Added for Windows.
Qualifier Implemented : boolean = false, 

    Scope(method);

[indication]
class __ExtrinsicEvent
{
};
