/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.0.3
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "MyIndication.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_0123968F036E16988B8DE82DE4E1291A;

extern const Meta_Property
_CIM_Indication_IndicationIdentifier;

extern const Meta_Property
_CIM_Indication_CorrelatedIndications;

extern const Meta_Property
_CIM_Indication_IndicationTime;

extern const Meta_Property
_CIM_Indication_PerceivedSeverity;

extern const Meta_Property
_CIM_Indication_OtherSeverity;

extern const Meta_Reference
_MyIndication_object;

const Meta_Reference _MyIndication_object =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_EMBEDDED_OBJECT,
    "object",
    0, /* meta_qualifiers */
    0, /* num_meta_qualifiers */
    0, /* subscript */
    &Instance::static_meta_class,
    CIMPLE_OFF(MyIndication,object)
};

static const Meta_Property
_MyIndication_DeliverIndications_return_value =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0,
    CIMPLE_OFF(MyIndication_DeliverIndications_method,return_value),
    0, /* value */
};

static Meta_Feature* _MyIndication_DeliverIndications_MFA[] =
{
    (Meta_Feature*)(void*)&_MyIndication_DeliverIndications_return_value
};

const Meta_Method
MyIndication_DeliverIndications_method::static_meta_class =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_METHOD|CIMPLE_FLAG_STATIC,
    "DeliverIndications",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _MyIndication_DeliverIndications_MFA,
    CIMPLE_ARRAY_SIZE(_MyIndication_DeliverIndications_MFA),
    sizeof(MyIndication_DeliverIndications_method),
    UINT32,
};

static Meta_Feature* _MyIndication_MFA[] =
{
    (Meta_Feature*)(void*)&_CIM_Indication_IndicationIdentifier,
    (Meta_Feature*)(void*)&_CIM_Indication_CorrelatedIndications,
    (Meta_Feature*)(void*)&_CIM_Indication_IndicationTime,
    (Meta_Feature*)(void*)&_CIM_Indication_PerceivedSeverity,
    (Meta_Feature*)(void*)&_CIM_Indication_OtherSeverity,
    (Meta_Feature*)(void*)&_MyIndication_object,
    (Meta_Feature*)(void*)&MyIndication_DeliverIndications_method::static_meta_class,
};

static const Meta_Feature_Local _locals[] =
{
    {0},
    {0},
    {0},
    {0},
    {0},
    {1},
    {1},
};

const Meta_Class MyIndication::static_meta_class =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_INDICATION,
    "MyIndication",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _MyIndication_MFA,
    CIMPLE_ARRAY_SIZE(_MyIndication_MFA),
    sizeof(MyIndication),
    _locals,
    &CIM_Indication::static_meta_class,
    0, /* num_keys */
    &__meta_repository_0123968F036E16988B8DE82DE4E1291A,
};

CIMPLE_NAMESPACE_END

