//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.0.22
//
//==============================================================================

#include <cimple/cimple.h>
#include "repository.h"

CIMPLE_NAMESPACE_BEGIN

/*[2528]*/
static const Meta_Class* _meta_classes[] =
{
    &CIM_Indication::static_meta_class,
    &MyIndication::static_meta_class,
    &DerivedIndication::static_meta_class,
};

static const size_t _num_meta_classes = CIMPLE_ARRAY_SIZE(_meta_classes);

extern const Meta_Repository __meta_repository_59AB7750F9FF18899D6174C1EBEDB037;

/*[2555]*/
const Meta_Repository __meta_repository_59AB7750F9FF18899D6174C1EBEDB037 =
{
    _meta_classes,
    _num_meta_classes,
};

CIMPLE_NAMESPACE_END
