/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.1.0
//
//==============================================================================

#ifndef _cimple_Y_h
#define _cimple_Y_h

#include <cimple/cimple.h>
#include "X.h"

CIMPLE_NAMESPACE_BEGIN

// Y keys:
//     Key

/*[1195]*/
class Y : public Instance
{
public:
    // X features:
    Property<uint32> Key;
    Property<Array_String> Names;

    // Y features:
    Property<boolean> Flag;

    CIMPLE_CLASS(Y)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_Y_h */
