ROOT = $(PEGASUS_ROOT)
DIR = cimple/providers/CIM_StoragePool/meth/create_CIM_ConcreteJob
include $(ROOT)/mak/config.mak
LIBRARIES = pegclient pegcommon

EXTRA_INCLUDES = $(SYS_INCLUDES)

PROGRAM = create_CIM_ConcreteJob

SOURCES = main.cpp

include $(ROOT)/mak/program.mak

tests:

genclass:


live-tests:
	$(PROGRAM)
