ROOT = $(PEGASUS_ROOT)
DIR = Pegasus/Client/tests/foo2
include $(ROOT)/mak/config.mak
LIBRARIES = pegclient pegcommon

EXTRA_INCLUDES = $(SYS_INCLUDES)

PROGRAM = call_foo2

SOURCES = main.cpp

include $(ROOT)/mak/program.mak

tests:

genclass:

chksrc:
	chksrc $(SOURCES)
