//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#ifndef _AX_h
#define _AX_h

#include <cimple/cimple.h>
#include "X.h"
#include "X.h"

CIMPLE_NAMESPACE_BEGIN

class AX : public Instance
{
public:
    // AX features:
    X* left;
    X* right;

    CIMPLE_CLASS(AX)
};

CIMPLE_NAMESPACE_END

#endif /* _AX_h */
