/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.1.2
//
//==============================================================================

#ifndef _cimple_Y_h
#define _cimple_Y_h

#include <cimple/cimple.h>
#include "X.h"

CIMPLE_NAMESPACE_BEGIN

// Y keys:

/*[928]*/
class Y : public Instance
{
public:
    // X features:
    Property<uint32> x;

    // Y features:
    Property<uint32> y;

    CIMPLE_CLASS(Y)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_Y_h */
