/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.0.3
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "Z.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Property
_X_x;

extern const Meta_Property
_Y_y;

extern const Meta_Property
_Z_z;

const Meta_Property
_Z_z =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "z",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0, /* subscript */
    CIMPLE_OFF(Z,z),
    0, /* value */
};

static Meta_Feature* _Z_MFA[] =
{
    (Meta_Feature*)(void*)&_X_x,
    (Meta_Feature*)(void*)&_Y_y,
    (Meta_Feature*)(void*)&_Z_z,
};

static const Meta_Feature_Local _locals[] =
{
    {0},
    {0},
    {1},
};

const Meta_Class Z::static_meta_class =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_CLASS,
    "Z",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _Z_MFA,
    CIMPLE_ARRAY_SIZE(_Z_MFA),
    sizeof(Z),
    _locals,
    &Y::static_meta_class,
    0, /* num_keys */
    0,
};

CIMPLE_NAMESPACE_END

CIMPLE_ID("$Header: /home/cvs/cimple/src/cimple/tests/class/Z.cpp,v 1.21 2007/06/19 15:24:54 mbrasher-public Exp $");
