TOP = ../../../..
include $(TOP)/mak/config.mak

BINARY = test_scheduler
SOURCES = main.cpp
LIBRARIES = cimple
DEFINES += -DCIMPLE_LINK_STATIC_LIBCIMPLE

include $(TOP)/mak/rules.mak

tests:

genclass:
