TOP = ../../..
include $(TOP)/mak/config.mak

DIRS = \
    mutex \
    array \
    string \
    property \
    meta \
    sizes \
    cast \
    time \
    join \
    encoding \
    model_path \
    class

BROKEN_TESTS = \
    datetime \

include $(TOP)/mak/rules.mak
