TOP = ../../..
include $(TOP)/mak/config.mak

DIRS = \
    mutex \
    array \
    string \
    property \
    sizes \
    time \
    model_path \
    cast \
    class \
    clone \
    print \
    datetime

include $(TOP)/mak/rules.mak
