/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.1.0
//
//==============================================================================

#ifndef _cimple_CMPL_ResponseStressTest_h
#define _cimple_CMPL_ResponseStressTest_h

#include <cimple/cimple.h>

CIMPLE_NAMESPACE_BEGIN

// CMPL_ResponseStressTest keys:
//     Id

/*[1204]*/
class CMPL_ResponseStressTest : public Instance
{
public:
    // CMPL_ResponseStressTest features:
    Property<uint64> Id;
    Property<uint64> SequenceNumber;
    Property<uint64> ResponseCount;
    Property<uint64> RequestedInstanceSize;
    Property<String> Pattern;
    Property<uint64> interval;
    Property<String> S1;
    Property<String> S2;
    Property<String> S3;
    Property<String> S4;
    Property<String> S5;
    Property<uint64> totalTime;

    CIMPLE_CLASS(CMPL_ResponseStressTest)
};

/*[1290]*/
class CMPL_ResponseStressTest_set_method : public Instance
{
public:
    Property<uint64> ResponseCount;
    Property<uint64> ResponseInstanceSize;
    Property<uint32> return_value;
    CIMPLE_METHOD(CMPL_ResponseStressTest_set_method)
};

/*[1290]*/
class CMPL_ResponseStressTest_get_method : public Instance
{
public:
    Property<uint64> ResponseCount;
    Property<uint64> ResponseInstanceSize;
    Property<uint32> return_value;
    CIMPLE_METHOD(CMPL_ResponseStressTest_get_method)
};

/*[1290]*/
class CMPL_ResponseStressTest_stop_method : public Instance
{
public:
    Property<uint32> return_value;
    CIMPLE_METHOD(CMPL_ResponseStressTest_stop_method)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_CMPL_ResponseStressTest_h */
