// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
//  CIM_iSCSISessionStatistics
// ==================================================================
   [Experimental, UMLPackagePath ( "CIM::Network::iSCSI" ),
       Version ( "2.8.1000" ), Description (
       "Traffic and error statistics for an iSCSI Session. An instance "
       "of this class will be associated by ElementStatisticalData to "
       "the instance of iSCSISession.")]
class CIM_iSCSISessionStatistics : CIM_StatisticalData {

      [Description (
          "The count of Command PDUs transferred on this session."), 
       Counter, 
       MappingStrings { "MIB.IETF|iSCSI-MIB.iscsiSsnCmdPDUs" }]
   uint64 CommandPDUsTransferred;

      [Description (
          "The count of Response PDUs transferred on this session."), 
       Counter, 
       MappingStrings { "MIB.IETF|iSCSI-MIB.iscsiSsnRspPDUs" }]
   uint64 ResponsePDUsTransferred;

      [Description (
          "The count of bytes(data octets) that were transmitted by "
          "the local iSCSI node on this session."), 
       Units ( "Bytes" ), Counter, 
       MappingStrings { "MIB.IETF|iSCSI-MIB.iscsiSsnTxDataOctets" }]
   uint64 BytesTransmitted;

      [Description (
          "The count of bytes(data octets) that were received by the "
          "local iSCSI node on this session."), 
       Units ( "Bytes" ), Counter, 
       MappingStrings { "MIB.IETF|iSCSI-MIB.iscsiSsnRxDataOctets" }]
   uint64 BytesReceived;

      [Description (
          "The count of PDUs which were received on the session and "
          "contained header or data digest errors."), 
       Counter, 
       MappingStrings { "MIB.IETF|iSCSI-MIB.iscsiSsnDigestErrors" }]
   uint64 DigestErrors;

      [Description (
          "The count of connections within this session which have "
          "been terminated due to timeout."), 
       Counter, 
       MappingStrings { "MIB.IETF|iSCSI-MIB.iscsiSsnCxnTimeoutErrors" }]
   uint64 ConnectionTimeoutErrors;
};
