/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.0.7
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "Assoc.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Reference
_Assoc_Left;

const Meta_Reference
_Assoc_Left =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_KEY,
    "Left",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    0, /* subscript */
    &CIM_Job::static_meta_class,
    CIMPLE_OFF(Assoc,Left)
};

extern const Meta_Reference
_Assoc_Right;

const Meta_Reference
_Assoc_Right =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_REFERENCE|CIMPLE_FLAG_KEY,
    "Right",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    0, /* subscript */
    &CIM_Job::static_meta_class,
    CIMPLE_OFF(Assoc,Right)
};

static Meta_Feature* _Assoc_MFA[] =
{
    (Meta_Feature*)(void*)&_Assoc_Left,
    (Meta_Feature*)(void*)&_Assoc_Right,
};

static const Meta_Feature_Local _locals[] =
{
    {1},
    {1},
};

const Meta_Class Assoc::static_meta_class =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_ASSOCIATION,
    "Assoc",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _Assoc_MFA,
    CIMPLE_ARRAY_SIZE(_Assoc_MFA),
    sizeof(Assoc),
    _locals,
    0, /* super_class */ 
    2, /* num_keys */
    0,
};

CIMPLE_NAMESPACE_END

