/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.0.22
//
//==============================================================================

#ifndef _cimple_Class3_h
#define _cimple_Class3_h

#include <cimple/cimple.h>
#include "Class1.h"
#include "Class1.h"
#include "Class1.h"
#include "Class1.h"
#include "Class1.h"
#include "Class1.h"
#include "Class1.h"
#include "Class1.h"
#include "Class1.h"
#include "Class1.h"
#include "Class1.h"

CIMPLE_NAMESPACE_BEGIN

// Class3 keys:
//     Key

/*[928]*/
class Class3 : public Instance
{
public:
    // Class3 features:
    Property<uint32> Key;
    Property<boolean> BooleanScalar;
    Property<uint8> Uint8Scalar;
    Property<sint8> Sint8Scalar;
    Property<uint16> Uint16Scalar;
    Property<sint16> Sint16Scalar;
    Property<uint32> Uint32Scalar;
    Property<sint32> Sint32Scalar;
    Property<uint64> Uint64Scalar;
    Property<sint64> Sint64Scalar;
    Property<real32> Real32Scalar;
    Property<real64> Real64Scalar;
    Property<char16> Char16Scalar;
    Property<String> StringScalar;
    Property<Datetime> DatetimeScalar;
    Class1* InstanceScalar;
    Instance* ObjectScalar;
    Property<Array_boolean> BooleanArray;
    Property<Array_uint8> Uint8Array;
    Property<Array_sint8> Sint8Array;
    Property<Array_uint16> Uint16Array;
    Property<Array_sint16> Sint16Array;
    Property<Array_uint32> Uint32Array;
    Property<Array_sint32> Sint32Array;
    Property<Array_uint64> Uint64Array;
    Property<Array_sint64> Sint64Array;
    Property<Array_real32> Real32Array;
    Property<Array_real64> Real64Array;
    Property<Array_char16> Char16Array;
    Property<Array_String> StringArray;
    Property<Array_Datetime> DatetimeArray;
    Property< Array<Class1*> > InstanceArray;
    Property< Array<Instance*> > ObjectArray;

    CIMPLE_CLASS(Class3)
};

/*[1014]*/
class Class3_BooleanReturn_method : public Instance
{
public:
    Property<boolean> return_value;
    CIMPLE_METHOD(Class3_BooleanReturn_method)
};

/*[1014]*/
class Class3_Uint8Return_method : public Instance
{
public:
    Property<uint8> return_value;
    CIMPLE_METHOD(Class3_Uint8Return_method)
};

/*[1014]*/
class Class3_Sint8Return_method : public Instance
{
public:
    Property<sint8> return_value;
    CIMPLE_METHOD(Class3_Sint8Return_method)
};

/*[1014]*/
class Class3_Uint16Return_method : public Instance
{
public:
    Property<uint16> return_value;
    CIMPLE_METHOD(Class3_Uint16Return_method)
};

/*[1014]*/
class Class3_Sint16Return_method : public Instance
{
public:
    Property<sint16> return_value;
    CIMPLE_METHOD(Class3_Sint16Return_method)
};

/*[1014]*/
class Class3_Uint32Return_method : public Instance
{
public:
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_Uint32Return_method)
};

/*[1014]*/
class Class3_Sint32Return_method : public Instance
{
public:
    Property<sint32> return_value;
    CIMPLE_METHOD(Class3_Sint32Return_method)
};

/*[1014]*/
class Class3_Uint64Return_method : public Instance
{
public:
    Property<uint64> return_value;
    CIMPLE_METHOD(Class3_Uint64Return_method)
};

/*[1014]*/
class Class3_Sint64Return_method : public Instance
{
public:
    Property<sint64> return_value;
    CIMPLE_METHOD(Class3_Sint64Return_method)
};

/*[1014]*/
class Class3_Real32Return_method : public Instance
{
public:
    Property<real32> return_value;
    CIMPLE_METHOD(Class3_Real32Return_method)
};

/*[1014]*/
class Class3_Real64Return_method : public Instance
{
public:
    Property<real64> return_value;
    CIMPLE_METHOD(Class3_Real64Return_method)
};

/*[1014]*/
class Class3_Char16Return_method : public Instance
{
public:
    Property<char16> return_value;
    CIMPLE_METHOD(Class3_Char16Return_method)
};

/*[1014]*/
class Class3_StringReturn_method : public Instance
{
public:
    Property<String> return_value;
    CIMPLE_METHOD(Class3_StringReturn_method)
};

/*[1014]*/
class Class3_DatetimeReturn_method : public Instance
{
public:
    Property<Datetime> return_value;
    CIMPLE_METHOD(Class3_DatetimeReturn_method)
};

/*[1014]*/
class Class3_InstanceReturn_method : public Instance
{
public:
    Class1* return_value;
    CIMPLE_METHOD(Class3_InstanceReturn_method)
};

/*[1014]*/
class Class3_ObjectReturn_method : public Instance
{
public:
    Instance* return_value;
    CIMPLE_METHOD(Class3_ObjectReturn_method)
};

/*[1014]*/
class Class3_BooleanScalarParams_method : public Instance
{
public:
    Property<boolean> p1;
    Property<boolean> p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_BooleanScalarParams_method)
};

/*[1014]*/
class Class3_Uint8ScalarParams_method : public Instance
{
public:
    Property<uint8> p1;
    Property<uint8> p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_Uint8ScalarParams_method)
};

/*[1014]*/
class Class3_Sint8ScalarParams_method : public Instance
{
public:
    Property<sint8> p1;
    Property<sint8> p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_Sint8ScalarParams_method)
};

/*[1014]*/
class Class3_Uint16ScalarParams_method : public Instance
{
public:
    Property<uint16> p1;
    Property<uint16> p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_Uint16ScalarParams_method)
};

/*[1014]*/
class Class3_Sint16ScalarParams_method : public Instance
{
public:
    Property<sint16> p1;
    Property<sint16> p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_Sint16ScalarParams_method)
};

/*[1014]*/
class Class3_Uint32ScalarParams_method : public Instance
{
public:
    Property<uint32> p1;
    Property<uint32> p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_Uint32ScalarParams_method)
};

/*[1014]*/
class Class3_Sint32ScalarParams_method : public Instance
{
public:
    Property<sint32> p1;
    Property<sint32> p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_Sint32ScalarParams_method)
};

/*[1014]*/
class Class3_Uint64ScalarParams_method : public Instance
{
public:
    Property<uint64> p1;
    Property<uint64> p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_Uint64ScalarParams_method)
};

/*[1014]*/
class Class3_Sint64ScalarParams_method : public Instance
{
public:
    Property<sint64> p1;
    Property<sint64> p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_Sint64ScalarParams_method)
};

/*[1014]*/
class Class3_Real32ScalarParams_method : public Instance
{
public:
    Property<real32> p1;
    Property<real32> p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_Real32ScalarParams_method)
};

/*[1014]*/
class Class3_Real64ScalarParams_method : public Instance
{
public:
    Property<real64> p1;
    Property<real64> p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_Real64ScalarParams_method)
};

/*[1014]*/
class Class3_Char16ScalarParams_method : public Instance
{
public:
    Property<char16> p1;
    Property<char16> p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_Char16ScalarParams_method)
};

/*[1014]*/
class Class3_StringScalarParams_method : public Instance
{
public:
    Property<String> p1;
    Property<String> p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_StringScalarParams_method)
};

/*[1014]*/
class Class3_DatetimeScalarParams_method : public Instance
{
public:
    Property<Datetime> p1;
    Property<Datetime> p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_DatetimeScalarParams_method)
};

/*[1014]*/
class Class3_ObjectScalarParams_method : public Instance
{
public:
    Instance* p1;
    Instance* p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_ObjectScalarParams_method)
};

/*[1014]*/
class Class3_InstanceScalarParams_method : public Instance
{
public:
    Class1* p1;
    Class1* p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_InstanceScalarParams_method)
};

/*[1014]*/
class Class3_ReferenceScalarParams_method : public Instance
{
public:
    Class1* p1;
    Class1* p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_ReferenceScalarParams_method)
};

/*[1014]*/
class Class3_BooleanArrayParams_method : public Instance
{
public:
    Property<Array_boolean> p1;
    Property<Array_boolean> p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_BooleanArrayParams_method)
};

/*[1014]*/
class Class3_Uint8ArrayParams_method : public Instance
{
public:
    Property<Array_uint8> p1;
    Property<Array_uint8> p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_Uint8ArrayParams_method)
};

/*[1014]*/
class Class3_Sint8ArrayParams_method : public Instance
{
public:
    Property<Array_sint8> p1;
    Property<Array_sint8> p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_Sint8ArrayParams_method)
};

/*[1014]*/
class Class3_Uint16ArrayParams_method : public Instance
{
public:
    Property<Array_uint16> p1;
    Property<Array_uint16> p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_Uint16ArrayParams_method)
};

/*[1014]*/
class Class3_Sint16ArrayParams_method : public Instance
{
public:
    Property<Array_sint16> p1;
    Property<Array_sint16> p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_Sint16ArrayParams_method)
};

/*[1014]*/
class Class3_Uint32ArrayParams_method : public Instance
{
public:
    Property<Array_uint32> p1;
    Property<Array_uint32> p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_Uint32ArrayParams_method)
};

/*[1014]*/
class Class3_Sint32ArrayParams_method : public Instance
{
public:
    Property<Array_sint32> p1;
    Property<Array_sint32> p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_Sint32ArrayParams_method)
};

/*[1014]*/
class Class3_Uint64ArrayParams_method : public Instance
{
public:
    Property<Array_uint64> p1;
    Property<Array_uint64> p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_Uint64ArrayParams_method)
};

/*[1014]*/
class Class3_Sint64ArrayParams_method : public Instance
{
public:
    Property<Array_sint64> p1;
    Property<Array_sint64> p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_Sint64ArrayParams_method)
};

/*[1014]*/
class Class3_Real32ArrayParams_method : public Instance
{
public:
    Property<Array_real32> p1;
    Property<Array_real32> p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_Real32ArrayParams_method)
};

/*[1014]*/
class Class3_Real64ArrayParams_method : public Instance
{
public:
    Property<Array_real64> p1;
    Property<Array_real64> p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_Real64ArrayParams_method)
};

/*[1014]*/
class Class3_Char16ArrayParams_method : public Instance
{
public:
    Property<Array_char16> p1;
    Property<Array_char16> p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_Char16ArrayParams_method)
};

/*[1014]*/
class Class3_StringArrayParams_method : public Instance
{
public:
    Property<Array_String> p1;
    Property<Array_String> p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_StringArrayParams_method)
};

/*[1014]*/
class Class3_DatetimeArrayParams_method : public Instance
{
public:
    Property<Array_Datetime> p1;
    Property<Array_Datetime> p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_DatetimeArrayParams_method)
};

/*[1014]*/
class Class3_ObjectArrayParams_method : public Instance
{
public:
    Property< Array<Instance*> > p1;
    Property< Array<Instance*> > p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_ObjectArrayParams_method)
};

/*[1014]*/
class Class3_InstanceArrayParams_method : public Instance
{
public:
    Property< Array<Class1*> > p1;
    Property< Array<Class1*> > p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_InstanceArrayParams_method)
};

/*[1014]*/
class Class3_ReferenceArrayParams_method : public Instance
{
public:
    Property< Array<Class1*> > p1;
    Property< Array<Class1*> > p2;
    Property<uint32> return_value;
    CIMPLE_METHOD(Class3_ReferenceArrayParams_method)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_Class3_h */
