class Class1
{
    [Key] uint32 Key;
};

class Class2 : Class1
{
    [Key] uint32 Key;
};

[Association]
class Assoc1
{
   [Key] Class1 REF Left;
   [Key] Class1 REF Right;
};

[Association]
class Assoc2 : Assoc1
{
   [Key] Class2 REF Left;
   [Key] Class2 REF Right;
};

class Class3
{
    [Key] uint32 Key;

    // Scalar properties:
    boolean BooleanScalar;
    uint8 Uint8Scalar;
    sint8 Sint8Scalar;
    uint16 Uint16Scalar;
    sint16 Sint16Scalar;
    uint32 Uint32Scalar;
    sint32 Sint32Scalar;
    uint64 Uint64Scalar;
    sint64 Sint64Scalar;
    real32 Real32Scalar;
    real64 Real64Scalar;
    char16 Char16Scalar;
    string StringScalar;
    datetime DatetimeScalar;
    [EmbeddedInstance("Class1")] string InstanceScalar;
    [EmbeddedObject] string ObjectScalar;

    // Array properties:
    boolean BooleanArray[];
    uint8 Uint8Array[];
    sint8 Sint8Array[];
    uint16 Uint16Array[];
    sint16 Sint16Array[];
    uint32 Uint32Array[];
    sint32 Sint32Array[];
    uint64 Uint64Array[];
    sint64 Sint64Array[];
    real32 Real32Array[];
    real64 Real64Array[];
    char16 Char16Array[];
    string StringArray[];
    datetime DatetimeArray[];
    [EmbeddedInstance("Class1")] string InstanceArray[];
    [EmbeddedObject] string ObjectArray[];

    // Return types:
    boolean BooleanReturn();
    uint8 Uint8Return();
    sint8 Sint8Return();
    uint16 Uint16Return();
    sint16 Sint16Return();
    uint32 Uint32Return();
    sint32 Sint32Return();
    uint64 Uint64Return();
    sint64 Sint64Return();
    real32 Real32Return();
    real64 Real64Return();
    char16 Char16Return();
    string StringReturn();
    datetime DatetimeReturn();
    [EmbeddedInstance("Class1")] string InstanceReturn();
    [EmbeddedObject] string ObjectReturn();

    // Scalar methods:
    uint32 BooleanScalarParams([In] boolean p1, [In(false), Out] boolean p2);
    uint32 Uint8ScalarParams([In] uint8 p1, [In(false), Out] uint8 p2);
    uint32 Sint8ScalarParams([In] sint8 p1, [In(false), Out] sint8 p2);
    uint32 Uint16ScalarParams([In] uint16 p1, [In(false), Out] uint16 p2);
    uint32 Sint16ScalarParams([In] sint16 p1, [In(false), Out] sint16 p2);
    uint32 Uint32ScalarParams([In] uint32 p1, [In(false), Out] uint32 p2);
    uint32 Sint32ScalarParams([In] sint32 p1, [In(false), Out] sint32 p2);
    uint32 Uint64ScalarParams([In] uint64 p1, [In(false), Out] uint64 p2);
    uint32 Sint64ScalarParams([In] sint64 p1, [In(false), Out] sint64 p2);
    uint32 Real32ScalarParams([In] real32 p1, [In(false), Out] real32 p2);
    uint32 Real64ScalarParams([In] real64 p1, [In(false), Out] real64 p2);
    uint32 Char16ScalarParams([In] char16 p1, [In(false), Out] char16 p2);
    uint32 StringScalarParams([In] string p1, [In(false), Out] string p2);
    uint32 DatetimeScalarParams([In] datetime p1, [In(false), Out] datetime p2);
    uint32 ObjectScalarParams(
        [In, EmbeddedObject] string p1,
        [In(false), Out, EmbeddedObject] string p2);
    uint32 InstanceScalarParams(
        [In, EmbeddedInstance("Class1")] string p1,
        [In(false), Out, EmbeddedInstance("Class1")] string p2);
    uint32 ReferenceScalarParams(
        [In] Class1 REF p1, [In(false), Out] Class1 REF p2);

    // Array methods:
    uint32 BooleanArrayParams([In] boolean p1[], [In(false), Out] boolean p2[]);
    uint32 Uint8ArrayParams([In] uint8 p1[], [In(false), Out] uint8 p2[]);
    uint32 Sint8ArrayParams([In] sint8 p1[], [In(false), Out] sint8 p2[]);
    uint32 Uint16ArrayParams([In] uint16 p1[], [In(false), Out] uint16 p2[]);
    uint32 Sint16ArrayParams([In] sint16 p1[], [In(false), Out] sint16 p2[]);
    uint32 Uint32ArrayParams([In] uint32 p1[], [In(false), Out] uint32 p2[]);
    uint32 Sint32ArrayParams([In] sint32 p1[], [In(false), Out] sint32 p2[]);
    uint32 Uint64ArrayParams([In] uint64 p1[], [In(false), Out] uint64 p2[]);
    uint32 Sint64ArrayParams([In] sint64 p1[], [In(false), Out] sint64 p2[]);
    uint32 Real32ArrayParams([In] real32 p1[], [In(false), Out] real32 p2[]);
    uint32 Real64ArrayParams([In] real64 p1[], [In(false), Out] real64 p2[]);
    uint32 Char16ArrayParams([In] char16 p1[], [In(false), Out] char16 p2[]);
    uint32 StringArrayParams([In] string p1[], [In(false), Out] string p2[]);
    uint32 DatetimeArrayParams(
        [In] datetime p1[], [In(false), Out] datetime p2[]);
    uint32 ObjectArrayParams(
        [In, EmbeddedObject] string p1[],
        [In(false), Out, EmbeddedObject] string p2[]);
    uint32 InstanceArrayParams(
        [In, EmbeddedInstance("Class1")] string p1[],
        [In(false), Out, EmbeddedInstance("Class1")] string p2[]);
    uint32 ReferenceArrayParams(
        [In] Class1 REF p1[], [In(false), Out] Class1 REF p2[]);
};

class President
{
    [Key] uint32 Number;
    string First;
    string Last;
};

[Association]
class Successor
{
    [Key] President REF Prev;
    [Key] President REF Next;
};

class Part
{
    [Key] uint32 Key;
};

class Whole
{
    [Key] Uint32 Key;
    [EmbeddedInstance("Part")] string emb;
};

class SuperClass
{
    [Key] Uint32 Key;
};

class SubClass : SuperClass
{
};
