/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.0.22
//
//==============================================================================

#ifndef _cimple_SubClass_h
#define _cimple_SubClass_h

#include <cimple/cimple.h>
#include "SuperClass.h"

CIMPLE_NAMESPACE_BEGIN

// SubClass keys:
//     Key

/*[928]*/
class SubClass : public Instance
{
public:
    // SuperClass features:
    Property<uint32> Key;

    // SubClass features:

    CIMPLE_CLASS(SubClass)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_SubClass_h */
