/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.0.22
//
//==============================================================================

#ifndef _cimple_SuperClass_h
#define _cimple_SuperClass_h

#include <cimple/cimple.h>

CIMPLE_NAMESPACE_BEGIN

// SuperClass keys:
//     Key

/*[928]*/
class SuperClass : public Instance
{
public:
    // SuperClass features:
    Property<uint32> Key;

    CIMPLE_CLASS(SuperClass)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_SuperClass_h */
