#pragma include("cimv211.mof")

// This is a pseudo class that only exists to implement embedded object 
// properties. In CIMPLE, these properties are pointers to real instances
// rather than strings.

/*
class Instance
{
    uint32 dummy;
};
*/
