/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#ifndef _cimple_Test2_h
#define _cimple_Test2_h

#include <cimple/cimple.h>
#include "Test1.h"
#include "Test1.h"

#if (0x00633800 > CIMPLE_VERSION)
# error "The version of genclass used to generate this file (0.99.56) is newer than the version of <cimple/cimple.h> found on the include path. Please place the matching version of <cimple/cimple.h> on the include path."
#endif

#if (0x00633800 < CIMPLE_VERSION)
# error "The version of genclass used to generate this file (0.99.56) is older than the version of <cimple/cimple.h> found on the include path. Please regenerate the sources with the matching version of genclass."
#endif


CIMPLE_NAMESPACE_BEGIN

class Test2 : public Instance
{
public:
    // Test2 features:
    Property<boolean> ref_field1;
    Property<sint8> ref_field2;
    Property<String> ref_field3;
    Test1* ref1;
    Test1* ref2;

    CIMPLE_CLASS(Test2)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_Test2_h */
