TOP = ../../../..
include $(TOP)/mak/config.mak

BINARY = call_ci_employee

SOURCES = main.cpp

LIBRARIES = cimple pegclient pegcommon

include $(TOP)/mak/pegasus.mak
include $(TOP)/mak/rules.mak

live:
	$(TARGET)
