
class ASSOC2_C
{

};

[Association]
class ASSOC2_A1
{
    ASSOC2_C ref r1;
    ASSOC2_C ref r2;
};

class ASSOC2_A2 : ASSOC2_A1
{
    ASSOC2_C ref r1 = "ASSOC2_C";
    ASSOC2_C ref r2 = "ASSOC2_C";
};

class ASSOC2_A3 : ASSOC2_A2
{
    uint32 f(uint32 x, string y, uint32 z);
};

