TOP=../../../..
include $(TOP)/mak/config.mak

all:
depend:
gen:

tests:
	$(BIN_DIR)/mofc -I $(TOP)/schema/cim2131 tests.mof
	@ $(ECHO) "+++++ passed all tests ($(BIN_DIR)/mofc)"

sub:

genclass:

CLEAN += memstream.tmp

clean:
	$(RM) $(CLEAN)

chksrc:
