TOP=../../../..
include $(TOP)/mak/config.mak

all:
depend:
gen:

tests:
	$(BIN)/mofc -I $(TOP)/schema tests.mof
	@ $(ECHO) "+++++ passed all tests ($(BIN)/mofc)"

sub:

genclass:

CLEAN += memstream.tmp

clean:
	$(RM) $(CLEAN)
