#pragma include ("CIM_Schema.mof")
#pragma include ("case.mof")
#pragma include ("flavor.mof")
#pragma include ("inst.mof")
#pragma include ("class.mof")
#pragma include ("obj_ref.mof")
#pragma include ("assoc.mof")
#pragma include ("assoc2.mof")
#pragma include ("ref.mof")
#pragma include ("refref.mof")
