// Copyright (c) 2005 DMTF.  All rights reserved.
// ==================================================================
//  CIM_SharedSecretIsShared
// ==================================================================
   [Association, Version ( "2.6.0" ), Description (
       "This relationship associates a SharedSecretService with the "
       "SecretKey it verifies.")]
class CIM_SharedSecretIsShared : CIM_ManagedCredential {

      [Override ( "Antecedent" ), Min ( 1 ), Max ( 1 ), Description (
          "The credential management service.")]
   CIM_SharedSecretService REF Antecedent;

      [Override ( "Dependent" ), Weak, Description (
          "The managed credential.")]
   CIM_SharedSecret REF Dependent;
};
