//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "D.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Property _A_a;

extern const Meta_Property _B_b;

extern const Meta_Property _C_c;

extern const Meta_Property _D_d;

const Meta_Property _D_d =
{
    CIMPLE_FLAG_PROPERTY,
    "d",
    UINT32,
    0,
    CIMPLE_OFF(D,d)
};

static Meta_Feature* _D_meta_features[] =
{
    (Meta_Feature*)&_A_a,
    (Meta_Feature*)&_B_b,
    (Meta_Feature*)&_C_c,
    (Meta_Feature*)&_D_d,
};

static const char* _super_classes[] =
{
    "C",
    "B",
    "A",
};

static const Meta_Feature_Local _locals[] =
{
    {0},
    {0},
    {0},
    {1},
};

const Meta_Class D::static_meta_class =
{
    CIMPLE_FLAG_CLASS,
    "D",
    _D_meta_features,
    CIMPLE_ARRAY_SIZE(_D_meta_features),
    sizeof(D),
    _locals,
    &C::static_meta_class,
    _super_classes,
    CIMPLE_ARRAY_SIZE(_super_classes),
    0, /* num_keys */
    0x40E298B8,/* crc */
    0,
};

CIMPLE_NAMESPACE_END

