/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.0.3
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "D.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Property
_A_a;

extern const Meta_Property
_B_b;

extern const Meta_Property
_C_c;

extern const Meta_Property
_D_d;

const Meta_Property
_D_d =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "d",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT32,
    0, /* subscript */
    CIMPLE_OFF(D,d),
    0, /* value */
};

static Meta_Feature* _D_MFA[] =
{
    (Meta_Feature*)(void*)&_A_a,
    (Meta_Feature*)(void*)&_B_b,
    (Meta_Feature*)(void*)&_C_c,
    (Meta_Feature*)(void*)&_D_d,
};

static const Meta_Feature_Local _locals[] =
{
    {0},
    {0},
    {0},
    {1},
};

const Meta_Class D::static_meta_class =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_CLASS,
    "D",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _D_MFA,
    CIMPLE_ARRAY_SIZE(_D_MFA),
    sizeof(D),
    _locals,
    &C::static_meta_class,
    0, /* num_keys */
    0,
};

CIMPLE_NAMESPACE_END

