ROOT = $(PEGASUS_ROOT)
DIR = Pegasus/Client/tests/create_link
include $(ROOT)/mak/config.mak
LIBRARIES = pegclient pegcommon

EXTRA_INCLUDES = $(SYS_INCLUDES)

PROGRAM = create_link

SOURCES = create_link.cpp

include $(ROOT)/mak/program.mak

tests:
