//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#ifndef _cimple_Sub2_h
#define _cimple_Sub2_h

#include <cimple/cimple.h>
#include "Super.h"

CIMPLE_NAMESPACE_BEGIN

class Sub2 : public Instance
{
public:
    // Super features:
    Property<uint32> key;

    // Sub2 features:
    Property<uint32> sub2;

    CIMPLE_CLASS(Sub2)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_Sub2_h */
