TOP = ../..
include $(TOP)/mak/config.mak

SH_LIBRARY = cmplcimcgi

SOURCES = module.cpp 

LIBRARIES =

FLAGS += $(SIZE_OPTIMIZATION_FLAGS)

DEFINES += -DCIMPLE_LIBCIMPLE

include $(TOP)/mak/rules.mak

genclass:
