//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.0.6
//
//==============================================================================

#include <cimple/cimple.h>
#include "repository.h"

CIMPLE_NAMESPACE_BEGIN

/*[2547]*/
static const Meta_Class* _meta_classes[] =
{
    &cmpl_test::static_meta_class,
};

static const size_t _num_meta_classes = CIMPLE_ARRAY_SIZE(_meta_classes);

extern const Meta_Repository __meta_repository_933514FD876A10F78C61A8AF373818C1;

/*[2574]*/
const Meta_Repository __meta_repository_933514FD876A10F78C61A8AF373818C1 =
{
    _meta_classes,
    _num_meta_classes,
};

CIMPLE_NAMESPACE_END
