TOP = ../../..
include $(TOP)/mak/config.mak

BINARY = ciminvoke

SOURCES = main.cpp 

LIBRARIES = pegclient pegcommon cimple

include $(TOP)/mak/pegasus.mak
include $(TOP)/mak/rules.mak
include ../check-pegasus.mak
