/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.1.2
//
//==============================================================================

#ifndef _cimple_Fan_h
#define _cimple_Fan_h

#include <cimple/cimple.h>

CIMPLE_NAMESPACE_BEGIN

// Fan keys:
//     DeviceID

/*[928]*/
class Fan : public Instance
{
public:
    // Fan features:
    Property<String> DeviceID;
    Property<uint64> Speed;
    Property<uint64> DesiredSpeed;

    CIMPLE_CLASS(Fan)
};

/*[1014]*/
class Fan_SetSpeed_method : public Instance
{
public:
    Property<uint64> DesiredSpeed;
    Property<uint32> return_value;
    CIMPLE_METHOD(Fan_SetSpeed_method)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_Fan_h */
