//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "CIM_Job.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

CIMPLE_HIDE
extern const Meta_Property _CIM_ManagedElement_Caption;

CIMPLE_HIDE
extern const Meta_Property _CIM_ManagedElement_Description;

CIMPLE_HIDE
extern const Meta_Property _CIM_ManagedElement_ElementName;

CIMPLE_HIDE
extern const Meta_Property _CIM_ManagedSystemElement_InstallDate;

CIMPLE_HIDE
extern const Meta_Property _CIM_ManagedSystemElement_Name;

CIMPLE_HIDE
extern const Meta_Property _CIM_ManagedSystemElement_OperationalStatus;

CIMPLE_HIDE
extern const Meta_Property _CIM_ManagedSystemElement_StatusDescriptions;

CIMPLE_HIDE
extern const Meta_Property _CIM_ManagedSystemElement_Status;

CIMPLE_HIDE
extern const Meta_Property _CIM_Job_JobStatus;

const Meta_Property _CIM_Job_JobStatus =
{
    CIMPLE_FLAG_PROPERTY,
    "JobStatus",
    STRING,
    0,
    CIMPLE_OFF(CIM_Job,JobStatus)
};

CIMPLE_HIDE
extern const Meta_Property _CIM_Job_TimeSubmitted;

const Meta_Property _CIM_Job_TimeSubmitted =
{
    CIMPLE_FLAG_PROPERTY,
    "TimeSubmitted",
    DATETIME,
    0,
    CIMPLE_OFF(CIM_Job,TimeSubmitted)
};

CIMPLE_HIDE
extern const Meta_Property _CIM_Job_ScheduledStartTime;

const Meta_Property _CIM_Job_ScheduledStartTime =
{
    CIMPLE_FLAG_PROPERTY,
    "ScheduledStartTime",
    DATETIME,
    0,
    CIMPLE_OFF(CIM_Job,ScheduledStartTime)
};

CIMPLE_HIDE
extern const Meta_Property _CIM_Job_StartTime;

const Meta_Property _CIM_Job_StartTime =
{
    CIMPLE_FLAG_PROPERTY,
    "StartTime",
    DATETIME,
    0,
    CIMPLE_OFF(CIM_Job,StartTime)
};

CIMPLE_HIDE
extern const Meta_Property _CIM_Job_ElapsedTime;

const Meta_Property _CIM_Job_ElapsedTime =
{
    CIMPLE_FLAG_PROPERTY,
    "ElapsedTime",
    DATETIME,
    0,
    CIMPLE_OFF(CIM_Job,ElapsedTime)
};

CIMPLE_HIDE
extern const Meta_Property _CIM_Job_JobRunTimes;

const Meta_Property _CIM_Job_JobRunTimes =
{
    CIMPLE_FLAG_PROPERTY,
    "JobRunTimes",
    UINT32,
    0,
    CIMPLE_OFF(CIM_Job,JobRunTimes)
};

CIMPLE_HIDE
extern const Meta_Property _CIM_Job_RunMonth;

const Meta_Property _CIM_Job_RunMonth =
{
    CIMPLE_FLAG_PROPERTY,
    "RunMonth",
    UINT8,
    0,
    CIMPLE_OFF(CIM_Job,RunMonth)
};

CIMPLE_HIDE
extern const Meta_Property _CIM_Job_RunDay;

const Meta_Property _CIM_Job_RunDay =
{
    CIMPLE_FLAG_PROPERTY,
    "RunDay",
    SINT8,
    0,
    CIMPLE_OFF(CIM_Job,RunDay)
};

CIMPLE_HIDE
extern const Meta_Property _CIM_Job_RunDayOfWeek;

const Meta_Property _CIM_Job_RunDayOfWeek =
{
    CIMPLE_FLAG_PROPERTY,
    "RunDayOfWeek",
    SINT8,
    0,
    CIMPLE_OFF(CIM_Job,RunDayOfWeek)
};

CIMPLE_HIDE
extern const Meta_Property _CIM_Job_RunStartInterval;

const Meta_Property _CIM_Job_RunStartInterval =
{
    CIMPLE_FLAG_PROPERTY,
    "RunStartInterval",
    DATETIME,
    0,
    CIMPLE_OFF(CIM_Job,RunStartInterval)
};

CIMPLE_HIDE
extern const Meta_Property _CIM_Job_LocalOrUtcTime;

const Meta_Property _CIM_Job_LocalOrUtcTime =
{
    CIMPLE_FLAG_PROPERTY,
    "LocalOrUtcTime",
    UINT16,
    0,
    CIMPLE_OFF(CIM_Job,LocalOrUtcTime)
};

CIMPLE_HIDE
extern const Meta_Property _CIM_Job_UntilTime;

const Meta_Property _CIM_Job_UntilTime =
{
    CIMPLE_FLAG_PROPERTY,
    "UntilTime",
    DATETIME,
    0,
    CIMPLE_OFF(CIM_Job,UntilTime)
};

CIMPLE_HIDE
extern const Meta_Property _CIM_Job_Notify;

const Meta_Property _CIM_Job_Notify =
{
    CIMPLE_FLAG_PROPERTY,
    "Notify",
    STRING,
    0,
    CIMPLE_OFF(CIM_Job,Notify)
};

CIMPLE_HIDE
extern const Meta_Property _CIM_Job_Owner;

const Meta_Property _CIM_Job_Owner =
{
    CIMPLE_FLAG_PROPERTY,
    "Owner",
    STRING,
    0,
    CIMPLE_OFF(CIM_Job,Owner)
};

CIMPLE_HIDE
extern const Meta_Property _CIM_Job_Priority;

const Meta_Property _CIM_Job_Priority =
{
    CIMPLE_FLAG_PROPERTY,
    "Priority",
    UINT32,
    0,
    CIMPLE_OFF(CIM_Job,Priority)
};

CIMPLE_HIDE
extern const Meta_Property _CIM_Job_PercentComplete;

const Meta_Property _CIM_Job_PercentComplete =
{
    CIMPLE_FLAG_PROPERTY,
    "PercentComplete",
    UINT16,
    0,
    CIMPLE_OFF(CIM_Job,PercentComplete)
};

CIMPLE_HIDE
extern const Meta_Property _CIM_Job_DeleteOnCompletion;

const Meta_Property _CIM_Job_DeleteOnCompletion =
{
    CIMPLE_FLAG_PROPERTY,
    "DeleteOnCompletion",
    BOOLEAN,
    0,
    CIMPLE_OFF(CIM_Job,DeleteOnCompletion)
};

CIMPLE_HIDE
extern const Meta_Property _CIM_Job_ErrorCode;

const Meta_Property _CIM_Job_ErrorCode =
{
    CIMPLE_FLAG_PROPERTY,
    "ErrorCode",
    UINT16,
    0,
    CIMPLE_OFF(CIM_Job,ErrorCode)
};

CIMPLE_HIDE
extern const Meta_Property _CIM_Job_ErrorDescription;

const Meta_Property _CIM_Job_ErrorDescription =
{
    CIMPLE_FLAG_PROPERTY,
    "ErrorDescription",
    STRING,
    0,
    CIMPLE_OFF(CIM_Job,ErrorDescription)
};

CIMPLE_HIDE
extern const Meta_Property _CIM_Job_RecoveryAction;

const Meta_Property _CIM_Job_RecoveryAction =
{
    CIMPLE_FLAG_PROPERTY,
    "RecoveryAction",
    UINT16,
    0,
    CIMPLE_OFF(CIM_Job,RecoveryAction)
};

CIMPLE_HIDE
extern const Meta_Property _CIM_Job_OtherRecoveryAction;

const Meta_Property _CIM_Job_OtherRecoveryAction =
{
    CIMPLE_FLAG_PROPERTY,
    "OtherRecoveryAction",
    STRING,
    0,
    CIMPLE_OFF(CIM_Job,OtherRecoveryAction)
};

static const Meta_Property _CIM_Job_KillJob_DeleteOnKill =
{
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_IN,
    "DeleteOnKill",
    BOOLEAN,
    0,
    CIMPLE_OFF(CIM_Job_KillJob_method,DeleteOnKill)
};

static const Meta_Property _CIM_Job_KillJob_return_value =
{
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_OUT,
    "return_value",
    UINT32,
    0,
    CIMPLE_OFF(CIM_Job_KillJob_method,return_value)
};

static Meta_Feature* _CIM_Job_KillJob_meta_features[] =
{
    (Meta_Feature*)&_CIM_Job_KillJob_DeleteOnKill,
    (Meta_Feature*)&_CIM_Job_KillJob_return_value
};

const Meta_Method CIM_Job_KillJob_method::static_meta_class =
{
    CIMPLE_FLAG_METHOD,
    "KillJob",
    _CIM_Job_KillJob_meta_features,
    CIMPLE_ARRAY_SIZE(_CIM_Job_KillJob_meta_features),
    sizeof(CIM_Job_KillJob_method),
    UINT32,
};

static Meta_Feature* _CIM_Job_meta_features[] =
{
    (Meta_Feature*)&_CIM_ManagedElement_Caption,
    (Meta_Feature*)&_CIM_ManagedElement_Description,
    (Meta_Feature*)&_CIM_ManagedElement_ElementName,
    (Meta_Feature*)&_CIM_ManagedSystemElement_InstallDate,
    (Meta_Feature*)&_CIM_ManagedSystemElement_Name,
    (Meta_Feature*)&_CIM_ManagedSystemElement_OperationalStatus,
    (Meta_Feature*)&_CIM_ManagedSystemElement_StatusDescriptions,
    (Meta_Feature*)&_CIM_ManagedSystemElement_Status,
    (Meta_Feature*)&_CIM_Job_JobStatus,
    (Meta_Feature*)&_CIM_Job_TimeSubmitted,
    (Meta_Feature*)&_CIM_Job_ScheduledStartTime,
    (Meta_Feature*)&_CIM_Job_StartTime,
    (Meta_Feature*)&_CIM_Job_ElapsedTime,
    (Meta_Feature*)&_CIM_Job_JobRunTimes,
    (Meta_Feature*)&_CIM_Job_RunMonth,
    (Meta_Feature*)&_CIM_Job_RunDay,
    (Meta_Feature*)&_CIM_Job_RunDayOfWeek,
    (Meta_Feature*)&_CIM_Job_RunStartInterval,
    (Meta_Feature*)&_CIM_Job_LocalOrUtcTime,
    (Meta_Feature*)&_CIM_Job_UntilTime,
    (Meta_Feature*)&_CIM_Job_Notify,
    (Meta_Feature*)&_CIM_Job_Owner,
    (Meta_Feature*)&_CIM_Job_Priority,
    (Meta_Feature*)&_CIM_Job_PercentComplete,
    (Meta_Feature*)&_CIM_Job_DeleteOnCompletion,
    (Meta_Feature*)&_CIM_Job_ErrorCode,
    (Meta_Feature*)&_CIM_Job_ErrorDescription,
    (Meta_Feature*)&_CIM_Job_RecoveryAction,
    (Meta_Feature*)&_CIM_Job_OtherRecoveryAction,
    (Meta_Feature*)&CIM_Job_KillJob_method::static_meta_class,
};

const Meta_Class CIM_Job::static_meta_class =
{
    CIMPLE_FLAG_CLASS,
    "CIM_Job",
    _CIM_Job_meta_features,
    CIMPLE_ARRAY_SIZE(_CIM_Job_meta_features),
    sizeof(CIM_Job),
    &CIM_LogicalElement::static_meta_class,
    0,
    0x0BC3279B,
};

CIMPLE_NAMESPACE_END

