/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#ifndef _cimple_CIM_Capabilities_h
#define _cimple_CIM_Capabilities_h

#include <cimple/cimple.h>
#include "CIM_ManagedElement.h"

CIMPLE_NAMESPACE_BEGIN

class CIM_Capabilities : public Instance
{
public:
    // CIM_ManagedElement features:
    Property<String> Caption;
    Property<String> Description;
    Property<String> ElementName;

    // CIM_Capabilities features:
    Property<String> InstanceID;

    CIMPLE_CLASS(CIM_Capabilities)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_CIM_Capabilities_h */
