/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "CIM_StorageConfigurationCapabilities.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_7B1AD485B77E19A58BACB51CE16145E8;

extern const Meta_Property
_CIM_ManagedElement_Caption;

extern const Meta_Property
_CIM_ManagedElement_Description;

extern const Meta_Property
_CIM_Capabilities_ElementName;

extern const Meta_Property
_CIM_Capabilities_InstanceID;

extern const Meta_Property
_CIM_StorageConfigurationCapabilities_SupportedAsynchronousActions;

const Meta_Property
_CIM_StorageConfigurationCapabilities_SupportedAsynchronousActions =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "SupportedAsynchronousActions",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT16,
    -1, /* subscript */
    CIMPLE_OFF(CIM_StorageConfigurationCapabilities,SupportedAsynchronousActions),
    0, /* value */
};

extern const Meta_Property
_CIM_StorageConfigurationCapabilities_SupportedSynchronousActions;

const Meta_Property
_CIM_StorageConfigurationCapabilities_SupportedSynchronousActions =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "SupportedSynchronousActions",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT16,
    -1, /* subscript */
    CIMPLE_OFF(CIM_StorageConfigurationCapabilities,SupportedSynchronousActions),
    0, /* value */
};

extern const Meta_Property
_CIM_StorageConfigurationCapabilities_SupportedStorageElementTypes;

const Meta_Property
_CIM_StorageConfigurationCapabilities_SupportedStorageElementTypes =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "SupportedStorageElementTypes",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT16,
    -1, /* subscript */
    CIMPLE_OFF(CIM_StorageConfigurationCapabilities,SupportedStorageElementTypes),
    0, /* value */
};

extern const Meta_Property
_CIM_StorageConfigurationCapabilities_SupportedStoragePoolFeatures;

const Meta_Property
_CIM_StorageConfigurationCapabilities_SupportedStoragePoolFeatures =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "SupportedStoragePoolFeatures",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT16,
    -1, /* subscript */
    CIMPLE_OFF(CIM_StorageConfigurationCapabilities,SupportedStoragePoolFeatures),
    0, /* value */
};

extern const Meta_Property
_CIM_StorageConfigurationCapabilities_SupportedStorageElementFeatures;

const Meta_Property
_CIM_StorageConfigurationCapabilities_SupportedStorageElementFeatures =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "SupportedStorageElementFeatures",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT16,
    -1, /* subscript */
    CIMPLE_OFF(CIM_StorageConfigurationCapabilities,SupportedStorageElementFeatures),
    0, /* value */
};

extern const Meta_Property
_CIM_StorageConfigurationCapabilities_SupportedCopyTypes;

const Meta_Property
_CIM_StorageConfigurationCapabilities_SupportedCopyTypes =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "SupportedCopyTypes",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT16,
    -1, /* subscript */
    CIMPLE_OFF(CIM_StorageConfigurationCapabilities,SupportedCopyTypes),
    0, /* value */
};

extern const Meta_Property
_CIM_StorageConfigurationCapabilities_InitialReplicationState;

const Meta_Property
_CIM_StorageConfigurationCapabilities_InitialReplicationState =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_READ,
    "InitialReplicationState",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    UINT16,
    0, /* subscript */
    CIMPLE_OFF(CIM_StorageConfigurationCapabilities,InitialReplicationState),
    0, /* value */
};

static Meta_Feature* _CIM_StorageConfigurationCapabilities_MFA[] =
{
    (Meta_Feature*)&_CIM_ManagedElement_Caption,
    (Meta_Feature*)&_CIM_ManagedElement_Description,
    (Meta_Feature*)&_CIM_Capabilities_ElementName,
    (Meta_Feature*)&_CIM_Capabilities_InstanceID,
    (Meta_Feature*)&_CIM_StorageConfigurationCapabilities_SupportedAsynchronousActions,
    (Meta_Feature*)&_CIM_StorageConfigurationCapabilities_SupportedSynchronousActions,
    (Meta_Feature*)&_CIM_StorageConfigurationCapabilities_SupportedStorageElementTypes,
    (Meta_Feature*)&_CIM_StorageConfigurationCapabilities_SupportedStoragePoolFeatures,
    (Meta_Feature*)&_CIM_StorageConfigurationCapabilities_SupportedStorageElementFeatures,
    (Meta_Feature*)&_CIM_StorageConfigurationCapabilities_SupportedCopyTypes,
    (Meta_Feature*)&_CIM_StorageConfigurationCapabilities_InitialReplicationState,
};

static const Meta_Feature_Local _locals[] =
{
    {0},
    {0},
    {0},
    {0},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
    {1},
};

const Meta_Class CIM_StorageConfigurationCapabilities::static_meta_class =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_CLASS,
    "CIM_StorageConfigurationCapabilities",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _CIM_StorageConfigurationCapabilities_MFA,
    CIMPLE_ARRAY_SIZE(_CIM_StorageConfigurationCapabilities_MFA),
    sizeof(CIM_StorageConfigurationCapabilities),
    _locals,
    &CIM_Capabilities::static_meta_class,
    1, /* num_keys */
    0x0EC3FBE6, /* crc */
    &__meta_repository_7B1AD485B77E19A58BACB51CE16145E8,
};

CIMPLE_NAMESPACE_END

CIMPLE_ID("$Header: /home/cvs/cimple/src/bugs/bug-a/CIM_StorageConfigurationCapabilities.cpp,v 1.4 2007/03/07 20:25:23 mbrasher-public Exp $");
