/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#ifndef _cimple_CIM_StorageConfigurationCapabilities_h
#define _cimple_CIM_StorageConfigurationCapabilities_h

#include <cimple/cimple.h>
#include "CIM_Capabilities.h"

CIMPLE_NAMESPACE_BEGIN

class CIM_StorageConfigurationCapabilities : public Instance
{
public:
    // CIM_ManagedElement features:
    Property<String> Caption;
    Property<String> Description;
    Property<String> ElementName;

    // CIM_Capabilities features:
    Property<String> InstanceID;

    // CIM_StorageConfigurationCapabilities features:
    Property<Array_uint16> SupportedAsynchronousActions;
    Property<Array_uint16> SupportedSynchronousActions;
    Property<Array_uint16> SupportedStorageElementTypes;
    Property<Array_uint16> SupportedStoragePoolFeatures;
    Property<Array_uint16> SupportedStorageElementFeatures;
    Property<Array_uint16> SupportedCopyTypes;
    Property<uint16> InitialReplicationState;

    CIMPLE_CLASS(CIM_StorageConfigurationCapabilities)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_CIM_StorageConfigurationCapabilities_h */
