//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#include <cimple/cimple.h>
#include "repository.h"

CIMPLE_NAMESPACE_BEGIN

static const Meta_Class* _meta_classes[] =
{
    &CIM_ManagedElement::static_meta_class,
    &CIM_Capabilities::static_meta_class,
    &CIM_StorageConfigurationCapabilities::static_meta_class,
    &ZZZ_StorageConfigurationServiceCapabilities::static_meta_class,
    &CIM_ManagedSystemElement::static_meta_class,
    &CIM_LogicalElement::static_meta_class,
    &CIM_Job::static_meta_class,
    &CIM_ConcreteJob::static_meta_class,
    &CIM_EnabledLogicalElement::static_meta_class,
    &CIM_System::static_meta_class,
    &CIM_ComputerSystem::static_meta_class,
    &ZZZ_ControllerSystem::static_meta_class,
    &CIM_RegisteredProfile::static_meta_class,
    &ZZZ_RegisteredProfile::static_meta_class,
    &ZZZ::static_meta_class,
};

static const size_t _num_meta_classes = CIMPLE_ARRAY_SIZE(_meta_classes);

extern const Meta_Repository __meta_repository_7B1AD485B77E19A58BACB51CE16145E8;

const Meta_Repository __meta_repository_7B1AD485B77E19A58BACB51CE16145E8 =
{
    _meta_classes,
    _num_meta_classes,
};

CIMPLE_NAMESPACE_END

CIMPLE_ID("$Header: /home/cvs/cimple/src/bugs/bug-a/repository.cpp,v 1.4 2007/03/07 20:25:23 mbrasher-public Exp $");
