//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "OtherClass.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Property _OtherClass_key;

const Meta_Property _OtherClass_key =
{
    CIMPLE_FLAG_PROPERTY|CIMPLE_FLAG_KEY,
    "key",
    STRING,
    0,
    CIMPLE_OFF(OtherClass,key)
};

extern const Meta_Property _OtherClass_num;

const Meta_Property _OtherClass_num =
{
    CIMPLE_FLAG_PROPERTY,
    "num",
    UINT32,
    0,
    CIMPLE_OFF(OtherClass,num)
};

static Meta_Feature* _OtherClass_meta_features[] =
{
    (Meta_Feature*)&_OtherClass_key,
    (Meta_Feature*)&_OtherClass_num,
};

static const Meta_Feature_Local _locals[] =
{
    {1},
    {1},
};

const Meta_Class OtherClass::static_meta_class =
{
    CIMPLE_FLAG_CLASS,
    "OtherClass",
    _OtherClass_meta_features,
    CIMPLE_ARRAY_SIZE(_OtherClass_meta_features),
    sizeof(OtherClass),
    _locals,
    0, /* super_class */ 
    0, /* super_classes */
    0, /* num_super_classes */
    1, /* num_keys */
    0xA69A6950,/* crc */
    0,
};

CIMPLE_NAMESPACE_END

