//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 2.1.0
//
//==============================================================================

#include <cimple/cimple.h>
#include "repository.h"

CIMPLE_NAMESPACE_BEGIN

/*[2823]*/
static const Meta_Class* _meta_classes[] =
{
    &Person::static_meta_class,
    &PersonLink::static_meta_class,
    &Salesman::static_meta_class,
    &SalesmanLink::static_meta_class,
};

static const size_t _num_meta_classes = CIMPLE_ARRAY_SIZE(_meta_classes);

extern const Meta_Repository __meta_repository_CFA0C0C0BF12124090F12E88B029ABDC;

/*[2850]*/
const Meta_Repository __meta_repository_CFA0C0C0BF12124090F12E88B029ABDC =
{
    _meta_classes,
    _num_meta_classes,
};

CIMPLE_NAMESPACE_END
