class Person
{
    [key] uint32 ssn;
    string first;
    string last;

    uint32 hello(
	[IN]
	String message,
	[OUT]
	String response);
};

class Salesman : Person
{
    uint32 budget;
};

[Association]
class PersonLink
{
    [key] Person ref parent;
    [key] Person ref child;
};

[Association]
class SalesmanLink : PersonLink
{
    [Key] Salesman ref parent;
    [Key] Salesman ref child;
};
