/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT THIS FILE; IT WAS AUTOMATICALLY GENERATED BY GENCLASS.
//
//==============================================================================

#include <cimple/Meta_Class.h>
#include <cimple/Meta_Property.h>
#include <cimple/Meta_Reference.h>
#include "SalesmanLink.h"

CIMPLE_NAMESPACE_BEGIN

using namespace cimple;

extern const Meta_Repository __meta_repository_415C2E0823D519D0B7C34CFC8299CB0B;

extern const Meta_Reference
_PersonLink_parent;

extern const Meta_Reference
_PersonLink_child;

static Meta_Feature* _SalesmanLink_MFA[] =
{
    (Meta_Feature*)(void*)&_PersonLink_parent,
    (Meta_Feature*)(void*)&_PersonLink_child,
};

static const Meta_Feature_Local _locals[] =
{
    {0},
    {0},
};

const Meta_Class SalesmanLink::static_meta_class =
{
    { 0 }, /* refs */
    CIMPLE_FLAG_ASSOCIATION,
    "SalesmanLink",
    0, /* meta_qualifiers */
    0, /* num_meta_qaulifiers */
    _SalesmanLink_MFA,
    CIMPLE_ARRAY_SIZE(_SalesmanLink_MFA),
    sizeof(SalesmanLink),
    _locals,
    &PersonLink::static_meta_class,
    2, /* num_keys */
    &__meta_repository_415C2E0823D519D0B7C34CFC8299CB0B,
};

CIMPLE_NAMESPACE_END

CIMPLE_ID("$Header: /home/cvs/cimple/src/providers/Person/SalesmanLink.cpp,v 1.19 2007/04/26 22:41:05 mbrasher-public Exp $");
