TOP = ../../../..
include $(TOP)/mak/config.mak

BINARY = test_string
SOURCES = test_string.cpp
LIBRARIES = cimple

include $(TOP)/mak/rules.mak

tests:
	@ $(BIN_DIR)/test_string

genclass:

xxx:
	echo $(TARGET)
