// Copyright (c) 2005 DMTF.  All rights reserved.
// <change cr="DMTFCR01083" type = "new"> Add
// PrivilegeManagementCapabilities </change>
// <change cr="ArchCR00066.004" type="add">Add UmlPackagePath
// qualifier values to CIM Schema.</change>
// ==================================================================
// PrivilegeManagementCapabilities
// ==================================================================

   [Experimental, UMLPackagePath ( "CIM::User::Privilege" ),
       Version ( "2.7.1000" ), Description (
       "A subclass of Capabilities that defines the capabilities of "
       "the Privilege Management Service.")]
class CIM_PrivilegeManagementCapabilities : CIM_Capabilities {

      [Description (
          "Set to TRUE if this PrivilegeManagementService supports "
          "association of multiple subjects or targets to a particular "
          "Privilege. If False, the AssignAccess method supports at "
          "most one entry each in the Subjects and Targets parameters.")]
   boolean SharedPrivilegeSupported = FALSE;

};

