TOP = ../..
include $(TOP)/mak/config.mak

DIRS = \
    file2c \
    dlopen \
    dlsym \
    catmod \
    gencommon \
    genclass \
    genclass/tests \
    genprov \
    genprov/tests \
    testprov \
    apriori \
    cwhat \
    cgenuuid

include $(TOP)/mak/dir.mak
