TOP = ../..
include $(TOP)/mak/config.mak

DIRS = \
    csleep \
    gencommon \
    genclass \
    genclass/tests \
    genprov \
    genmod \
    genproj \
    genprov/tests \
    file2c

XDIRS = \
    dlopen \
    cwhat \
    dlsym \
    catmod \
    apriori \
    cgenuuid

include $(TOP)/mak/dir.mak
