/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.0.3
//
//==============================================================================

#ifndef _cimple_EmbeddedClass_h
#define _cimple_EmbeddedClass_h

#include <cimple/cimple.h>

CIMPLE_NAMESPACE_BEGIN

// EmbeddedClass keys:

class EmbeddedClass : public Instance
{
public:
    // EmbeddedClass features:
    Property<String> msg;

    CIMPLE_CLASS(EmbeddedClass)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_EmbeddedClass_h */
